url = ["https://filelist.io/", ]
name = "Filelist"
nickname = "Filelist"
logo = "favicon.ico"
tracker = "reactor.filelist.io"
sp_full = 100
limit_speed = 100
tags = "影视"
iyuu = 0
sign_in = false
get_info = true
repeat_torrents = true
brush_free = false
brush_rss = false
hr_discern = false
search_torrents = true
page_index = "index.php"
page_torrents = "torrents.php?incldead=1"
page_sign_in = "attendance.php"
page_control_panel = "my.php"
page_detail = "details.php?id={}"
page_download = "download.php?id={}&passkey={}"
page_user = "userdetails.php?id={}"
page_search = "browse.php?search={}"
imdb_search = "torrents.php?cat=0&searchin=3&sort=2&search={}"
page_message = "messages.php"
page_hr = "myhr.php?hrtype=1&userid={}"
page_leeching = "getusertorrentlistajax.php?userid={}&type=leeching"
page_uploaded = "getusertorrentlistajax.php?userid={}&type=uploaded"
page_seeding = "userdetails.php?id={}"
page_completed = "getusertorrentlistajax.php?userid={}&type=completed"
page_mybonus = "shop.php"
page_viewfilelist = "viewfilelist.php?id={}"
sign_info_title = "//td[@id='outer']//td[@class='embedded']/h2/text()"
sign_info_content = "//td[@id='outer']//td[@class='embedded']/table//td//text()"
hr = false
hr_rate = 2
hr_time = 10
my_invitation_rule = "//a[@href='/invite.php']//text()[1]"
my_time_join_rule = "//td[contains(text(),'Join')]/following-sibling::td/text()"
my_latest_active_rule = "//td[contains(text(),'Last')]/following-sibling::td/text()"
my_uploaded_rule = "//td[contains(text(),'Uploaded')]/following-sibling::td/text()"
my_downloaded_rule = "//td[contains(text(),'Downloaded')]/following-sibling::td/text()"
my_ratio_rule = "//td[contains(text(),'ratio')]/following-sibling::td//text()"
my_bonus_rule = "//a[contains(@href,'/shop.php')]/text()"
my_per_hour_bonus_rule = "//b[contains(text(),'hour')]/text()"
my_score_rule = "//font[@class='color_bonus' and contains(text(),'积分')]/following-sibling::text()[1]"
my_level_rule = "//td[contains(text(),'Class')]/following-sibling::td/font[1]/text()"
my_passkey_rule = "//input[@name='resetpasskey']/following-sibling::text()[1]"
my_uid_rule = "//div[@class='status_avatar']/a[contains(@href, '/userdetails.php?id=')]/@href"
my_hr_rule = "//a[@href='myhr.php']//text()"
my_leech_rule = "//img[@class='arrowdown']/following-sibling::text()[1]"
my_publish_rule = "//p/preceding-sibling::b/text()[1]"
my_seed_rule = "//div[contains(text(),'Seeding')]/b[1]/text()"
my_seed_vol_rule = "//div[contains(text(),'Seeding')]/b[2]/text()"
my_mailbox_rule = "//a[@href='/messages.php']/font[1]/text()[1]"
my_message_title = "//img[@alt='Unread']/parent::div/following-sibling::a[1]/div/b/text()"
my_notice_rule = "//a[@href='index.php']/font[contains(text(),'条')]/text()[1]"
my_notice_title = "//td[@class='text']/div/a"
my_notice_content = "//td[@class='text']/div/a/following-sibling::div"
torrents_rule = "//table[@class='torrents']/tr"
torrent_title_rule = ".//td/a[contains(@href,'detail')]/b/text()[last()]"
torrent_subtitle_rule = ".//a[contains(@href,'detail')]/parent::td/text()[last()]"
torrent_detail_url_rule = ".//td[@class='embedded']/a[contains(@href,'detail')]/@href"
torrent_category_rule = ".//td[@class='rowfollow nowrap'][1]/a[1]/img/@title"
torrent_poster_rule = ".//table/tr/td[1]/img/@src"
torrent_magnet_url_rule = ".//td/a[contains(@href,'download.php?id=')]/@href"
torrent_size_rule = ".//td[5]/text()"
torrent_progress_rule = ".//div[contains(@title,'ing')]/@title"
torrent_hr_rule = ".//table/tr/td/img[@class='hitandrun']/@title"
torrent_sale_rule = ".//img[contains(@class,'pro_')]/@alt"
torrent_sale_expire_rule = ".//img[contains(@class,'free')]/following-sibling::font/span/@title"
torrent_release_rule = ".//td[4]/span/@title"
torrent_seeders_rule = ".//a[contains(@href,'#seeders')]/text()"
torrent_leechers_rule = ".//a[contains(@href,'#leechers')]/text()"
torrent_completers_rule = ".//a[contains(@href,'viewsnatches')]//text()"
detail_title_rule = "//h1/text()[1]"
detail_subtitle_rule = "//td[contains(text(),'副标题')]/following-sibling::td/text()[1]"
detail_download_url_rule = "//a[@class='index' and contains(@href,'download.php')]/@href"
detail_size_rule = "//td//b[contains(text(),'大小')]/following::text()[1]"
detail_category_rule = "//td/b[contains(text(),'类型')]/following-sibling::text()[1]"
detail_count_files_rule = "//td/b[contains(text(),'文件数')]/following-sibling::text()[1]"
detail_hash_rule = "//td/b[contains(text(),'Hash')]/following-sibling::text()[1]"
detail_free_rule = "//h1/b/font/@class"
detail_free_expire_rule = "//h1/b/span/@title"
detail_douban_rule = "//td/a[starts-with(@href,'https://movie.douban.com/subject/')][1]"
detail_imdb_rule = "//a[@class='faqlink' and starts-with(@href,'https://www.imdb.com/title/')]/@href"
detail_poster_rule = "//td/a/span[contains(text(),'简介')]/../../following-sibling::td//img[1]/@src"
detail_tags_rule = "//td[contains(text(),'标签')]/following-sibling::td//text()"
torrent_tags_rule = ".//a[contains(@href,'detail')]/../span[contains(@class,'tags')]/text()"
detail_hr_rule = "//h1/img[@class='hitandrun']/@title"
alive = true
page_pieces_hash_api = "api/pieces-hash"
pieces_repeat = false
proxy = true
structure = "Filelist"

[level.User]
level_id = 1
level = "User"
days = 0
uploaded = "0"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 0.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "新用户的默认级别"

[level.PowerUser]
level_id = 2
level = "PowerUser"
days = 28
uploaded = "0"
downloaded = "50"
bonus = 0.0
score = 0
ratio = 1.05
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "它可以下载大于1MB的DOX文件。该类有权申请上传者身份。"

[level.Addict]
level_id = 3
level = "Addict"
days = 0
uploaded = "0"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 0.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "此类有权请求自定义标题。此类有权提出请求。"

[level.Elite]
level_id = 4
level = "Elite"
days = 0
uploaded = "0"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 0.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "普通用户可以达到的最高等级。此类授予您为其他用户提供声誉的权利。"

[level.VIP]
level_id = 0
level = "VIP"
days = 0
uploaded = "0"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 0.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "无论下载如何，该类的最低分享率始终等于2，并且被排除在HR规则之外。可以自定义头衔。"
