url = ["https://club.hares.top/", ]
name = "hares"
nickname = "白兔"
logo = "favicon.ico"
tracker = "club.hares.top"
sp_full = 170
limit_speed = 100
tags = "影视"
iyuu = 66
sign_in = true
get_info = true
repeat_torrents = true
brush_free = true
brush_rss = true
hr_discern = false
search_torrents = true
page_index = "index.php"
page_torrents = "torrents.php?incldead=1"
page_sign_in = "attendance.php?action=sign"
page_control_panel = "usercp.php"
page_detail = "details.php?id={}"
page_download = "download.php?id={}&passkey={}"
page_user = "userdetails.php?id={}"
page_search = "torrents.php?search={}"
page_message = "messages.php"
page_hr = "myhr.php?hrtype=1&userid={}"
page_leeching = "getusertorrentlistajax.php?uid={}&type=leeching"
page_uploaded = "getusertorrentlistajax.php?uid={}&type=uploaded"
page_seeding = "getusertorrentlistajax.php?uid={}&type=seeding"
page_completed = "getusertorrentlistajax.php?uid={}&type=completed"
page_mybonus = "mybonus.php"
page_viewfilelist = "viewfilelist.php?id={}"
sign_info_title = "//td[@id='outer']//td[@class='embedded']/h2/text()"
sign_info_content = "//td[@id='outer']//td[@class='embedded']/table//td//text()"
hr = false
hr_rate = 2
hr_time = 10
my_invitation_rule = "//li/i[contains(@title,'邀请')]/following::text()[1]"
my_time_join_rule = "//td[contains(text(),'加入日期')]/following-sibling::td[1]/span/@title"
my_latest_active_rule = "//td[contains(text(),'最近动向')]/following-sibling::td[1]//span/@title"
my_uploaded_rule = "//li/i[contains(@title,'上传')]/following::text()[1]"
my_downloaded_rule = "//li/i[contains(@title,'下载')]/following::text()[1]"
my_ratio_rule = "//li/i[contains(@title,'分享率')]/following::text()[1]"
my_bonus_rule = "//li/i[contains(@title,'奶糖')]/following::text()[1]"
my_per_hour_bonus_rule = "//div[contains(text(),'每小时')]/text()[1]"
my_score_rule = "//li/i[contains(@title,'积分')]/following::text()[1]"
my_level_rule = "//li/i[contains(@title,'等级')]/following::text()[1]"
my_passkey_rule = "//td[contains(text(),'密钥')]/following-sibling::td[1]/text()"
my_uid_rule = "//span/a[contains(text(),'UID')]/@href"
my_hr_rule = "//a[@href='myhr.php']/text()"
my_leech_rule = "//li/i[contains(@title,'下载中')]/following::text()[1]"
my_publish_rule = "//p/preceding-sibling::b/text()[1]"
my_seed_rule = "//li/i[contains(@title,'做种中')]/following::text()[1]"
my_seed_vol_rule = "//tr/td[3]"
my_mailbox_rule = "//a[@href='messages.php']/font[contains(text(),'条')]/text()[1]"
my_message_title = "//i[@class='fas fa-envelope-square layui-font-red fa-3x']/parent::td/following-sibling::td/a[1]//text()"
my_notice_rule = "//a[@href='index.php']/font[contains(text(),'条')]/text()[1]"
my_notice_title = "//div[@class='home_Announcement']/span[1]"
my_notice_content = "//div[@class='home_Announcement']/span/following-sibling::div/div"
torrents_rule = "//table[@class='torrents layui-table']/tr"
torrent_title_rule = ".//td[2]/div[1]/div[1]/p/text()"
torrent_subtitle_rule = ".//a[contains(@href,'detail')]/parent::td/text()[last()]"
torrent_detail_url_rule = ".//td[2]/div[1]/div[1]/div[2]/div/a/@href"
torrent_category_rule = ".//td[1]/a/img/@title"
torrent_poster_rule = ".//td[2]/div[1]/div[1]/div[1]/a/@rel"
torrent_magnet_url_rule = ".//a[contains(@href,'download')]/@href"
torrent_size_rule = ".//td[5]/text()"
torrent_progress_rule = ".//div[contains(@title,'ing')]/@title"
torrent_hr_rule = ".//table/tr/td/img[@class='hitandrun']/@title"
torrent_sale_rule = ".//img[contains(@class,'pro_')]/@alt"
torrent_sale_expire_rule = ".//td//em/span/@title"
torrent_release_rule = ".//td[4]/span/@title"
torrent_seeders_rule = ".//td[6]/b/a/text()"
torrent_leechers_rule = ".//td[7]/b/a/text()"
torrent_completers_rule = ".//td[8]/a/b/text()"
detail_title_rule = "//h1/text()[1]"
detail_subtitle_rule = "//td[contains(text(),'副标题')]/following-sibling::td/text()[1]"
detail_download_url_rule = "//a[@title='下载种子' and contains(@href,'download.php')]/@href"
detail_size_rule = "//td//b[contains(text(),'大小')]/following::text()[1]"
detail_category_rule = "//td/b[contains(text(),'类型')]/following-sibling::text()[1]"
detail_count_files_rule = "//td/b[contains(text(),'文件数')]/following-sibling::text()[1]"
detail_hash_rule = "//td/b[contains(text(),'Hash')]/following-sibling::text()[1]"
detail_free_rule = "//h1/b/font/@class"
detail_free_expire_rule = "//h1/b/span/@title"
detail_douban_rule = "//td/a[starts-with(@href,'https://movie.douban.com/subject/')][1]"
detail_imdb_rule = "//a[@class='faqlink' and starts-with(@href,'https://www.imdb.com/title/')]/@href"
detail_poster_rule = "//td/a/span[contains(text(),'简介')]/../../following-sibling::td//img[1]/@src"
detail_tags_rule = "//td[contains(text(),'标签')]/following-sibling::td//text()"
torrent_tags_rule = ".//a[contains(@href,'detail')]/../span[contains(@class,'tags')]/text()"
detail_hr_rule = "//h1/img[@class='hitandrun']/@title"
alive = true
page_pieces_hash_api = "api/pieces-hash"
pieces_repeat = false
proxy = false

[level.User]
level_id = 1
level = "User"
days = 0
uploaded = "0"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 0.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "新用户的默认级别。"

[level.PowerUser]
level_id = 2
level = "PowerUser"
days = 4
uploaded = "0"
downloaded = "100GB"
bonus = 0.0
score = 20000
ratio = 2.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "可以在邀请区回复；可以查看NFO文档；可以查看用户列表；可以请求续种；可以查看排行榜。"

[level.EliteUser]
level_id = 3
level = "EliteUser"
days = 8
uploaded = "0"
downloaded = "350GB"
bonus = 0.0
score = 50000
ratio = 2.5
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "可以查看其它用户的种子历史(如果用户隐私等级未设置为'强')；可以删除自己上传的字幕。"

[level.CrazyUser]
level_id = 4
level = "CrazyUser"
days = 15
uploaded = "0"
downloaded = "500GB"
bonus = 0.0
score = 200000
ratio = 3.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "可以直接发布种子；可以发送邀请；可以在做种/下载/发布的时候选择匿名模式。"

[level.InsaneUser]
level_id = 5
level = "InsaneUser"
days = 25
uploaded = "0"
downloaded = "1TB"
bonus = 0.0
score = 400000
ratio = 3.5
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "得到两个邀请名额；可以查看普通日志。"

[level.VeteranUser]
level_id = 6
level = "VeteranUser"
days = 40
uploaded = "0"
downloaded = "2TB"
bonus = 0.0
score = 600000
ratio = 4.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "得到四个邀请名额；可以查看其它用户的评论、帖子历史。"

[level.ExtremeUser]
level_id = 7
level = "ExtremeUser"
days = 60
uploaded = "0"
downloaded = "4TB"
bonus = 0.0
score = 800000
ratio = 4.5
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "得到六个邀请名额；可以更新过期的外部信息；可以查看ExtremeUser论坛。ExtremeUserxa0用户封存后将永远保留账号。"

[level.UltimateUser]
level_id = 8
level = "UltimateUser"
days = 80
uploaded = "0"
downloaded = "6TB"
bonus = 0.0
score = 1000000
ratio = 5.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "得到八个邀请名额。"

[level.NexusMaster]
level_id = 9
level = "NexusMaster"
days = 100
uploaded = "0"
downloaded = "8TB"
bonus = 0.0
score = 1200000
ratio = 5.5
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "得到十个邀请名额。NexusMasterxa0用户会永远保留账号。"

[level.VIP]
level_id = 0
level = "VIP"
days = 0
uploaded = "0"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 0.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "和NexusMaster拥有相同权限并被认为是精英成员。免除自动降级。期间免除下载量，免除HR。"
