url = ["https://club.hares.top/", ]
name = "hares"
nickname = "白兔"
logo = "favicon.ico"
tracker = "club.hares.top"
sp_full = 170
limit_speed = 100
tags = "影视"
iyuu = 66
sign_in = true
get_info = true
repeat_torrents = true
brush_free = true
brush_rss = true
hr_discern = false
search_torrents = true
page_index = "index.php"
page_torrents = "torrents.php"
page_sign_in = "api/general?loading=false"
page_control_panel = "usercp.php"
page_detail = "view.php?id={}"
page_download = "download.php?id={}&passkey={}"
page_user = "user.php?id={}"
page_search = "torrents.php?search={}"
page_message = "messages.php"
page_hr = "myhr.php?hrtype=1&userid={}"
page_leeching = "getusertorrentlistajax.php?uid={}&type=leeching"
page_uploaded = "getusertorrentlistajax.php?uid={}&type=uploaded"
page_seeding = "user.php?id={}&action=seeding"
page_completed = "getusertorrentlistajax.php?uid={}&type=completed"
page_mybonus = "user.php?id={}&action=bonus"
page_viewfilelist = "viewfilelist.php?id={}"
sign_info_title = "//td[@id='outer']//td[@class='embedded']/h2/text()"
sign_info_content = "//td[@id='outer']//td[@class='embedded']/table//td//text()"
hr = false
hr_rate = 2
hr_time = 10
my_invitation_rule = "//div[contains(text(),'萝卜')]/following-sibling::div/text()[1]"
my_time_join_rule = "//span[contains(text(),'注册日期')]/text()"
my_latest_active_rule = "//span[contains(text(),'最近登录')]/text()"
my_uploaded_rule = "//div[text()='上传量']/following-sibling::div/text()[1]"
my_downloaded_rule = "//div[text()='下载量']/following-sibling::div/text()[1]"
my_ratio_rule = "//span[contains(text(),'分享率')][1]/em/text()"
my_bonus_rule = "//div[contains(text(),'奶糖余额')]/following-sibling::div/text()[1]"
my_per_hour_bonus_rule = "//p[contains(text(),'每小时获取奶糖')]/../b/text()"
my_score_rule = "//span[contains(text(),'做种积分')]/text()"
my_level_rule = "//div[@class='layui-hares-head-menu-info-username']/span[last()]/text()"
my_passkey_rule = "//input[@type='password']/@value"
my_uid_rule = "//div[@class='layui-hares-head-menu-info-username']/span/a[contains(@href,'user.php')]/@href"
my_hr_rule = "//a[@href='myhr.php']/text()"
my_leech_rule = "//div[contains(text(),'下载中')]/following-sibling::div/text()[1]"
my_publish_rule = "//p/preceding-sibling::b/text()[1]"
my_seed_rule = "//div[contains(text(),'做种中')]/following-sibling::div/text()[1]"
my_seed_vol_rule = "//a/cite[contains(text(),'做种总大小')]/text()"
my_mailbox_rule = "//a[@href='messages.php']//text()"
my_message_title = "//i[@class='fas fa-envelope-square layui-font-red fa-3x']/parent::td/following-sibling::td/a[1]//text()"
my_notice_rule = "//a[@href='index.php']/font[contains(text(),'条')]/text()[1]"
my_notice_title = "//div[@class='home_Announcement']/span[1]"
my_notice_content = "//div[@class='home_Announcement']/span/following-sibling::div/div"
torrents_rule = "//table//tr[not(@class)]"
torrent_title_rule = "./td/div/div/span/a/text()"
torrent_subtitle_rule = "./td/div[3]/div[last()-1]/text()"
torrent_detail_url_rule = "./td/div/div/span/a/@href"
torrent_category_rule = "./td/div[1]/a//img/@alt"
torrent_poster_rule = "./td/div[2]/img/@src"
torrent_magnet_url_rule = ".//div/a[contains(@href,'download.php')]/i/../@href"
torrent_size_rule = "./td/div[5]/text()"
torrent_progress_rule = ".//div[contains(@title,'ing')]/@title"
torrent_hr_rule = ".//table/tr/td/img[@class='hitandrun']/@title"
torrent_sale_rule = ".//img[contains(@class,'pro_')]/@alt"
torrent_sale_expire_rule = ".//td//em/span/@title"
torrent_release_rule = "./td/div[4]/text()"
torrent_seeders_rule = "./td/div[6]//text()[1]"
torrent_leechers_rule = "./td/div[7]//text()[1]"
torrent_completers_rule = "./td/div[8]//text()[1]"
detail_title_rule = "//td[contains(text(),'种子名称')]/following-sibling::td/text()[1]"
detail_subtitle_rule = "//td[contains(text(),'种子标题')]/following-sibling::td/text()[1]"
detail_download_url_rule = "//button[contains(text(),'种子链接')]/@data-link"
detail_size_rule = "//span[contains(@title,'种子大小')]/text()"
detail_category_rule = "//span[contains(@title,'分类')]/text()"
detail_count_files_rule = "//td/b[contains(text(),'文件数')]/following-sibling::text()[1]"
detail_hash_rule = "//td/b[contains(text(),'Hash')]/following-sibling::text()[1]"
detail_free_rule = "//td/em[contains(@class,'free-color')]/text()"
detail_free_expire_rule = "//h1/b/span/@title"
detail_douban_rule = "//td/a[starts-with(@href,'https://movie.douban.com/subject/')][1]"
detail_imdb_rule = "//a[@class='faqlink' and starts-with(@href,'https://www.imdb.com/title/')]/@href"
detail_poster_rule = "//td/a/span[contains(text(),'简介')]/../../following-sibling::td//img[1]/@src"
detail_tags_rule = "//td[contains(text(),'种子标签')]/following-sibling::td/span/@title"
torrent_tags_rule = "./td/div[3]/div[last()]/span/@title"
detail_hr_rule = "//h1/img[@class='hitandrun']/@title"
alive = true
page_pieces_hash_api = "api/pieces-hash"
pieces_repeat = false
proxy = false

[level.User]
level_id = 1
level = "User"
days = 0
uploaded = "0"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 0.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "新用户的默认级别。"

[level.PowerUser]
level_id = 2
level = "PowerUser"
days = 4
uploaded = "0"
downloaded = "100GB"
bonus = 0.0
score = 20000
ratio = 2.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "可以在邀请区回复；可以查看NFO文档；可以查看用户列表；可以请求续种；可以查看排行榜。"

[level.EliteUser]
level_id = 3
level = "EliteUser"
days = 8
uploaded = "0"
downloaded = "350GB"
bonus = 0.0
score = 50000
ratio = 2.5
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "可以查看其它用户的种子历史(如果用户隐私等级未设置为'强')；可以删除自己上传的字幕。"

[level.CrazyUser]
level_id = 4
level = "CrazyUser"
days = 15
uploaded = "0"
downloaded = "500GB"
bonus = 0.0
score = 200000
ratio = 3.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "可以直接发布种子；可以发送邀请；可以在做种/下载/发布的时候选择匿名模式。"

[level.InsaneUser]
level_id = 5
level = "InsaneUser"
days = 25
uploaded = "0"
downloaded = "1TB"
bonus = 0.0
score = 400000
ratio = 3.5
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "得到两个邀请名额；可以查看普通日志。"

[level.VeteranUser]
level_id = 6
level = "VeteranUser"
days = 40
uploaded = "0"
downloaded = "2TB"
bonus = 0.0
score = 600000
ratio = 4.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "得到四个邀请名额；可以查看其它用户的评论、帖子历史。"

[level.ExtremeUser]
level_id = 7
level = "ExtremeUser"
days = 60
uploaded = "0"
downloaded = "4TB"
bonus = 0.0
score = 800000
ratio = 4.5
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "得到六个邀请名额；可以更新过期的外部信息；可以查看ExtremeUser论坛。ExtremeUserxa0用户封存后将永远保留账号。"

[level.UltimateUser]
level_id = 8
level = "UltimateUser"
days = 80
uploaded = "0"
downloaded = "6TB"
bonus = 0.0
score = 1000000
ratio = 5.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "得到八个邀请名额。"

[level.NexusMaster]
level_id = 9
level = "NexusMaster"
days = 100
uploaded = "0"
downloaded = "8TB"
bonus = 0.0
score = 1200000
ratio = 5.5
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "得到十个邀请名额。NexusMasterxa0用户会永远保留账号。"

[level.VIP]
level_id = 0
level = "VIP"
days = 0
uploaded = "0"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 0.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "和NexusMaster拥有相同权限并被认为是精英成员。免除自动降级。期间免除下载量，免除HR。"
