url = [ "https://hdcity.city/", "https://hdcity.leniter.org/", "https://hdcity.work/",]
name = "hdcity"
nickname = "HD城市"
logo = "favicon.ico"
tracker = "sync.leniter.org|hdcity4.leniter.org|connected.hdcity.city"
sp_full = 140
limit_speed = 100
tags = "影视,720P,综合"
iyuu = 17
sign_in = true
get_info = true
repeat_torrents = true
brush_free = true
brush_rss = true
hr_discern = false
search_torrents = true
page_index = "index.php"
page_torrents = "pt"
page_sign_in = "sign"
page_control_panel = "userdetails"
page_detail = "details.php?id={}"
page_download = "download?id={}&cuhash={}"
page_user = "userdetails?id={}"
page_search = [ "pt?incldead=1&spstate=0&inclbookmarked=0&iwannaseethis={}",]
page_message = "messages.php"
page_hr = "myhr.php?hrtype=1&userid={}"
page_leeching = "getusertorrentlistajax.php?userid={}&type=leeching"
page_uploaded = "getusertorrentlistajax.php?userid={}&type=uploaded"
page_seeding = "getusertorrentlistajax.php?userid={}&type=seeding"
page_completed = "getusertorrentlistajax.php?userid={}&type=completed"
page_mybonus = "mybonus"
page_viewfilelist = "viewfilelist.php?id={}"
sign_info_title = "//h1/text()"
sign_info_content = "//h1/following-sibling::p/text()"
hr = false
hr_rate = 2
hr_time = 10
my_invitation_rule = "//a[@href='invite']/text()[1]"
my_time_join_rule = "//b[contains(text(), '加入日期')]/following-sibling::text()[1]"
my_latest_active_rule = "//b[text()='最近动向']/following-sibling::text()[1]"
my_uploaded_rule = "//a[@href='userdetails']/i[@title='上传量：']/following-sibling::text()[1]"
my_downloaded_rule = "//a[@href='userdetails']/i[@title='下载量：']/following-sibling::text()[1]"
my_ratio_rule = "//a[@href='userdetails']/i[@title='分享率：']/following-sibling::text()[1]"
my_bonus_rule = "//a[@href='mybonus']/text()[1]"
my_per_hour_bonus_rule = "//div[contains(text(),'每小时能获取')]/text()[1]"
my_score_rule = "//tr[115]/td[2]/text()"
my_level_rule = "//div[@id='bottomnav']/div/a/strong/following-sibling::text()[1]"
my_passkey_rule = "//span[@id='kpkey']/em/text()"
my_uid_rule = "//div[@class='text']/b[contains(.,'ID')]/../text()"
my_hr_rule = "//a[@href='myhr.php']/text()"
my_leech_rule = "//a[@href='userdetails']/span[@title='当前下载']/text()[1]"
my_publish_rule = "//div[contains(., '条记录')]/b[1]/text()"
my_seed_rule = "//a[@href='userdetails']/span[@title='当前做种']/text()[1]"
my_seed_vol_rule = "//tr/td[3]"
my_mailbox_rule = "//li/a/i[@id='rmsg']/following::text()[1]"
my_message_title = "//img[@alt='Unread']/parent::td/following-sibling::td/a[1]//text()"
my_notice_rule = "//a[@href='index.php']/font[contains(text(),'条')]/text()[1]"
my_notice_title = "//div[@class='block'][1]/div[@class='blocktitle']/a"
my_notice_content = "//div[@class='block'][1]/div[@class='blocktitle']/following-sibling::div"
torrents_rule = "//center/div/div/div[contains(@class,'mitem')]"
torrent_title_rule = "./div[@class='trm']/div/div[@class='trbi']/a/span/text()"
torrent_subtitle_rule = ".//a[contains(@href,'detail')]/parent::td/text()[last()]"
torrent_detail_url_rule = "./div[@class='mtop']/div[1]/a/@href"
torrent_category_rule = "./div/div[@class='trti']/a/span/text()"
torrent_poster_rule = "./div[@class='trm']/div/div/img/@src"
torrent_magnet_url_rule = ".//a[contains(@href,'download?id=')]/@href"
torrent_size_rule = ".//div[@class='trl']/i/following-sibling::text()[1]"
torrent_progress_rule = ".//div[contains(@title,'ing')]/@title"
torrent_hr_rule = ".//table/tr/td/img[@class='hitandrun']/@title"
torrent_sale_rule = ".//img[contains(@class,'pro_')]/@alt"
torrent_sale_expire_rule = ".//img[contains(@class,'free')]/following-sibling::font/span/@title"
torrent_release_rule = ".//div[@class='trtop']/div/text()"
torrent_seeders_rule = ".//a[contains(@href,'dllist=1#seeders')]/font/text()"
torrent_leechers_rule = ".//a[contains(@href,'dllist=1#leechers')]/text()"
torrent_completers_rule = ".//a[contains(@href,'viewsnatches?id=')]/text()"
detail_title_rule = "//h1/text()[1]"
detail_subtitle_rule = "//td[contains(text(),'副标题')]/following-sibling::td/text()[1]"
detail_download_url_rule = "//input[@title='DirectLink']/preceding-sibling::a[1]/@href"
detail_size_rule = "//td//b[contains(text(),'大小')]/following::text()[1]"
detail_category_rule = "//td/b[contains(text(),'类型')]/following-sibling::text()[1]"
detail_count_files_rule = "//td/b[contains(text(),'文件数')]/following-sibling::text()[1]"
detail_hash_rule = "//td/b[contains(text(),'Hash')]/following-sibling::text()[1]"
detail_free_rule = "//h1/b/font/@class"
detail_free_expire_rule = "//h1/b/span/@title"
detail_douban_rule = "//td/a[starts-with(@href,'https://movie.douban.com/subject/')][1]"
detail_imdb_rule = "//a[@class='faqlink' and starts-with(@href,'https://www.imdb.com/title/')]/@href"
detail_poster_rule = "//td/a/span[contains(text(),'简介')]/../../following-sibling::td//img[1]/@src"
detail_tags_rule = "//td[contains(text(),'标签')]/following-sibling::td//text()"
torrent_tags_rule = ".//a[contains(@href,'detail')]/../span[contains(@class,'tags')]/text()"
detail_hr_rule = "//h1/img[@class='hitandrun']/@title"
alive = true
page_pieces_hash_api = "api/pieces-hash"
pieces_repeat = false
proxy = true
imdb_search = "pt?incldead=1&spstate=0&inclbookmarked=0&iwannaseethis={}&search_area=4&search_mode=0"
structure = "HDCity"
type = "pt"
nation = "china"
my_email_rule = "//b[contains(text(),'邮箱')]/following-sibling::a//text()"
my_username_rule = "//div[@id='bottomnav']/div/a/strong/text()"
buy_page = "mybonus.php?action=exchange"

[buy_action]
"100GB上传流量" = "3"
"100GB下载流量" = "5"
"1个邀请名额" = "6"
"1个临时邀请名额" = "7"
"贵宾待遇" = "9"

[level.Peasant]
level_id = -1
level = "Peasant"
name = "堕落者"
days = 0
uploaded = "0"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 0.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "被降级的、分享率低于 1 的市民，以及新上户口的市民，有 30 天时间来提升分享率，如不满足要求会被禁用。"

[level.Newbie]
level_id = 0
level = "Newbie"
name = "天使"
days = 0
uploaded = "0"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 0.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = true
graduation = true
rights = "新手上路。可以直接发布种子；可以使用 RSS。"

[level.PowerAngel]
level_id = 0
level = "PowerAngel"
name = "大天使"
days = 0
uploaded = "0"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 0.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = true
graduation = true
rights = "可以请求续种； 可以查看其它用户的种子历史(如果用户隐私等级未设置为\"强\")。"

[level.EliteAngel]
level_id = 0
level = "EliteAngel"
name = "权天使"
days = 0
uploaded = "0"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 0.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = true
graduation = true
rights = "权天使 及以上等级封存账号后不会被删除。"

[level.CrazyAngel]
level_id = 0
level = "CrazyAngel"
name = "能天使"
days = 0
uploaded = "0"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 0.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = true
graduation = true
rights = "可以在做种/下载/发布的时候选择匿名模式。"

[level.InsaneAngel]
level_id = 0
level = "InsaneAngel"
name = "力天使"
days = 0
uploaded = "0"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 0.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = true
graduation = true
rights = "可以查看普通日志。"

[level.VeteranAngel]
level_id = 0
level = "VeteranAngel"
name = "主天使"
days = 0
uploaded = "0"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 0.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = true
graduation = true
rights = "主天使 及以上市民会永远保留账号。"

[level.ExtremeAngel]
level_id = 0
level = "ExtremeAngel"
name = "座天使"
days = 0
uploaded = "0"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 0.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = true
graduation = true
rights = ""

[level.UltimateAngel]
level_id = 0
level = "UltimateAngel"
name = "智天使"
days = 0
uploaded = "0"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 0.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = true
graduation = true
rights = "比较牛逼的等级。"

[level.MasterAngel]
level_id = 0
level = "MasterAngel"
name = "炽天使"
days = 0
uploaded = "0"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 0.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = true
graduation = true
rights = "最牛逼的市民，或特殊任务分配。"

[level.VIP]
level_id = 0
level = "VIP"
name = "壕"
days = 0
uploaded = "0"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 0.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = true
graduation = true
rights = "管理员分配，捐助的市民，或自行以魅力值兑换获得。免除自动降级无视分享率。"

[level.Retiree]
level_id = 0
level = "Retiree"
name = "隐天使"
days = 0
uploaded = "0"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 0.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = true
graduation = true
rights = "退休后的管理组成员。"

[level.Uploader]
level_id = 0
level = "Uploader"
name = "射种天使"
days = 0
uploaded = "0"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 0.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = true
graduation = true
rights = "专注的发布者。工作组。可以查看匿名。"

[level.ForumModerator]
level_id = 0
level = "ForumModerator"
name = "论坛版主"
days = 0
uploaded = "0"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 0.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = true
graduation = true
rights = "论坛管理者。可以制定在任版块的版规、管理主题和帖子。"

[level.Moderator]
level_id = 0
level = "Moderator"
name = "总版主"
days = 0
uploaded = "0"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 0.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = true
graduation = true
rights = "可以查看管理组信箱、举报信箱；管理趣味盒内容、投票内容；可以编辑或删除任何发布的种子及字幕；可以管理候选；可以管理论坛帖子、用户评论；可以查看机密日志；可以管理日志中的代码、史册；可以查看用户的邀请记录；可以管理用户帐号的一般信息；可以将种子设为置顶或促销；可以查看用户IP或Email等机密信息。不能管理友情链接、最近消息；不能删除账号。"

[level.Administrator]
level_id = 0
level = "Administrator"
name = "管理员"
days = 0
uploaded = "0"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 0.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = true
graduation = true
rights = "各种日常管理，可以做任何修改。"

[level.Sysop]
level_id = 0
level = "Sysop"
name = "守护天使"
days = 0
uploaded = "0"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 0.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = true
graduation = true
rights = "网站开发/维护人员，可以做任何修改。"

[level.Mayor]
level_id = 0
level = "Mayor"
name = "市长"
days = 0
uploaded = "0"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 0.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = true
rights = "灵魂。"

[level."天使"]
level_id = 0
level = "\"天使\""
name = "\"天使\""
days = 0
uploaded = "0"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 0.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = true
rights = ""

[level."大天使"]
level_id = 0
level = "\"大天使\""
name = "\"大天使\""
days = 0
uploaded = "0"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 0.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = true
rights = ""

[level."权天使"]
level_id = 0
level = "\"权天使\""
name = "\"权天使\""
days = 0
uploaded = "0"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 0.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = true
rights = ""

[level."能天使"]
level_id = 0
level = "\"能天使\""
name = "\"能天使\""
days = 0
uploaded = "0"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 0.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = true
rights = ""

[level."力天使"]
level_id = 0
level = "\"力天使\""
name = "\"力天使\""
days = 0
uploaded = "0"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 0.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = true
rights = ""

[level."主天使"]
level_id = 0
level = "\"主天使\""
name = "\"主天使\""
days = 0
uploaded = "0"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 0.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = true
rights = ""

[level."座天使"]
level_id = 0
level = "\"座天使\""
name = "\"座天使\""
days = 0
uploaded = "0"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 0.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = true
rights = ""

[level."智天使"]
level_id = 0
level = "\"智天使\""
name = "\"智天使\""
days = 0
uploaded = "0"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 0.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = true
rights = ""

[level."炽天使"]
level_id = 0
level = "\"炽天使\""
name = "\"炽天使\""
days = 0
uploaded = "0"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 0.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = true
rights = ""

[level."壕"]
level_id = 0
level = "\"壕\""
name = "\"壕\""
days = 0
uploaded = "0"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 0.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = true
rights = ""
