url = [ "https://hdcity.city/",]
name = "hdcity"
nickname = "HD城市"
logo = "favicon.ico"
tracker = "sync.leniter.org"
sp_full = 140
limit_speed = 100
tags = "影视"
iyuu = 17
sign_in = true
get_info = true
repeat_torrents = true
brush_free = true
brush_rss = true
hr_discern = false
search_torrents = true
page_index = "index.php"
page_torrents = "torrents.php?incldead=1"
page_sign_in = "sign"
page_control_panel = "usercp.php"
page_detail = "details.php?id={}"
page_download = "download?id={}&cuhash={}"
page_user = "userdetails?id={}"
page_search = "pt?incldead=1&spstate=0&inclbookmarked=0&iwannaseethis={}"
page_message = "messages.php"
page_hr = "myhr.php?hrtype=1&userid={}"
page_leeching = "getusertorrentlistajax.php?userid={}&type=leeching"
page_uploaded = "getusertorrentlistajax.php?userid={}&type=uploaded"
page_seeding = "getusertorrentlistajax.php?userid={}&type=seeding"
page_completed = "getusertorrentlistajax.php?userid={}&type=completed"
page_mybonus = "mybonus"
page_viewfilelist = "viewfilelist.php?id={}"
sign_info_title = "//h1/text()"
sign_info_content = "//h1/following-sibling::p/text()"
hr = false
hr_rate = 2
hr_time = 10
my_invitation_rule = "//a[@href=\"invite\"]/text()[1]"
my_time_join_rule = "//b[contains(text(), \"加入日期\")]/following-sibling::text()[1]"
my_latest_active_rule = "//b[text()=\"最近动向\"]/following-sibling::text()[1]"
my_uploaded_rule = "//a[@href=\"userdetails\"]/i[@title=\"上传量：\"]/following-sibling::text()[1]"
my_downloaded_rule = "//a[@href=\"userdetails\"]/i[@title=\"下载量：\"]/following-sibling::text()[1]"
my_ratio_rule = "//a[@href=\"userdetails\"]/i[@title=\"分享率：\"]/following-sibling::text()[1]"
my_bonus_rule = "//a[@href=\"mybonus\"]/text()[1]"
my_per_hour_bonus_rule = "//div[contains(text(),\"每小时能获取\")]/text()[1]"
my_score_rule = "//tr[115]/td[2]/text()"
my_level_rule = "//div[@id=\"bottomnav\"]/div/a/strong/following-sibling::text()[1]"
my_passkey_rule = "//span[@id=\"kpkey\"]/em/text()"
my_uid_rule = "//b[text()=\"ID\"]/following-sibling::text()[1]"
my_hr_rule = "//a[@href=\"myhr.php\"]/text()"
my_leech_rule = "//a[@href=\"userdetails\"]/span[@title=\"当前下载\"]/text()[1]"
my_publish_rule = "//p/preceding-sibling::b/text()[1]"
my_seed_rule = "//a[@href=\"userdetails\"]/span[@title=\"当前做种\"]/text()[1]"
my_seed_vol_rule = "//tr/td[3]"
my_mailbox_rule = "//li/a/i[@id=\"rmsg\"]/following::text()[1]"
my_message_title = "//img[@alt=\"Unread\"]/parent::td/following-sibling::td/a[1]//text()"
my_notice_rule = "//a[@href=\"index.php\"]/font[contains(text(),\"条\")]/text()[1]"
my_notice_title = "//div[@class=\"block\"][1]/div[@class=\"blocktitle\"]/a"
my_notice_content = "//div[@class=\"block\"][1]/div[@class=\"blocktitle\"]/following-sibling::div"
torrents_rule = "//center/div/div/div[contains(@class,\"trblock\")]"
torrent_title_rule = "./div[@class=\"trm\"]/div/div[@class=\"trbi\"]/a/span/text()"
torrent_subtitle_rule = ".//a[contains(@href,\"detail\")]/parent::td/text()[last()]"
torrent_detail_url_rule = "./div[@class=\"trtop\"]/a/@href"
torrent_category_rule = "./div/div[@class=\"trti\"]/a/span/text()"
torrent_poster_rule = "./div[@class=\"trm\"]/div/div/img/@src"
torrent_magnet_url_rule = ".//a[contains(@href,\"download?id=\")]/@href"
torrent_size_rule = ".//div[@class=\"trl\"]/i/following-sibling::text()[1]"
torrent_hr_rule = ".//table/tr/td/img[@class=\"hitandrun\"]/@title"
torrent_sale_rule = ".//img[contains(@class,\"pro_\")]/@alt"
torrent_sale_expire_rule = ".//img[contains(@class,\"free\")]/following-sibling::font/span/@title"
torrent_release_rule = ".//div[@class=\"trtop\"]/div/text()"
torrent_seeders_rule = ".//a[contains(@href,\"dllist=1#seeders\")]/font/text()"
torrent_leechers_rule = ".//a[contains(@href,\"dllist=1#leechers\")]/text()"
torrent_completers_rule = ".//a[contains(@href,\"viewsnatches?id=\")]/text()"
detail_title_rule = "//h1/text()[1]"
detail_subtitle_rule = "//td[contains(text(),\"副标题\")]/following-sibling::td/text()[1]"
detail_download_url_rule = "//a[@class=\"index\" and contains(@href,\"download.php\")]/@href"
detail_size_rule = "//td//b[contains(text(),\"大小\")]/following::text()[1]"
detail_category_rule = "//td/b[contains(text(),\"类型\")]/following-sibling::text()[1]"
detail_count_files_rule = "//td/b[contains(text(),\"文件数\")]/following-sibling::text()[1]"
detail_hash_rule = "//td/b[contains(text(),\"Hash\")]/following-sibling::text()[1]"
detail_free_rule = "//h1/b/font/@class"
detail_free_expire_rule = "//h1/b/span/@title"
detail_douban_rule = "//td/a[starts-with(@href,\"https://movie.douban.com/subject/\")][1]"
detail_imdb_rule = "//a[@class=\"faqlink\" and starts-with(@href,\"https://www.imdb.com/title/\")]/@href"
detail_poster_rule = "//td/a/span[contains(text(),\"简介\")]/../../following-sibling::td//img[1]/@src"
detail_tags_rule = "//td[contains(text(),\"标签\")]/following-sibling::td//text()"
torrent_tags_rule = ".//a[contains(@href,\"detail\")]/../span[contains(@class,\"tags\")]/text()"
detail_hr_rule = "//h1/img[@class=\"hitandrun\"]/@title"
alive = true
page_pieces_hash_api = "api/pieces-hash"
pieces_repeat = false
proxy = true

[level."天使"]
level_id = 1
level = "天使"
days = 0
uploaded = "0"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 0.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "新手上路。可以直接发布种子；可以使用RSS。"

[level."大天使"]
level_id = 2
level = "大天使"
days = 4
uploaded = "50GB"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 1.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "可以请求续种；可以查看其它用户的种子历史(如果用户隐私等级未设置为\"强\")。"

[level."权天使"]
level_id = 3
level = "权天使"
days = 8
uploaded = "150GB"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 1.1
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "权天使(EliteUser)及以上等级封存账号后不会被删除。"

[level."能天使"]
level_id = 4
level = "能天使"
days = 12
uploaded = "500GB"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 1.5
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "可以在做种/下载/发布的时候选择匿名模式。"

[level."力天使"]
level_id = 5
level = "力天使"
days = 16
uploaded = "1TB"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 2.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "可以查看普通日志。"

[level."主天使"]
level_id = 6
level = "主天使"
days = 24
uploaded = "5TB"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 2.5
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "主天使(VeteranUser)及以上市民会永远保留账号。"

[level."座天使"]
level_id = 7
level = "座天使"
days = 36
uploaded = "10TB"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 2.6
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "无"

[level."智天使"]
level_id = 8
level = "智天使"
days = 72
uploaded = "20TB"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 2.8
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "比较牛逼的等级。"

[level."炽天使"]
level_id = 9
level = "炽天使"
days = 100
uploaded = "40TB"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 4.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "最牛逼的市民，或特殊任务分配。"

[level."壕"]
level_id = 0
level = "壕"
days = 0
uploaded = "0"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 0.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "管理员分配，捐助的市民，或自行以魅力值兑换获得。免除自动降级无视分享率。"
