url = [ "https://hd-space.org/",]
name = "HDSpace"
nickname = "HDSpace"
logo = "favicon.ico"
tracker = "hd-space.pw|"
sp_full = 100
limit_speed = 100
tags = "影视"
iyuu = 50
sign_in = false
get_info = true
repeat_torrents = false
brush_free = false
brush_rss = false
hr_discern = false
search_torrents = true
page_index = "index.php"
page_torrents = "torrents.php?incldead=1"
page_sign_in = "attendance.php"
page_control_panel = "index.php?page=usercp&do=pid_c&action=change&uid={}"
page_detail = "details.php?id={}"
page_download = "download.php?id={}&passkey={}"
page_user = "index.php?page=usercp&uid={}"
page_search = "index.php?page=torrents&search={}"
page_message = "messages.php"
page_hr = "myhr.php?hrtype=1&userid={}"
page_leeching = "getusertorrentlistajax.php?userid={}&type=leeching"
page_uploaded = "getusertorrentlistajax.php?userid={}&type=uploaded"
page_seeding = "index.php?page=usercp&uid={}"
page_completed = "getusertorrentlistajax.php?userid={}&type=completed"
page_mybonus = "index.php?page=modules&module=seedbonus"
page_viewfilelist = "viewfilelist.php?id={}"
sign_info_title = "//td[@id='outer']//td[@class='embedded']/h2/text()"
sign_info_content = "//td[@id='outer']//td[@class='embedded']/table//td//text()"
hr = false
hr_rate = 2
hr_time = 10
my_invitation_rule = "//tr/td[contains(text(), 'Invites')]/a/text()"
my_time_join_rule = "//td[contains(text(),'Joined on')]/following-sibling::td/text()"
my_latest_active_rule = "//font[@color='steelblue']/text()"
my_uploaded_rule = "//td[contains(text(),'UP')][1]/text()"
my_downloaded_rule = "//td[contains(text(),'DL')][1]/text()"
my_ratio_rule = "//td[contains(text(),'Ratio: ')][1]/text()"
my_bonus_rule = "//td/a[contains(text(),'Bonus: ')][1]/text()"
my_per_hour_bonus_rule = "//h3/text()"
my_score_rule = "//font[@class='color_bonus' and contains(text(),'积分')]/following-sibling::text()[1]"
my_level_rule = "//td[text()='Rank']/following-sibling::td/text()"
my_passkey_rule = "//td[contains(text(), 'PID')]/following-sibling::td/text()"
my_uid_rule = "//td/a[contains(@href,'index.php?page=usercp&uid=') and contains(text(),'My Panel')][1]/@href"
my_hr_rule = "//tr/td[text()='Total Warns'][1]/following-sibling::td[1]/text()"
my_leech_rule = "//span[@title='Leech']//text()"
my_publish_rule = "//div[contains(., '条记录')]/b[1]/text()"
my_seed_rule = "//span[@title='Seed']//text()"
my_seed_vol_rule = "//tr/td[text()='Total Size of torrents'][1]/following-sibling::td[1]/text()"
my_mailbox_rule = "//div[contains(@class,'new-pm')]/h4/text()"
my_message_title = "//img[@alt='Unread']/parent::td/following-sibling::td/a[1]//text()"
my_notice_rule = "//a[@href='index.php']/font[contains(text(),'条')]/text()[1]"
my_notice_title = "//td[@class='text']/div/a"
my_notice_content = "//td[@class='text']/div/a/following-sibling::div"
torrents_rule = "//table[@class='torrents']/tr"
torrent_title_rule = ".//td/a[contains(@href,'detail')]/b/text()[last()]"
torrent_subtitle_rule = ".//a[contains(@href,'detail')]/parent::td/text()[last()]"
torrent_detail_url_rule = ".//td[@class='embedded']/a[contains(@href,'detail')]/@href"
torrent_category_rule = ".//td[@class='rowfollow nowrap'][1]/a[1]/img/@title"
torrent_poster_rule = ".//table/tr/td[1]/img/@src"
torrent_magnet_url_rule = ".//td/a[contains(@href,'download.php?id=')]/@href"
torrent_size_rule = ".//td[5]/text()"
torrent_progress_rule = ".//div[contains(@title,'ing')]/@title"
torrent_hr_rule = ".//table/tr/td/img[@class='hitandrun']/@title"
torrent_sale_rule = ".//img[contains(@class,'pro_')]/@alt"
torrent_sale_expire_rule = ".//img[contains(@class,'free')]/following-sibling::font/span/@title"
torrent_release_rule = ".//td[4]/span/@title"
torrent_seeders_rule = ".//a[contains(@href,'#seeders')]/text()"
torrent_leechers_rule = ".//a[contains(@href,'#leechers')]/text()"
torrent_completers_rule = ".//a[contains(@href,'viewsnatches')]//text()"
detail_title_rule = "//h1/text()[1]"
detail_subtitle_rule = "//td[contains(text(),'副标题')]/following-sibling::td/text()[1]"
detail_download_url_rule = "//a[@class='index' and contains(@href,'download.php')]/@href"
detail_size_rule = "//td//b[contains(text(),'大小')]/following::text()[1]"
detail_category_rule = "//td/b[contains(text(),'类型')]/following-sibling::text()[1]"
detail_count_files_rule = "//td/b[contains(text(),'文件数')]/following-sibling::text()[1]"
detail_hash_rule = "//td/b[contains(text(),'Hash')]/following-sibling::text()[1]"
detail_free_rule = "//h1/b/font/@class"
detail_free_expire_rule = "//h1/b/span/@title"
detail_douban_rule = "//td/a[starts-with(@href,'https://movie.douban.com/subject/')][1]"
detail_imdb_rule = "//a[@class='faqlink' and starts-with(@href,'https://www.imdb.com/title/')]/@href"
detail_poster_rule = "//td/a/span[contains(text(),'简介')]/../../following-sibling::td//img[1]/@src"
detail_tags_rule = "//td[contains(text(),'标签')]/following-sibling::td//text()"
torrent_tags_rule = ".//a[contains(@href,'detail')]/../span[contains(@class,'tags')]/text()"
detail_hr_rule = "//h1/img[@class='hitandrun']/@title"
alive = true
page_pieces_hash_api = "api/pieces-hash"
pieces_repeat = false
proxy = true
structure = "HDSpace"
type = "pt"
nation = "foreign"
my_email_rule = "//input[@name='email']/@value"
my_username_rule = "//td/table//tr/td/a/../span/text()"
buy_page = "mybonus.php?action=exchange"

[buy_action]
"100GB上传流量" = "3"
"100GB下载流量" = "5"
"1个邀请名额" = "6"
"1个临时邀请名额" = "7"
"贵宾待遇" = "9"
