url = ["https://jpopsuki.eu/", ]
name = "JPOP"
nickname = "JPOP"
logo = "favicon.ico"
tracker = "jpopsuki.eu"
sp_full = 107
limit_speed = 100
tags = "外站,音乐"
iyuu = 0
sign_in = false
get_info = true
repeat_torrents = false
brush_free = false
brush_rss = false
hr_discern = false
search_torrents = false
page_index = "index.php"
page_torrents = "torrents.php"
page_sign_in = "attendance.php"
page_control_panel = "user.php?id={}"
page_detail = "details.php?id={}"
page_download = "download.php?id={}&passkey={}"
page_user = "user.php?id={}"
page_search = "torrents.php?searchstr={}"
page_message = "inbox.php"
page_hr = "myhr.php?hrtype=1&userid={}"
page_leeching = "getusertorrentlistajax.php?userid={}&type=leeching"
page_uploaded = "torrents.php?type=uploaded&userid={}"
page_seeding = "torrents.php?type=seeding&userid={}"
page_completed = "getusertorrentlistajax.php?userid={}&type=completed"
page_mybonus = "bonus.php"
page_viewfilelist = "viewfilelist.php?id={}"
sign_info_title = "//td[@id='outer']//td[@class='embedded']/h2/text()"
sign_info_content = "//td[@id='outer']//td[@class='embedded']/table//td//text()"
hr = false
hr_rate = 2
hr_time = 10
my_invitation_rule = "//span/a[contains(@href,'invite.php?id=')]/following-sibling::text()[1]"
my_time_join_rule = "//div[contains(text(),'Stats')]/following-sibling::ul/li[1]/span/@title"
my_latest_active_rule = "//div[contains(text(),'Stats')]/following-sibling::ul/li[2]/span/@title"
my_uploaded_rule = "//ul[@id='userinfo_stats']/li[1]/span/text()"
my_downloaded_rule = "//ul[@id='userinfo_stats']/li[2]/span/text()"
my_ratio_rule = "//ul[@id='userinfo_stats']/li[3]/span/text()"
my_bonus_rule = "//ul[@id='userinfo_stats']/li[4]//a/span/text()"
my_per_hour_bonus_rule = "//*[@id='content']/div/div/strong[3]/text()"
my_score_rule = "//font[@class='color_bonus' and contains(text(),'积分')]/following-sibling::text()[1]"
my_level_rule = "//div[contains(text(),'Personal')]/following-sibling::ul/li[1]/text()"
my_passkey_rule = "//div[contains(text(),'Personal')]/following-sibling::ul/li[4]/text()"
my_uid_rule = "//ul[@id='userinfo_username']/li[1]/a/@href"
my_hr_rule = "//a[@href='myhr.php']//text()"
my_leech_rule = "//div[contains(text(),'Community')]/following-sibling::ul/li[7]/text()[1]"
my_publish_rule = "//div[contains(., '条记录')]/b[1]/text()"
my_seed_rule = "//div[contains(text(),'Community')]/following-sibling::ul/li[6]/text()[1]"
my_seed_vol_rule = "//tr[@class='torrent']/td[6]"
my_mailbox_rule = "//a[@href='messages.php']/font[contains(text(),'条')]/text()[1]"
my_message_title = "//img[@alt='Unread']/parent::td/following-sibling::td/a[1]//text()"
my_notice_rule = "//div/a[@href='notice.php']/text()[1]"
my_notice_title = "//div[@class='head']/strong//text()"
my_notice_content = "//div[@class='box vertical_space']/div[@class='pad']"
torrents_rule = "//table[@class='torrents']/tr"
torrent_title_rule = ".//td[@class='embedded']/a/b/text()"
torrent_subtitle_rule = ".//a[contains(@href,'detail')]/parent::td/text()[last()]"
torrent_detail_url_rule = ".//td[@class='embedded']/a[contains(@href,'detail')]/@href"
torrent_category_rule = ".//td[@class='rowfollow nowrap'][1]/a[1]/img/@title"
torrent_poster_rule = ".//table/tr/td[1]/img/@src"
torrent_magnet_url_rule = ".//td/a[contains(@href,'download.php?id=')]/@href"
torrent_size_rule = ".//td[5]/text()"
torrent_progress_rule = ".//div[contains(@title,'ing')]/@title"
torrent_hr_rule = ".//table/tr/td/img[@class='hitandrun']/@title"
torrent_sale_rule = ".//img[contains(@class,'free')]/@alt"
torrent_sale_expire_rule = ".//img[contains(@class,'free')]/following-sibling::font/span/@title"
torrent_release_rule = ".//td[4]/span/@title"
torrent_seeders_rule = ".//a[contains(@href,'#seeders')]/text()"
torrent_leechers_rule = ".//a[contains(@href,'#leechers')]/text()"
torrent_completers_rule = ".//a[contains(@href,'viewsnatches')]//text()"
detail_title_rule = "//h1/text()[1]"
detail_subtitle_rule = "//td[contains(text(),'副标题')]/following-sibling::td/text()[1]"
detail_download_url_rule = "//td[contains(text(),'种子链接')]/following-sibling::td/a/@href"
detail_size_rule = "//td//b[contains(text(),'大小')]/following::text()[1]"
detail_category_rule = "//td/b[contains(text(),'类型')]/following-sibling::text()[1]"
detail_count_files_rule = "//td/b[contains(text(),'文件数')]/following-sibling::text()[1]"
detail_hash_rule = "//td/b[contains(text(),'Hash')]/following-sibling::text()[1]"
detail_free_rule = "//h1/b/font/@class"
detail_free_expire_rule = "//h1/font/span/@title"
detail_douban_rule = "//td/a[starts-with(@href,'https://movie.douban.com/subject/')][1]"
detail_imdb_rule = "//a[@class='faqlink' and starts-with(@href,'https://www.imdb.com/title/')]/@href"
detail_poster_rule = "//td/a/span[contains(text(),'简介')]/parent::a/parent::td/following-sibling::td//img[1]"
detail_tags_rule = "//td[contains(text(),'标签')]/following-sibling::td//text()"
torrent_tags_rule = ".//a[contains(@href,'detail')]/../span[contains(@style,'background-color')]/text()"
detail_hr_rule = "//h1/img[@class='hitandrun']/@title"
alive = true
page_pieces_hash_api = "api/pieces-hash"
pieces_repeat = false
proxy = true
imdb_search = "torrents.php?search_area=4&search={}"
structure = "JPOP"
type = "pt"
nation = "foreign"
my_email_rule = "//li[contains(text(),'Email')]/a[1]//text()"
my_username_rule = "//ul[@id='userinfo_username']/li[1]/a/text()"
buy_page = "mybonus.php?action=exchange"

[buy_action]
"100GB上传流量" = "3"
"100GB下载流量" = "5"
"1个邀请名额" = "6"
"1个临时邀请名额" = "7"
"贵宾待遇" = "9"

[level.User]
level_id = 1
level = "User"
days = 0
uploaded = "0"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 0.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "新用户的默认级别。可以上传下载，不能发送邀请。"

[level.Member]
level_id = 2
level = "Member"
days = 1
uploaded = "10GB"
downloaded = "1KB"
bonus = 0.0
score = 0
ratio = 0.7
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "可以使用邀请、通知、设置论坛签名、访问前 10 名以及编辑知识库。"

[level.PowerUser]
level_id = 3
level = "PowerUser"
days = 2
uploaded = "25GB"
downloaded = "1KB"
bonus = 0.0
score = 100000
ratio = 1.05
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "与普通成员相同，加上高级前 10 名查看权限，可以查看种子抓取列表、删除标签、编辑种子描述、原始标题和发布日期，并访问高级用户搜索。每月获得一个新邀请（最多可获得 10 个可用邀请）。"

[level.Donor]
level_id = 4
level = "Donor"
days = 0
uploaded = "0"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 0.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "拥有与 PowerUser 相同的权限，并且可以免费提交请求、将种子添加到推荐列表中，并在邀请关闭时邀请用户。"

[level.VIP]
level_id = 0
level = "VIP"
days = 0
uploaded = "0"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 0.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "与 Donor 相同，并且可以发送无限邀请、将自己的种子设为免费下载并从种子中删除标签。"
