url = ["https://xp.m-team.cc/", "https://xp.m-team.io/", "https://zp.m-team.io/", "https://next.m-team.cc/", "https://kp.m-team.cc/", "https://kp.m-team.io/", ]
name = "MTeam"
nickname = "MTeam"
logo = "https://xp.m-team.cc/favicon.ico"
tracker = "tracker.m-team.cc|tracker.m-team.io|ipv6.tracker.m-team.cc|ipv4.tracker.m-team.cc|v6tracker.m-team.io|ipv6-tracker.m-team.cc"
sp_full = 0
limit_speed = 95
tags = "综合,影视,中文第一大站,官种"
iyuu = 3
sign_in = false
get_info = true
repeat_torrents = true
brush_free = true
brush_rss = true
hr_discern = false
search_torrents = true
page_index = "index"
page_torrents = "torrents.php?incldead=1"
page_sign_in = "attendance.php"
page_control_panel = "usercp?tab=laboratory"
page_detail = "api/torrent/detail"
page_download = "download.php?id={}&passkey={}"
page_user_api = "api/member/profile"
page_user = "profile/detail/{}"
page_search = "api/torrent/search"
page_notice = "api/news/list"
page_message = "api/msg/statistic"
page_hr = "myhr.php?hrtype=1&userid={}"
page_leeching = "api/member/getUserTorrentList"
page_uploaded = "api/member/getUserTorrentList"
page_seeding = "api/member/getUserTorrentList"
page_completed = "api/member/getUserTorrentList"
page_mybonus = "api/tracker/mybonus"
page_viewfilelist = "viewfilelist.php?id={}"
sign_info_title = "//td[@id='outer']//td[@class='embedded']/h2/text()"
sign_info_content = "//td[@id='outer']//td[@class='embedded']/table//td//text()"
hr = false
hr_rate = 2
hr_time = 10
my_invitation_rule = "//a[contains(@href,'invite.php?id=')]/following-sibling::text()[1]"
my_time_join_rule = "//td[contains(text(),'加入')]/following-sibling::td[1]//span/@title"
my_latest_active_rule = "//td[contains(text(),'最近')]/following-sibling::td[1]//span/@title"
my_uploaded_rule = "//font[@class='color_uploaded']/following-sibling::text()[1]"
my_downloaded_rule = "//font[@class='color_downloaded']/following-sibling::text()[1]"
my_ratio_rule = "//font[@class='color_ratio'][1]/following-sibling::text()[1]"
my_bonus_rule = "//a[@href='mybonus.php']/following-sibling::text()[1]"
my_per_hour_bonus_rule = "//td[contains(text(),'每小')]/text()[1]"
my_score_rule = "//font[@class='color_bonus' and contains(text(),'积分')]/following-sibling::text()[1]"
my_level_rule = "//span[@class='medium']/span[@class='nowrap'][1]/a[contains(@class,'_Name')]/@class"
my_passkey_rule = "//td[contains(text(),'密钥')]/following-sibling::td[1]/text()"
my_uid_rule = "//span/span/a[contains(@href,'/profile/detail/')]/@href"
my_hr_rule = "//a[@href='myhr.php']/text()"
my_leech_rule = "//img[@class='arrowdown'][1]/following-sibling::text()[1]"
my_publish_rule = "//div[contains(., '条记录')]/b[1]/text()"
my_seed_rule = "//img[@class='arrowup'][1]/following-sibling::text()[1]"
my_seed_vol_rule = "//tr/td[3]"
my_mailbox_rule = "//a[@href='messages.php']/font[contains(text(),'条')]/text()[1]"
my_message_title = "//img[@alt='Unread']/parent::td/following-sibling::td/a[1]//text()"
my_notice_rule = "//a[@href='index.php']/font[contains(text(),'条')]/text()[1]"
my_notice_title = "//td[@class='text']/div/a"
my_notice_content = "//td[@class='text']/div/a/following-sibling::div"
torrents_rule = "//table[@class='torrents']/tr"
torrent_title_rule = ".//tr/td[@class='embedded'][1]/text()"
torrent_subtitle_rule = ".//a[contains(@href,'detail')]/parent::td/text()[last()]"
torrent_detail_url_rule = ".//td[@class='embedded']/a[contains(@href,'detail')]/@href"
torrent_category_rule = ".//td[@class='rowfollow nowrap'][1]/a[1]/img/@alt"
torrent_poster_rule = ".//table/tr/td[1]/img/@src"
torrent_magnet_url_rule = ".//a[contains(@href,'download')]/@href"
torrent_size_rule = ".//td[5]/text()"
torrent_progress_rule = ".//div[contains(@title,'ing')]/@title"
torrent_hr_rule = ".//table/tr/td/img[@class='hitandrun']/@title"
torrent_sale_rule = ".//img[contains(@class,'pro_')]/@alt"
torrent_sale_expire_rule = ".//td[@class='embedded']/span/text()"
torrent_release_rule = ".//td[4]/span/@title"
torrent_seeders_rule = ".//td[6]/b/a/text()"
torrent_leechers_rule = ".//td[7]/b/a/text()"
torrent_completers_rule = ".//td[8]/a/b/text()"
detail_title_rule = "//h1/text()[1]"
detail_subtitle_rule = "//td[contains(text(),'副标题')]/following-sibling::td/text()[1]"
detail_download_url_rule = "//a[@class='index' and contains(@href,'download.php')]/@href"
detail_size_rule = "//td//b[contains(text(),'大小')]/following::text()[1]"
detail_category_rule = "//td/b[contains(text(),'类型')]/following-sibling::text()[1]"
detail_count_files_rule = "//td/b[contains(text(),'文件数')]/following-sibling::text()[1]"
detail_hash_rule = "//td/b[contains(text(),'Hash')]/following-sibling::text()[1]"
detail_free_rule = "//h1/b/font/@class"
detail_free_expire_rule = "//h1/b/span/@title"
detail_douban_rule = "//td/a[starts-with(@href,'https://movie.douban.com/subject/')][1]"
detail_imdb_rule = "//a[@class='faqlink' and starts-with(@href,'https://www.imdb.com/title/')]/@href"
detail_poster_rule = "//td/a/span[contains(text(),'简介')]/../../following-sibling::td//img[1]/@src"
detail_tags_rule = "//td[contains(text(),'标签')]/following-sibling::td//text()"
torrent_tags_rule = ".//img[contains(@src,'pic/trans.gif') and starts-with(@class, 'label')]/@alt"
detail_hr_rule = "//h1/img[@class='hitandrun']/@title"
alive = true
page_pieces_hash_api = "api/pieces-hash"
pieces_repeat = false
proxy = true
structure = "MTorrent"
type = "pt"
nation = "china"
my_email_rule = "//td[contains(text(),'邮箱')]/following-sibling::td[1]//text()"
my_username_rule = "//table[@id='info_block']//span/a[contains(@class,'_Name') and contains(@href,'userdetails.php?id=')]/b/text()"
buy_page = "mybonus.php?action=exchange"

[buy_action]
"100GB上传流量" = "3"
"100GB下载流量" = "5"
"1个邀请名额" = "6"
"1个临时邀请名额" = "7"
"贵宾待遇" = "9"

[level."小卒"]
level_id = 1
level = "小卒"
days = 0
uploaded = "0"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 0.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "可以發表候選種子。可以發佈趣味盒。可以兌換魔力。"

[level."捕頭"]
level_id = 2
level = "捕頭"
days = 4
uploaded = "0"
downloaded = "200GB"
bonus = 0.0
score = 0
ratio = 2.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "同上"

[level."知縣"]
level_id = 3
level = "知縣"
days = 8
uploaded = "0"
downloaded = "400GB"
bonus = 0.0
score = 0
ratio = 3.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "可以發送邀請。"

[level."通判"]
level_id = 4
level = "通判"
days = 12
uploaded = "0"
downloaded = "500GB"
bonus = 0.0
score = 0
ratio = 4.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "同上"

[level."知州"]
level_id = 5
level = "知州"
days = 16
uploaded = "0"
downloaded = "800GB"
bonus = 0.0
score = 0
ratio = 5.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "同上"

[level."府丞"]
level_id = 6
level = "府丞"
days = 20
uploaded = "0"
downloaded = "1000GB"
bonus = 0.0
score = 0
ratio = 6.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "封存時永久保號"

[level."府尹"]
level_id = 7
level = "府尹"
days = 24
uploaded = "0"
downloaded = "2000GB"
bonus = 0.0
score = 0
ratio = 7.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = true
graduation = false
rights = "永久保號。"

[level."總督"]
level_id = 8
level = "總督"
days = 28
uploaded = "0"
downloaded = "2500GB"
bonus = 0.0
score = 0
ratio = 8.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = true
graduation = false
rights = "魔力值加成：+7%"

[level."大臣"]
level_id = 9
level = "大臣"
days = 32
uploaded = "0"
downloaded = "3000GB"
bonus = 0.0
score = 0
ratio = 9.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = true
graduation = true
rights = "魔力值加成：+8%"

[level.VIP]
level_id = 0
level = "VIP"
days = 0
uploaded = "0"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 0.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = true
graduation = true
rights = "擁有與大臣/NexusMaster相同的權限。下載任何種子，下載量皆不計入分享率。（魔力值加成：+20%）"
