url = [ "https://www.open.cd/", "https://open.cd/",]
name = "OpenCD"
nickname = "皇后"
logo = "favicon.ico"
tracker = "open.cd|tracker.open.cd|www.open.cd|ipv4.open.cd"
sp_full = 400
limit_speed = 100
tags = "音乐"
iyuu = 33
sign_in = true
get_info = true
repeat_torrents = true
brush_free = true
brush_rss = true
hr_discern = false
search_torrents = true
page_index = "index.php"
page_torrents = "torrents.php?incldead=1"
page_sign_in = "plugin_sign-in.php"
page_control_panel = "usercp.php"
page_detail = "details.php?id={}"
page_download = "download.php?id={}&passkey={}"
page_user = "userdetails.php?id={}"
page_search = "torrents.php?search={}"
page_message = "messages.php"
page_hr = "myhr.php?hrtype=1&userid={}"
page_leeching = "getusertorrentlistajax.php?userid={}&type=leeching"
page_uploaded = "getusertorrentlistajax.php?userid={}&type=uploaded"
page_seeding = "getusertorrentlistajax.php?userid={}&type=seeding"
page_completed = "getusertorrentlistajax.php?userid={}&type=completed"
page_mybonus = "mybonus.php"
page_viewfilelist = "viewfilelist.php?id={}"
sign_info_title = "//td[@id='outer']//td[@class='embedded']/h2/text()"
sign_info_content = "//td[@id='outer']//td[@class='embedded']/table//td//text()"
hr = false
hr_rate = 2
hr_time = 10
my_invitation_rule = "//font[@class='color_invite']/following-sibling::text()[1]"
my_time_join_rule = "//td[contains(text(),'加入')]/following-sibling::td/span/@title"
my_latest_active_rule = "//td[contains(text(),'最近动向')]/following-sibling::td/span/@title"
my_uploaded_rule = "//font[@class='color_uploaded']/following-sibling::text()[1]"
my_downloaded_rule = "//font[@class='color_downloaded']/following-sibling::text()[1]"
my_ratio_rule = "//font[@class='color_ratio'][1]/following-sibling::text()[1]"
my_bonus_rule = "//font[@class='color_bonus']/following-sibling::text()[1]"
my_per_hour_bonus_rule = "//div[contains(text(),'每小时能获取')]/text()[1]"
my_score_rule = "//font[@class='color_bonus' and contains(text(),'积分')]/following-sibling::text()[1]"
my_level_rule = "//div/span[@class='nowrap']/a[contains(@class,'_Name')]/@class"
my_passkey_rule = "//td[contains(text(),'密钥')]/following-sibling::td[1]/text()"
my_uid_rule = "//a[contains(@class,'_Name') and contains(@href,'userdetails.php?id=')]/@href"
my_hr_rule = "//a[@href='myhr.php']//text()"
my_leech_rule = "//img[@class='arrowdown']/following-sibling::text()[1]"
my_publish_rule = "//div[contains(., '条记录')]/b[1]/text()"
my_seed_rule = "//img[@class='arrowup']/following-sibling::text()[1]"
my_seed_vol_rule = "//tr/td[3]"
my_mailbox_rule = "//a[@href='messages.php']/font[contains(text(),'条')]/text()[1]"
my_message_title = "//img[@alt='Unread']/parent::td/following-sibling::td/a[1]//text()"
my_notice_rule = "//a[@href='index.php']/font[contains(text(),'条')]/text()[1]"
my_notice_title = "//td[@class='text']/div/a"
my_notice_content = "//td[@class='text']/div/a/following-sibling::div"
torrents_rule = "//table[@class='torrents']/tr"
torrent_title_rule = ".//td[@class='embedded']/a[contains(@href,'detail')]/b/text()[last()]"
torrent_subtitle_rule = ".//a[contains(@href,'detail')]/parent::td/font/text()[last()]"
torrent_detail_url_rule = ".//td[@class='embedded']/a[contains(@href,'detail')]/@href"
torrent_category_rule = ".//td[@class='rowfollow nowrap'][1]/a[1]/img/@class"
torrent_poster_rule = ".//table/tr/td[1]/img/@src"
torrent_magnet_url_rule = ".//td/a[contains(@href,'download')]/@href"
torrent_size_rule = ".//td[5]/text()"
torrent_progress_rule = ".//div[contains(@title,'ing')]/@title"
torrent_hr_rule = ".//table/tr/td/img[@class='hitandrun']/@title"
torrent_sale_rule = ".//img[contains(@class,'pro_')]/@alt"
torrent_sale_expire_rule = ".//img[contains(@class,'free')]/following-sibling::font/span/@title"
torrent_release_rule = ".//td[4]/span/@title"
torrent_seeders_rule = ".//td[6]/b/a/text()"
torrent_leechers_rule = ".//td[7]/b/a/text()"
torrent_completers_rule = ".//td[8]/a/b/text()"
detail_title_rule = "//h1/text()[1]"
detail_subtitle_rule = "//td[contains(text(),'副标题')]/following-sibling::td/text()[1]"
detail_download_url_rule = "//td[contains(text(),'下載鏈接')]/following-sibling::td/a/@href[1]"
detail_size_rule = "//td//b[contains(text(),'大小')]/following::text()[1]"
detail_category_rule = "//td/b[contains(text(),'类型')]/following-sibling::text()[1]"
detail_count_files_rule = "//td/b[contains(text(),'文件数')]/following-sibling::text()[1]"
detail_hash_rule = "//td/b[contains(text(),'Hash')]/following-sibling::text()[1]"
detail_free_rule = "//h1/b/font/@class"
detail_free_expire_rule = "//h1/b/span/@title"
detail_douban_rule = "//td/a[starts-with(@href,'https://movie.douban.com/subject/')][1]"
detail_imdb_rule = "//a[@class='faqlink' and starts-with(@href,'https://www.imdb.com/title/')]/@href"
detail_poster_rule = "//td/a/span[contains(text(),'简介')]/../../following-sibling::td//img[1]/@src"
detail_tags_rule = "//td[contains(text(),'标签')]/following-sibling::td//text()"
torrent_tags_rule = ".//a[contains(@href,'detail')]/../span[contains(@class,'tags')]/text()"
detail_hr_rule = "//h1/img[@class='hitandrun']/@title"
alive = true
page_pieces_hash_api = "api/pieces-hash"
pieces_repeat = false
proxy = true
imdb_search = "torrents.php?search_area=4&search={}"
structure = "NexusPHP"
type = "pt"
nation = "china"
my_email_rule = "//td[contains(text(),'邮箱')]/following-sibling::td[1]//text()"
my_username_rule = "//table[@id='info_block']//span/a[contains(@class,'_Name') and contains(@href,'userdetails.php?id=')]/b/text()"
buy_page = "mybonus.php?action=exchange"

[buy_action]
"100GB上传流量" = "3"
"100GB下载流量" = "5"
"1个邀请名额" = "6"
"1个临时邀请名额" = "7"
"贵宾待遇" = "9"

[level.User]
level_id = 1
level = "User"
days = 0
uploaded = "0"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 0.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "新用戶的默認級別；可以查看NFO/LOG文檔。"

[level.PowerUser]
level_id = 2
level = "PowerUser"
days = 5
uploaded = "0"
downloaded = "20GB"
bonus = 0.0
score = 0
ratio = 1.5
torrents = 5
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "得到一個邀請名額；可以請求續種；可以發送邀請；可以查看排行榜；可以查看其它用戶的種子歷史(如果用戶隱私等級未設置為'強')；可以刪除自己上傳的字幕。"

[level.EliteUser]
level_id = 3
level = "EliteUser"
days = 10
uploaded = "0"
downloaded = "60GB"
bonus = 20.0
score = 0
ratio = 2.0
torrents = 20
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "得到兩個邀請名額；貴人-正六品(EliteUser)及以上用戶封存賬號後規定時間內不會被刪除；發布三個種子後無需經過候選可直接發布種子。"

[level.CrazyUser]
level_id = 4
level = "CrazyUser"
days = 15
uploaded = "0"
downloaded = "200GB"
bonus = 50.0
score = 0
ratio = 2.5
torrents = 50
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "得到三個邀請名額；可以在做種/下載/發布的時候選擇匿名模式。"

[level.InsaneUser]
level_id = 5
level = "InsaneUser"
days = 20
uploaded = "0"
downloaded = "400GB"
bonus = 100.0
score = 0
ratio = 3.0
torrents = 100
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "得到四個邀請名額；可以查看普通日誌。"

[level.VeteranUser]
level_id = 6
level = "VeteranUser"
days = 25
uploaded = "0"
downloaded = "600GB"
bonus = 200.0
score = 0
ratio = 3.5
torrents = 200
leeches = 0
seeding_delta = 0.0
keep_account = true
graduation = false
rights = "得到五個邀請名額；可以查看用戶列表，可以查看其它用戶的評論、帖子歷史。貴嬪-正三品(VeteranUser)及以上用戶會永遠保留賬號。"

[level.ExtremeUser]
level_id = 7
level = "ExtremeUser"
days = 25
uploaded = "0"
downloaded = "1TB"
bonus = 300.0
score = 0
ratio = 4.0
torrents = 300
leeches = 0
seeding_delta = 0.0
keep_account = true
graduation = false
rights = "得到六個邀請名額；可以更新過期的外部信息。"

[level.UltimateUser]
level_id = 8
level = "UltimateUser"
days = 30
uploaded = "0"
downloaded = "2TB"
bonus = 450.0
score = 0
ratio = 4.5
torrents = 450
leeches = 0
seeding_delta = 0.0
keep_account = true
graduation = false
rights = "得到七個邀請名額；查看種子文件的結構。"

[level.NexusMaster]
level_id = 9
level = "NexusMaster"
days = 30
uploaded = "0"
downloaded = "3TB"
bonus = 600.0
score = 0
ratio = 5.0
torrents = 600
leeches = 0
seeding_delta = 0.0
keep_account = true
graduation = true
rights = "得到十個邀請名額。"

[level.VIP]
level_id = 0
level = "VIP"
days = 0
uploaded = "0"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 0.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = true
graduation = true
rights = "和皇后(NexusMaster)擁有相同權限並被認為是精英成員。免除自動降級。"
