url = ["https://springsunday.net/", ]
name = "ssd"
nickname = "不可说"
logo = "favicon.ico"
tracker = "springsunday.net|on.springsunday.net"
sp_full = 107
limit_speed = 95
tags = "影视"
iyuu = 23
sign_in = false
get_info = true
repeat_torrents = true
brush_free = true
brush_rss = true
hr_discern = false
search_torrents = true
page_index = "index.php"
page_torrents = "torrents.php?incldead=1"
page_sign_in = "attendance.php"
page_control_panel = "usercp.php"
page_detail = "details.php?id={}"
page_download = "download.php?id={}&passkey={}"
page_user = "userdetails.php?id={}"
page_search = "torrents.php?search={}"
page_message = "messages.php?action=viewmailbox&box=-2"
page_hr = "myhr.php?hrtype=1&userid={}"
page_leeching = "getusertorrentlistajax.php?userid={}&type=leeching"
page_uploaded = "getusertorrentlistajax.php?userid={}&type=uploaded"
page_seeding = "getusertorrentlistajax.php?userid={}&type=seeding"
page_completed = "getusertorrentlistajax.php?userid={}&type=completed"
page_mybonus = "mybonus.php"
page_viewfilelist = "viewfilelist.php?id={}"
sign_info_title = "//td[@id='outer']//td[@class='embedded']/h2/text()"
sign_info_content = "//td[@id='outer']//td[@class='embedded']/table//td//text()"
hr = false
hr_rate = 2
hr_time = 10
my_invitation_rule = "//div[@id='info_block']//a[contains(@href,'invite.php?id=')]/text()[1]"
my_time_join_rule = "//td[contains(text(),'加入')]/following-sibling::td/span/@title"
my_latest_active_rule = "//td[contains(text(),'最近动向')]/following-sibling::td/span/@title"
my_uploaded_rule = "//div[@id='info_block']//font[@class='color_uploaded']/following-sibling::text()[1]"
my_downloaded_rule = "//div[@id='info_block']//font[@class='color_downloaded']/following-sibling::text()[1]"
my_ratio_rule = "//div[@id='info_block']//font[@class='color_ratio'][1]/following-sibling::text()[1]"
my_bonus_rule = "//a[contains(@href, 'mybonus.php?action=viewlog&id=')]/text()"
my_per_hour_bonus_rule = "//b[contains(text(),'我的数据')]/parent::td/parent::tr/td[last()]/text()"
my_score_rule = "//b[contains(text(),'做种积分')]/following-sibling::text()[1]"
my_level_rule = "//div[@id='info_block']//span[contains(@class,'_Name')]/@class"
my_passkey_rule = "//td[contains(text(),'密钥')]/following-sibling::td[1]/text()"
my_uid_rule = "//div[@id='info_block']//a[contains(@href,'userdetails.php?id=')]/@href"
my_hr_rule = "//a[@href='myhr.php']//text()"
my_leech_rule = "//div[@id='info_block']//img[@class='arrowdown']/following-sibling::text()[1]"
my_publish_rule = "//p/preceding-sibling::b/text()[1]"
my_seed_rule = "//div[@id='info_block']//img[@class='arrowup']/following-sibling::text()[1]"
my_seed_vol_rule = "//b[2]/text()"
my_mailbox_rule = "//a[contains(@href,'messages.php')]/b/text()[1]"
my_message_title = "//img[@alt='Unread']/parent::td/following-sibling::td/a[1]//text()"
my_notice_rule = "//a[contains(@href,'index.php')]/b/text()[1]"
my_notice_title = "//td[@class='text']/div/div/a"
my_notice_content = "//td[@class='text']/div/div/a/following-sibling::div"
torrents_rule = "//table[@class='torrents']/tr"
torrent_title_rule = ".//td[@class='embedded']/div[@class='torrent-smalldescr']/span/text()"
torrent_subtitle_rule = ".//div/a[contains(@href,'details')]/text()[1]"
torrent_detail_url_rule = ".//td[@class='embedded']/div/a[contains(@href,'details.php?id=')]/@href"
torrent_category_rule = ".//td[@class='rowfollow nowrap'][1]/a[1]/img/@alt"
torrent_poster_rule = ".//table/tr/td[1]/img/@src"
torrent_magnet_url_rule = ".//td//a[contains(@href,'download')]/@href"
torrent_size_rule = ".//td[5]/text()"
torrent_progress_rule = ".//div[contains(@title,'ing')]/@title"
torrent_hr_rule = ".//table/tr/td/img[@class='hitandrun']/@title"
torrent_sale_rule = ".//span[contains(@class,'torrent-pro-')]/text()"
torrent_sale_expire_rule = ".//span[contains(@class,'torrent-pro-')]/following-sibling::span/span/@title"
torrent_release_rule = ".//td[4]/span/@title"
torrent_seeders_rule = ".//td[6]/b/a//text()"
torrent_leechers_rule = ".//td[7]/b/a/text()"
torrent_completers_rule = ".//td[8]/a/b/text()"
detail_title_rule = "//h1/span[1]/text()[1] "
detail_subtitle_rule = "//td[contains(text(),'副标题')]/following-sibling::td/text()[1]"
detail_download_url_rule = "//td[contains(text(),'行为')]/following-sibling::td/a[1]/@href[1]"
detail_size_rule = "//td//b[contains(text(),'大小')]/following::text()[1]"
detail_category_rule = "//td/b[contains(text(),'类型')]/following-sibling::text()[1]"
detail_count_files_rule = "//td/b[contains(text(),'文件数')]/following-sibling::text()[1]"
detail_hash_rule = "//td/b[contains(text(),'Hash')]/following-sibling::text()[1]"
detail_free_rule = "//h1/b/font/@class"
detail_free_expire_rule = "//h1/b/span/@title"
detail_douban_rule = "//td/a[starts-with(@href,'https://movie.douban.com/subject/')][1]"
detail_imdb_rule = "//a[@class='faqlink' and starts-with(@href,'https://www.imdb.com/title/')]/@href"
detail_poster_rule = "//td/a/span[contains(text(),'简介')]/../../following-sibling::td//img[1]/@src"
detail_tags_rule = "//td[contains(text(),'标签')]/following-sibling::td//text()"
torrent_tags_rule = ".//div/a/span[contains(@class,'tag')]//text()"
detail_hr_rule = "//h1/img[@class='hitandrun']/@title"
alive = true
page_pieces_hash_api = "api/pieces-hash"
pieces_repeat = false
proxy = true
imdb_search = "torrents.php?search_area=4&search={}"
structure = "NexusPHP"
type = "pt"
nation = "china"

[level.User]
level_id = 1
level = "User"
days = 0
uploaded = "0"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 0.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "新用户的默认级别。可以发种，可以请求续种；可以上传字幕或删除自己上传的字幕；可以更新过期的外部信息。"

[level.EliteUser]
level_id = 2
level = "EliteUser"
days = 0
uploaded = "0"
downloaded = "500GB"
bonus = 0.0
score = 150000
ratio = 1.2
torrents = 1
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "可以在做种 / 下载 / 发布的时候选择匿名模式；可以查看用户列表；可以查看排行榜；可以浏览论坛邀请区；自助申请保种员；等级加成 0.05。"

[level.Master]
level_id = 3
level = "Master"
days = 0
uploaded = "0"
downloaded = "1024GB"
bonus = 0.0
score = 1000000
ratio = 1.2
torrents = 100
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "可以访问高级用户论坛，等级加成 0.15。"

[level.God]
level_id = 4
level = "God"
days = 0
uploaded = "0"
downloaded = "3TB"
bonus = 0.0
score = 2400000
ratio = 2.0
torrents = 300
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "彩色 ID 特权；可以查看普通日志；等级加成 0.25。"

[level.Immortal]
level_id = 10
level = "Immortal"
days = 0
uploaded = "0"
downloaded = "1TB"
bonus = 0.0
score = 1000000
ratio = 1.2
torrents = 100
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "成为当月神王时奖励当时邀请茉莉价格的一半茉莉，最酷炫的动态彩色 ID 特权；常规时期可以购买及发送邀请；等级加成 0.35。"

[level.VIP]
level_id = 0
level = "VIP"
days = 0
uploaded = "0"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 0.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "不计下载量（实际下载量依然会统计），其他权限和神王 (Immortal) 相同。 贵宾 (VIP) 及其以上等级免除自动降级。"
