url = [ "https://springsunday.net/",]
name = "ssd"
nickname = "不可说"
logo = "favicon.ico"
tracker = "springsunday.net|on.springsunday.net"
sp_full = 107
limit_speed = 95
tags = "影视"
iyuu = 23
sign_in = false
get_info = true
repeat_torrents = true
brush_free = true
brush_rss = true
hr_discern = false
search_torrents = true
page_index = "index.php"
page_torrents = "torrents.php?incldead=1"
page_sign_in = "attendance.php"
page_control_panel = "usercp.php"
page_detail = "details.php?id={}"
page_download = "download.php?id={}&passkey={}"
page_user = "userdetails.php?id={}"
page_search = "torrents.php?search={}"
page_message = "messages.php"
page_hr = "myhr.php?hrtype=1&userid={}"
page_leeching = "getusertorrentlistajax.php?userid={}&type=leeching"
page_uploaded = "getusertorrentlistajax.php?userid={}&type=uploaded"
page_seeding = "getusertorrentlistajax.php?userid={}&type=seeding"
page_completed = "getusertorrentlistajax.php?userid={}&type=completed"
page_mybonus = "mybonus.php"
page_viewfilelist = "viewfilelist.php?id={}"
sign_info_title = "//td[@id='outer']//td[@class='embedded']/h2/text()"
sign_info_content = "//td[@id='outer']//td[@class='embedded']/table//td//text()"
hr = false
hr_rate = 2
hr_time = 10
my_invitation_rule = "//div[@id='info_block']//a[contains(@href,'invite.php?id=')]/text()[1]"
my_time_join_rule = "//td[contains(text(),'加入')]/following-sibling::td/span/@title"
my_latest_active_rule = "//td[contains(text(),'最近动向')]/following-sibling::td/span/@title"
my_uploaded_rule = "//div[@id='info_block']//font[@class='color_uploaded']/following-sibling::text()[1]"
my_downloaded_rule = "//div[@id='info_block']//font[@class='color_downloaded']/following-sibling::text()[1]"
my_ratio_rule = "//div[@id='info_block']//font[@class='color_ratio'][1]/following-sibling::text()[1]"
my_bonus_rule = "//div[@id='info_block']//a[@href='mybonus.php']/text()[1]"
my_per_hour_bonus_rule = "//b[contains(text(),'我的数据')]/parent::td/parent::tr/td[last()]/text()"
my_score_rule = "//b[contains(text(),'做种积分')]/following-sibling::text()[1]"
my_level_rule = "//div[@id='info_block']//span[contains(@class,'_Name')]/@class"
my_passkey_rule = "//td[contains(text(),'密钥')]/following-sibling::td[1]/text()"
my_uid_rule = "//div[@id='info_block']//a[contains(@href,'userdetails.php?id=')]/@href"
my_hr_rule = "//a[@href='myhr.php']//text()"
my_leech_rule = "//div[@id='info_block']//img[@class='arrowdown']/following-sibling::text()[1]"
my_publish_rule = "//p/preceding-sibling::b/text()[1]"
my_seed_rule = "//div[@id='info_block']//img[@class='arrowup']/following-sibling::text()[1]"
my_seed_vol_rule = "//b[2]/text()"
my_mailbox_rule = "//a[@href='messages.php']//text()[1]"
my_message_title = "//img[@alt='Unread']/parent::td/following-sibling::td/a[1]//text()"
my_notice_rule = "//a[@href='index.php']/b/text()"
my_notice_title = "//td[@class='text']/div/div/a"
my_notice_content = "//td[@class='text']/div/div/a/following-sibling::div"
torrents_rule = "//table[@class='torrents']/tr"
torrent_title_rule = ".//td[@class='embedded']/div[@class='torrent-smalldescr']/text()"
torrent_subtitle_rule = ".//a[contains(@href,'detail')]/parent::td/text()[last()]"
torrent_detail_url_rule = ".//td[@class='embedded']/div/a[contains(@href,'details.php?id=')]/@href"
torrent_category_rule = ".//td[@class='rowfollow nowrap'][1]/a[1]/img/@class"
torrent_poster_rule = ".//table/tr/td[1]/img/@src"
torrent_magnet_url_rule = ".//td//a[contains(@href,'download')]/@href"
torrent_size_rule = ".//td[5]/text()"
torrent_hr_rule = ".//table/tr/td/img[@class='hitandrun']/@title"
torrent_sale_rule = ".//img[contains(@class,'pro_')]/@alt"
torrent_sale_expire_rule = ".//img[contains(@class,'free')]/following-sibling::span/span/@title"
torrent_release_rule = ".//td[4]/span/@title"
torrent_seeders_rule = ".//td[6]/b/a/text()"
torrent_leechers_rule = ".//td[7]/b/a/text()"
torrent_completers_rule = ".//td[8]/a/b/text()"
detail_title_rule = "//h1/text()[1]"
detail_subtitle_rule = "//td[contains(text(),'副标题')]/following-sibling::td/text()[1]"
detail_download_url_rule = "//a[@class='index' and contains(@href,'download.php')]/@href"
detail_size_rule = "//td//b[contains(text(),'大小')]/following::text()[1]"
detail_category_rule = "//td/b[contains(text(),'类型')]/following-sibling::text()[1]"
detail_count_files_rule = "//td/b[contains(text(),'文件数')]/following-sibling::text()[1]"
detail_hash_rule = "//td/b[contains(text(),'Hash')]/following-sibling::text()[1]"
detail_free_rule = "//h1/b/font/@class"
detail_free_expire_rule = "//h1/b/span/@title"
detail_douban_rule = "//td/a[starts-with(@href,'https://movie.douban.com/subject/')][1]"
detail_imdb_rule = "//a[@class='faqlink' and starts-with(@href,'https://www.imdb.com/title/')]/@href"
detail_poster_rule = "//td/a/span[contains(text(),'简介')]/../../following-sibling::td//img[1]/@src"
detail_tags_rule = "//td[contains(text(),'标签')]/following-sibling::td//text()"
torrent_tags_rule = ".//a[contains(@href,'detail')]/../span[contains(@class,'tags')]/text()"
detail_hr_rule = "//h1/img[@class='hitandrun']/@title"
alive = true
page_pieces_hash_api = "api/pieces-hash"
pieces_repeat = false
proxy = true

[level.User]
level_id = 1
level = "User"
days = 0
uploaded = "0"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 0.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "新用户的默认级别。可以申请友情链接。"

[level.PowerUser]
level_id = 2
level = "PowerUser"
days = 5
uploaded = "0"
downloaded = "100GB"
bonus = 0.0
score = 20000
ratio = 1.1
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "可以查看NFO文档；可以请求续种；可以上传字幕或删除自己上传的字幕。"

[level.EliteUser]
level_id = 3
level = "EliteUser"
days = 5
uploaded = "0"
downloaded = "200GB"
bonus = 0.0
score = 50000
ratio = 1.2
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "可以查看用户列表；可以查看排行榜。"

[level.CrazyUser]
level_id = 4
level = "CrazyUser"
days = 5
uploaded = "0"
downloaded = "500GB"
bonus = 0.0
score = 100000
ratio = 1.2
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "可以更新过期的外部信息；可以在做种/下载/发布的时候选择匿名模式；可以浏览论坛邀请区。着迷(CrazyUser)及以上用户封存账号后不会被删除。"

[level.InsaneUser]
level_id = 5
level = "InsaneUser"
days = 5
uploaded = "0"
downloaded = "1TB"
bonus = 0.0
score = 200000
ratio = 1.2
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "可以查看其它用户的种子历史（如果用户隐私等级未设置为“强”）。"

[level.VeteranUser]
level_id = 6
level = "VeteranUser"
days = 5
uploaded = "0"
downloaded = "2TB"
bonus = 0.0
score = 400000
ratio = 1.2
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "资深(VeteranUser)及以上用户会永远保留账号。该等级以上（含）可免除站点常规考核。"

[level.ExtremeUser]
level_id = 7
level = "ExtremeUser"
days = 5
uploaded = "0"
downloaded = "3TB"
bonus = 0.0
score = 600000
ratio = 1.5
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "得到1个邀请名额。"

[level.UltimateUser]
level_id = 8
level = "UltimateUser"
days = 5
uploaded = "0"
downloaded = "4TB"
bonus = 0.0
score = 800000
ratio = 1.5
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "可以查看其它用户的评论、帖子历史。"

[level.NexusMaster]
level_id = 9
level = "NexusMaster"
days = 5
uploaded = "0"
downloaded = "5TB"
bonus = 0.0
score = 1000000
ratio = 1.5
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "得到1个邀请名额。"

[level.NexusGod]
level_id = 10
level = "NexusGod"
days = 5
uploaded = "0"
downloaded = "11TB"
bonus = 0.0
score = 2200000
ratio = 2.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "彩色ID特权；可以查看普通日志；可以购买及发送邀请。"

[level.VIP]
level_id = 0
level = "VIP"
days = 0
uploaded = "0"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 0.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "不计下载量（实际下载量依然会统计），其他权限和神仙(Nexusxa0God)相同，并被认为是精英成员。贵宾(VIP)及其以上等级免除自动降级。"
