url = [ "https://www.tjupt.org/", "https://tjupt.org/",]
name = "tjupt"
nickname = "北洋园"
logo = "favicon.ico"
tracker = "tracker-public.tjupt.org"
sp_full = 150
limit_speed = 100
tags = "影视,教育站,综合"
iyuu = 5
sign_in = true
get_info = true
repeat_torrents = true
brush_free = true
brush_rss = true
hr_discern = false
search_torrents = true
page_index = "index.php"
page_torrents = "torrents.php?incldead=1"
page_sign_in = "attendance.php"
page_control_panel = "usercp.php"
page_detail = "details.php?id={}"
page_download = "download.php?id={}&passkey={}"
page_user = "userdetails.php?id={}"
page_search = [ "torrents.php?search={}",]
page_message = "messages.php"
page_hr = "myhr.php?hrtype=1&userid={}"
page_leeching = "getusertorrentlistajax.php?userid={}&type=leeching"
page_uploaded = "getusertorrentlistajax.php?userid={}&type=uploaded"
page_seeding = "getusertorrentlistajax.php?userid={}&type=seeding"
page_completed = "getusertorrentlistajax.php?userid={}&type=completed"
page_mybonus = "bonus.php?show=description"
page_viewfilelist = "viewfilelist.php?id={}"
sign_info_title = "//td[@id='outer']//td[@class='embedded']/h2/text()"
sign_info_content = "//td[@id='outer']//td[@class='embedded']/table//td//text()"
hr = false
hr_rate = 2
hr_time = 10
my_invitation_rule = "//span/a[contains(@href,'invite.php?id=')]/following-sibling::text()[1]"
my_time_join_rule = "//td[contains(text(),'加入')]/following-sibling::td/span/@title"
my_latest_active_rule = "//td[contains(text(),'最近动向')]/following-sibling::td/span/@title"
my_uploaded_rule = "//span[@class='color_uploaded']/following-sibling::text()[1]"
my_downloaded_rule = "//font[@class='color_downloaded']/following-sibling::text()[1]"
my_ratio_rule = "//strong[contains(text(),'做种/下载时间比率')]/following-sibling::font[1]/text()"
my_bonus_rule = "//td[contains(text(),'魔力值')]/following-sibling::td/a/text()"
my_per_hour_bonus_rule = "//div[contains(text(),'每小时')]/text()[1]"
my_score_rule = "//td[contains(text(),'做种积分')]/following-sibling::td/a/text()"
my_level_rule = "//table[@id='info_block']//span/a[contains(@class,'_Name') and contains(@href,'userdetails.php?id=')]/@class"
my_passkey_rule = "//td[contains(text(),'密钥')]/following-sibling::td[1]/span/text()"
my_uid_rule = "//table[@id='info_block']//span/a[contains(@class,'_Name') and contains(@href,'userdetails.php?id=')]/@href"
my_hr_rule = "//a[@href='/hnr_details.php'][last()]//text()"
my_leech_rule = "//img[@class='arrowdown'][1]/following-sibling::text()[1]"
my_publish_rule = "(//body//b)[1]/text()"
my_seed_rule = "//img[@class='arrowup'][1]/following-sibling::text()[1]"
my_seed_vol_rule = "//body/text()[1]"
my_mailbox_rule = "//a[@href='messages.php']/span/strong[contains(text(),'条')]/text()[1]"
my_message_title = "//img[@alt='Unread']/parent::td/following-sibling::td/a[1]//text()"
my_notice_rule = "//a[@href='index.php']/font[contains(text(),'条')]/text()[1]"
my_notice_title = "//td[@class='text']/div/a"
my_notice_content = "//td[@class='text']/div/a/following-sibling::div"
torrents_rule = "//td[@class='embedded']/table[@class='torrents'][1]/tr[@class]"
torrent_title_rule = ".//a[contains(@href,'detail')]/parent::td/a/b/text()[last()]"
torrent_subtitle_rule = ".//a[contains(@href,'detail')]/parent::td/text()[last()]"
torrent_detail_url_rule = ".//td[@class='embedded']/a[contains(@href,'detail')]/@href"
torrent_category_rule = ".//td[@class='rowfollow nowrap'][1]/a[1]/img/@title"
torrent_poster_rule = ".//table/tr/td[1]/img/@src"
torrent_magnet_url_rule = ".//td/a[contains(@href,'download.php?id=')]/@href"
torrent_size_rule = ".//td[5]/text()"
torrent_progress_rule = ".//div[contains(@title,'ing')]/@title"
torrent_hr_rule = ".//table/tr/td/img[@class='hitandrun']/@title"
torrent_sale_rule = ".//img[contains(@class,'pro_')]/@alt"
torrent_sale_expire_rule = ".//img[contains(@class,'free')]/following-sibling::font/span/@title"
torrent_release_rule = ".//td[4]/text()"
torrent_seeders_rule = ".//a[contains(@href,'#seeders')]/text()"
torrent_leechers_rule = ".//a[contains(@href,'#leechers')]/text()"
torrent_completers_rule = ".//a[contains(@href,'viewsnatches')]//text()"
detail_title_rule = "//a[@class='index' and contains(@href,'download.php')]/text()"
detail_subtitle_rule = "//h1/text()[1]"
detail_download_url_rule = "//td[contains(text(),'行为')]/following-sibling::td/a/b[contains(text(),'直链')]/../@href[1]"
detail_size_rule = "//td//b[contains(text(),'大小')]/../following::text()[1]"
detail_category_rule = "//td/b[contains(text(),' 类型')]/following-sibling::text()[1]"
detail_count_files_rule = "//td/b[contains(text(),'文件数')]/following-sibling::text()[1]"
detail_hash_rule = "//td/b[contains(text(),'Hash')]/following-sibling::text()[1]"
detail_free_rule = "//h1/font/@class"
detail_free_expire_rule = "//h1/b/span/@title"
detail_douban_rule = "//td//a[starts-with(@href,'https://movie.douban.com/subject/') and @class='faqlink'][1]/@href"
detail_imdb_rule = "//a[@class='faqlink' and starts-with(@href,'http://www.imdb.com/title/')]/@href"
detail_poster_rule = "//td/a/span[contains(text(),'简介')]/../../following-sibling::td//img[1]/@src"
detail_tags_rule = ".//td//font[contains(@class,'tag ')]/text()"
torrent_tags_rule = ".//td//font[contains(@class,'tag ')]/text()"
detail_hr_rule = "//h1/img[@class='hitandrun']/@title"
alive = true
page_pieces_hash_api = "api/pieces-hash"
pieces_repeat = false
proxy = true
imdb_search = "torrents.php?search_area=4&search={}"
structure = "NexusPHP"
type = "pt"
nation = "china"
my_email_rule = "//td[contains(text(),'邮箱')]/following-sibling::td[1]//text()"
my_username_rule = "//table[@id='info_block']//span/a[contains(@class,'_Name') and contains(@href,'userdetails.php?id=')]/b//text()"
buy_page = "mybonus.php?action=exchange"

[buy_action]
"100GB上传流量" = "3"
"100GB下载流量" = "5"
"1个邀请名额" = "6"
"1个临时邀请名额" = "7"
"贵宾待遇" = "9"

[level.Peasant]
level_id = -1
level = "Peasant"
name = "将功赎罪"
days = 0
uploaded = "0"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 0.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "被降级的用户，他们有14天时间来提升分享率，否则他们会被踢。不能发表趣味盒内容；不能申请友情链接；不能上传字幕；不能查看排行榜。"

[level.User]
level_id = 1
level = "User"
name = "无名小辈"
days = 0
uploaded = "0"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 0.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "新用户的默认级别。"

[level.PowerUser]
level_id = 2
level = "PowerUser"
name = "拜师学艺"
days = 4
uploaded = "50GB"
downloaded = "0"
bonus = 10000.0
score = 0
ratio = 0.0
torrents = 0
leeches = 20
seeding_delta = 30.0
keep_account = false
graduation = false
rights = "可以直接发布种子；可以查看NFO文档；可以查看用户列表；可以请求续种；可以查看其它用户的种子历史(如果用户隐私等级未设置为\"强\")； 可以删除自己上传的字幕。"

[level.EliteUser]
level_id = 3
level = "EliteUser"
name = "持剑下山"
days = 8
uploaded = "200GB"
downloaded = "0"
bonus = 30000.0
score = 0
ratio = 0.0
torrents = 0
leeches = 60
seeding_delta = 120.0
keep_account = false
graduation = false
rights = "持剑下山 及以上用户封存账号后不会被删除。"

[level.CrazyUser]
level_id = 4
level = "CrazyUser"
name = "初入江湖"
days = 16
uploaded = "800GB"
downloaded = "0"
bonus = 80000.0
score = 0
ratio = 0.0
torrents = 1
leeches = 150
seeding_delta = 450.0
keep_account = false
graduation = false
rights = "得到一个邀请名额；可以发送邀请；可以在做种/下载/发布的时候选择匿名模式。"

[level.InsaneUser]
level_id = 5
level = "InsaneUser"
name = "小有名气"
days = 28
uploaded = "2000GB"
downloaded = "0"
bonus = 150000.0
score = 0
ratio = 0.0
torrents = 5
leeches = 300
seeding_delta = 1500.0
keep_account = false
graduation = false
rights = "得到一个邀请名额；可以查看普通日志。"

[level.VeteranUser]
level_id = 6
level = "VeteranUser"
name = "威震一方"
days = 48
uploaded = "5000GB"
downloaded = "0"
bonus = 300000.0
score = 0
ratio = 0.0
torrents = 10
leeches = 600
seeding_delta = 4200
keep_account = true
graduation = false
rights = "得到一个邀请名额；可以查看其它用户的评论、帖子历史。 威震一方 及以上用户会永远保留账号。"

[level.ExtremeUser]
level_id = 7
level = "ExtremeUser"
name = "横扫群雄"
days = 72
uploaded = "10000GB"
downloaded = "0"
bonus = 400000.0
score = 0
ratio = 0.0
torrents = 15
leeches = 1000
seeding_delta = 28000.0
keep_account = true
graduation = false
rights = "得到一个邀请名额；可以更新过期的外部信息。"

[level.UltimateUser]
level_id = 8
level = "UltimateUser"
name = "开宗立派"
days = 100
uploaded = "20000GB"
downloaded = "0"
bonus = 600000.0
score = 0
ratio = 0.0
torrents = 30
leeches = 1800
seeding_delta = 90000.0
keep_account = true
graduation = false
rights = "得到两个邀请名额。"

[level.NexusMaster]
level_id = 9
level = "NexusMaster"
name = "天下无敌"
days = 132
uploaded = "50000GB"
downloaded = "0"
bonus = 1000000.0
score = 0
ratio = 0.0
torrents = 50
leeches = 3000
seeding_delta = 300000.0
keep_account = true
graduation = true
rights = "得到三个邀请名额。"

[level.VIP]
level_id = 0
level = "VIP"
name = "贵宾"
days = 0
uploaded = "0"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 0.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = true
graduation = true
rights = "和 天下无敌 拥有相同权限并被认为是精英成员。免除自动降级。"

[level.Retiree]
level_id = 0
level = "Retiree"
name = "扫地僧(养老族Retiree)"
days = 0
uploaded = "0"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 0.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "退休后的管理组成员。"

[level.Uploader]
level_id = 0
level = "Uploader"
name = "龙门镖局(发布员Uploader)"
days = 0
uploaded = "0"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 0.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "专注的发布者。免除自动降级；可以查看匿名用户的真实身份。"

[level.Moderator]
level_id = 0
level = "Moderator"
name = "六扇门(类管理员Moderator)"
days = 0
uploaded = "0"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 0.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "可以查看管理组信箱、举报信箱；管理趣味盒内容、投票内容；可以编辑或删除任何发布的种子；可以管理候选；可以管理论坛帖子、用户评论；可以查看机密日志；可以删除任何字幕；可以管理日志中的代码、史册；可以查看用户的邀请记录；可以管理用户帐号的一般信息。 不能 管理友情链接、最近消息、论坛版块； 不能 将种子设为置顶或促销； 不能 查看用户IP或Email等机密信息；不能删除账号。"

[level.Administrator]
level_id = 0
level = "Administrator"
name = "中枢六部(管理员Administrator)"
days = 0
uploaded = "0"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 0.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "除了不能改变站点设定、管理捐赠外，可以做任何事。"

[level.Sysop]
level_id = 0
level = "Sysop"
name = "锦衣卫(维护开发员Sysop)"
days = 0
uploaded = "0"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 0.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "网站开发/维护人员，可以改变站点设定，不能管理捐赠。"

[level.StaffLeader]
level_id = 0
level = "StaffLeader"
name = "九五之尊(主管Staff Leader)"
days = 0
uploaded = "0"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 0.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "网站主管，可以做任何事。"

[level.BitTorrent]
level_id = 0
level = "BitTorrent"
name = "BitTorrent"
days = 0
uploaded = "0"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 0.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "6881 - 6889"

[level.Kazza]
level_id = 0
level = "Kazza"
name = "Kazza"
days = 0
uploaded = "0"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 0.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "1214"

[level.Gnutella]
level_id = 0
level = "Gnutella"
name = "Gnutella"
days = 0
uploaded = "0"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 0.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "6346 - 6347"

[level.Emule]
level_id = 0
level = "Emule"
name = "Emule"
days = 0
uploaded = "0"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 0.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "4662"

[level.WinMX]
level_id = 0
level = "WinMX"
name = "WinMX"
days = 0
uploaded = "0"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 0.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "6699"
