url = [ "https://www.torrentleech.cc/", "https://www.torrentleech.org/", "https://www.torrentleech.me/", "https://www.tleechreload.org/",]
name = "TorrentLeech"
nickname = "TorrentLeech"
logo = "favicon.ico"
tracker = "tracker.torrentleech.org|tracker.tleechreload.org"
sp_full = 107
limit_speed = 100
tags = "影视"
iyuu = 0
sign_in = false
get_info = true
repeat_torrents = true
brush_free = true
brush_rss = false
hr_discern = false
search_torrents = false
page_index = ""
page_torrents = "torrents/browse/list"
page_sign_in = "attendance.php"
page_control_panel = "profile/{}/view"
page_detail = "details.php?id={}"
page_download = "download.php?id={}&passkey={}"
page_user = "profile/{}/view"
page_search = "torrents/browse/list/query/{}"
page_message = "profile/{}/notifications"
page_hr = "myhr.php?hrtype=1&userid={}"
page_leeching = "getusertorrentlistajax.php?userid={}&type=leeching"
page_uploaded = "getusertorrentlistajax.php?userid={}&type=uploaded"
page_seeding = "profile/{}/seeding"
page_completed = "getusertorrentlistajax.php?userid={}&type=completed"
page_mybonus = "profile/{}/marketplace"
page_viewfilelist = "viewfilelist.php?id={}"
sign_info_title = "//td[@id='outer']//td[@class='embedded']/h2/text()"
sign_info_content = "//td[@id='outer']//td[@class='embedded']/table//td//text()"
hr = false
hr_rate = 2
hr_time = 336
my_invitation_rule = "//span[contains(@onclick,'invites')]/text()"
my_time_join_rule = "//td[contains(text(),'Registration date')]/following-sibling::td/text()"
my_latest_active_rule = "//td[contains(text(),'Last visit')]/following-sibling::td/text()"
my_uploaded_rule = "//span[contains(@onclick,'seeding')]/text()"
my_downloaded_rule = "//span[contains(@onclick,'leeching')]/text()[1]"
my_ratio_rule = "//div[contains(@title,'Ratio')]/text()"
my_bonus_rule = "//span[contains(@onclick,'marketplace')]/span/text()"
my_per_hour_bonus_rule = "//p[contains(text(),'Available TL points: ')]/span/text()"
my_score_rule = "//span[contains(@onclick,'marketplace')]/span/text()"
my_level_rule = "//td[contains(text(),'Class')]/following-sibling::td/text()"
my_passkey_rule = "//td[contains(text(),'Torrent Passkey')]/following-sibling::td/text()"
my_uid_rule = "//div/span/span/span[contains(@class, 'user_')]/text()"
my_hr_rule = "//span[contains(@onclick,'hnr')]/text()"
my_leech_rule = "//span[contains(@onclick,'leeching')]/following-sibling::text()[1]"
my_publish_rule = "//div[contains(., '条记录')]/b[1]/text()"
my_seed_rule = "//span[contains(@onclick,'seeding')]/following-sibling::text()[1]"
my_seed_vol_rule = "//td[2]"
my_mailbox_rule = "//span[contains(@onclick,'notifications')]//span/text()"
my_message_title = "//td/i/../parent::tr/td[last()]/text()"
my_notice_rule = "//a[@href='index.php']/font[contains(text(),'条')]/text()[1]"
my_notice_title = "//td[@class='text']/div/a//text()"
my_notice_content = "//td[@class='text']/div/a/following-sibling::div"
torrents_rule = "//tr[@class='torrent']"
torrent_title_rule = ".//td[@class='td-name']/div[@class='name']/a/text()[1]"
torrent_subtitle_rule = ".//a[contains(@href,'detail')]/parent::td/text()[last()]"
torrent_detail_url_rule = ".//td[@class='td-name']/div[@class='name']/a/@href"
torrent_category_rule = ".//td[@class='td-category']/div[@class='circle']/a/@data-ccid"
torrent_poster_rule = ".//table/tr/td[1]/img/@src"
torrent_magnet_url_rule = ".//td[@class='td-quick-download']/a/@href"
torrent_size_rule = ".//td[@class='td-size']/div/text()"
torrent_progress_rule = ".//div[contains(@title,'ing')]/@title"
torrent_hr_rule = ".//table/tr/td/img[@class='hitandrun']/@title"
torrent_sale_rule = ".//span[contains(@class,'freeleech')]/text()"
torrent_sale_expire_rule = ".//img[contains(@class,'free')]/following-sibling::font/span/@title"
torrent_release_rule = ".//td[@class='td-uploaded-time']/div/text()"
torrent_seeders_rule = ".//td[@class='td-seeders']/div/text()"
torrent_leechers_rule = ".//td[@class='td-leechers']/div/text()"
torrent_completers_rule = ".//td[@class='td-snatched']/div/text()"
detail_title_rule = "//*[@id='torrentnameid']/text()"
detail_subtitle_rule = "//td[contains(text(),'副标题')]/following-sibling::td/text()[1]"
detail_download_url_rule = "//a[@id='detailsDownloadButton']/@href"
detail_size_rule = "//td[contains(text(),'Size')]/following::text()[1]"
detail_category_rule = "//td[contains(text(),'Category')]/following::text()[1]"
detail_count_files_rule = "//td/b[contains(text(),'文件数')]/following-sibling::text()[1]"
detail_hash_rule = "//td/b[contains(text(),'Hash')]/following-sibling::text()[1]"
detail_free_rule = "//span[contains(@class,'freeleech')]/text()"
detail_free_expire_rule = "//h1/b/span/@title"
detail_douban_rule = "//td/a[starts-with(@href,'https://movie.douban.com/subject/')][1]"
detail_imdb_rule = "//a[@class='faqlink' and starts-with(@href,'https://www.imdb.com/title/')]/@href"
detail_poster_rule = "//td/a/span[contains(text(),'简介')]/../../following-sibling::td//img[1]/@src"
detail_tags_rule = "//td[contains(text(),'Tags')]/following-sibling::td//text()"
torrent_tags_rule = ".//a[contains(@href,'detail')]/../span[contains(@class,'tags')]/text()"
detail_hr_rule = "//h1/img[@class='hitandrun']/@title"
alive = true
page_pieces_hash_api = "api/pieces-hash"
pieces_repeat = false
proxy = true
imdb_search = "torrents.php?search_area=4&search={}"
structure = "TorrentLeech"
type = "pt"
nation = "foreign"
my_email_rule = "//td[contains(text(),'Email')]/following-sibling::td[1]//text()"
my_username_rule = "//td[contains(text(),'Username')]/following-sibling::td/text()"
buy_page = "mybonus.php?action=exchange"

[buy_action]
"100GB上传流量" = "3"
"100GB下载流量" = "5"
"1个邀请名额" = "6"
"1个临时邀请名额" = "7"
"贵宾待遇" = "9"
