url = [ "https://totheglory.im/",]
name = "TTG"
nickname = "TTG"
logo = "favicon.ico"
tracker = "tracker.totheglory.im"
sp_full = 107
limit_speed = 30
tags = "影视"
iyuu = 14
sign_in = true
get_info = true
repeat_torrents = true
brush_free = true
brush_rss = true
hr_discern = false
search_torrents = true
page_index = "index.php"
page_torrents = "torrents.php?incldead=1"
page_sign_in = "signed.php"
page_control_panel = "usercp.php"
page_detail = "t/{}/"
page_download = "dl/{}/{}"
page_user = "userdetails.php?id={}"
page_search = "browse.php?search_field={}&c=M"
page_message = "messages.php"
page_hr = "myhr.php?hrtype=1&userid={}"
page_leeching = "getusertorrentlistajax.php?userid={}&type=leeching"
page_uploaded = "getusertorrentlistajax.php?userid={}&type=uploaded"
page_seeding = "userdetails.php?id={}"
page_completed = "getusertorrentlistajax.php?userid={}&type=completed"
page_mybonus = "mybonus.php"
page_viewfilelist = "viewfilelist.php?id={}"
sign_info_title = "//td[@id='outer']//td[@class='embedded']/h2/text()"
sign_info_content = "//td[@id='outer']//td[@class='embedded']/table//td//text()"
hr = false
hr_rate = 2
hr_time = 10
my_invitation_rule = "//a[contains(@href,'invite.php')]/span/text()[1]"
my_time_join_rule = "//td[contains(text(),'注册日期')]/following-sibling::td[1]/text()"
my_latest_active_rule = "//td[contains(text(),'上次访问')]/following-sibling::td[1]/text()"
my_uploaded_rule = "//font[contains(text(),'上传量')]/following-sibling::font[1]/a/text()[1]"
my_downloaded_rule = "//font[contains(text(),'下载量')]/following-sibling::font[1]/a/text()[1]"
my_ratio_rule = "//font[contains(text(),'分享率 ')][1]/following-sibling::font[1]/text()[1]"
my_bonus_rule = "//a[contains(@href,'mybonus.php')]/text()[1]"
my_per_hour_bonus_rule = "//td[contains(text(),'总计')]/following-sibling::td/text()"
my_score_rule = "//font[contains(text(),'HP')]/following-sibling::text()[1]"
my_level_rule = "//td[contains(text(),'等级')]/following-sibling::td/text()"
my_passkey_rule = "//td[contains(text(),'Passkey')]/following-sibling::td[1]/text()"
my_uid_rule = "//a[contains(@href,'/userdetails.php?id=')]/@href"
my_hr_rule = "//a[@href='myhr.php']/text()"
my_leech_rule = "//img[contains(@title,'下载中')]/following-sibling::font[1]/span/text()[1]"
my_publish_rule = "//p/preceding-sibling::b/text()[1]"
my_seed_rule = "//img[contains(@title,'做种中')]/following-sibling::font[1]/span/text()[1]"
my_seed_vol_rule = "//*[@id='ka2']//td[not(@class)][4]"
my_mailbox_rule = "//a[contains(@href,'messages.php')]/font[contains(text(),'个')]/text()[1]"
my_message_title = "//img[@alt='Unread']/parent::td/following-sibling::td/a[1]//text()"
my_notice_rule = "//a[@href='/announcement.php']/font/text()"
my_notice_title = "//td[@class='text']/ul/li"
my_notice_content = "//td[@class='text']/div/a/following-sibling::div"
torrents_rule = "//table[@id='torrent_table']/tr[@class]"
torrent_title_rule = ".//div[@class='name_left']/a/b//text()[1][name(..)!='span']"
torrent_subtitle_rule = ".//div[@class='name_left']/a/b//span/text()"
torrent_detail_url_rule = ".//div/a[contains(@href,'/t/')]/@href"
torrent_category_rule = ".//img[contains(@src,'cate')]/@alt"
torrent_poster_rule = ".//table/tr/td[1]/img/@src"
torrent_magnet_url_rule = ".//img[contains(@class,'dl_img')]/parent::a/@href"
torrent_size_rule = ".//td[7]/text()"
torrent_progress_rule = ".//div[contains(@title,'ing')]/@title"
torrent_hr_rule = ".//img[@title='Hit and Run']"
torrent_sale_rule = ".//img[contains(@src,'/pic/ico_')]/@alt"
torrent_sale_expire_rule = ".//span/@onclick"
torrent_release_rule = ".//td[5]//text()"
torrent_seeders_rule = ".//a[contains(@href,'&toseeders')]//text()"
torrent_leechers_rule = ".//a[contains(@href,'&todlers')]//text()"
torrent_completers_rule = ".//td[8]/text()[1]"
detail_title_rule = "//h1/text()[1]"
detail_subtitle_rule = "//td[contains(text(),'副标题')]/following-sibling::td/text()[1]"
detail_download_url_rule = "//td/a[contains(@href,'/dl/') and contains(text(),'点击复制到剪切板')]/@href"
detail_size_rule = "//td//b[contains(text(),'大小')]/following::text()[1]"
detail_category_rule = "//td[contains(text(),'类型')]/following-sibling::td/text()[1]"
detail_count_files_rule = "//td/b[contains(text(),'文件数')]/following-sibling::text()[1]"
detail_hash_rule = "//td/b[contains(text(),'Hash')]/following-sibling::text()[1]"
detail_free_rule = "//div/img[contains(@src,'free')]/@src"
detail_free_expire_rule = "//div/img[contains(@src,'free')]/following-sibling::font/text()"
detail_douban_rule = "//div/a[starts-with(@href,'https://movie.douban.com/subject/')][1]"
detail_imdb_rule = "//td/a[starts-with(@href,'https://www.imdb.com/title/')]/@href"
detail_poster_rule = "//td/span[contains(text(),'简述')]/../following-sibling::td/div/img[1]/@src"
detail_tags_rule = "//td[contains(text(),'标签')]/following-sibling::td//text()"
torrent_tags_rule = ".//a[contains(@href,'detail')]/../span[contains(@class,'tags')]/text()"
detail_hr_rule = "//h1/img[@class='hitandrun']/@title"
alive = true
page_pieces_hash_api = "api/pieces-hash"
pieces_repeat = false
proxy = true
structure = "NexusPHP"

[level.Byte]
level_id = 1
level = "Byte"
days = 0
uploaded = "0"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 0.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "此为入站最初始等级，接受新人考核制。"

[level.KiloByte]
level_id = 2
level = "KiloByte"
days = 5
uploaded = "0"
downloaded = "60GB"
bonus = 0.0
score = 0
ratio = 1.1
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "此等级才为正式会员，可申请种子候选。此等级及以下会员12周不活动将被系统自动清除。"

[level.MegaByte]
level_id = 3
level = "MegaByte"
days = 8
uploaded = "0"
downloaded = "150GB"
bonus = 0.0
score = 0
ratio = 2.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "此等级及以上会员12周不活动将被系统自动清除。"

[level.GigaByte]
level_id = 4
level = "GigaByte"
days = 8
uploaded = "0"
downloaded = "250GB"
bonus = 0.0
score = 0
ratio = 2.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "此等级可挂起，可进入积分商城（内测中，尽请期待）。"

[level.TeraByte]
level_id = 5
level = "TeraByte"
days = 16
uploaded = "0"
downloaded = "500GB"
bonus = 0.0
score = 0
ratio = 2.5
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "此等级可用积分购买邀请，并可浏览全站（新加游戏分类页），可以访问邀请区。"

[level.PetaByte]
level_id = 6
level = "PetaByte"
days = 24
uploaded = "0"
downloaded = "750GB"
bonus = 0.0
score = 0
ratio = 2.5
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "此等级可直接发布种子。此等级及以下会员挂起超过180天将被系统自动清除。"

[level.ExaByte]
level_id = 7
level = "ExaByte"
days = 24
uploaded = "0"
downloaded = "1TB"
bonus = 0.0
score = 0
ratio = 3.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "此等级自行挂起账号后不会被清除。"

[level.ZettaByte]
level_id = 8
level = "ZettaByte"
days = 24
uploaded = "0"
downloaded = "1.5TB"
bonus = 0.0
score = 0
ratio = 3.5
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "此等级免除流量考核。（至于是年中年终两次还是只年终，什么时候开始目前还尚未定论）"

[level.YottaByte]
level_id = 9
level = "YottaByte"
days = 24
uploaded = "0"
downloaded = "2.5TB"
bonus = 0.0
score = 0
ratio = 4.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "此等级可查看排行榜。此等级及以下会员12周不活动将被系统自动清除。"

[level.BrontoByte]
level_id = 10
level = "BrontoByte"
days = 32
uploaded = "0"
downloaded = "3.5TB"
bonus = 0.0
score = 0
ratio = 5.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "此等级及以上等级用户会永远保留账号。"

[level.NonaByte]
level_id = 11
level = "NonaByte"
days = 48
uploaded = "50TB"
downloaded = "5TB"
bonus = 0.0
score = 0
ratio = 6.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "无"

[level.DoggaByte]
level_id = 12
level = "DoggaByte"
days = 48
uploaded = "100TB"
downloaded = "10TB"
bonus = 0.0
score = 0
ratio = 6.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "无"

[level.VIP]
level_id = 0
level = "VIP"
days = 0
uploaded = "0"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 0.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "为TTG做出特殊重大贡献的用户或合作者等。只计算上传量，不计算下载量。"
