url = ["https://hhanclub.top/", "https://hhan.club/", ]
name = "憨憨"
nickname = "憨憨"
logo = "favicon.ico"
tracker = "tracker.hhan.club|hhanclub.top|tracker.hhanclub.top|hhan.club"
sp_full = 50
limit_speed = 95
tags = "影视"
iyuu = 72
sign_in = true
get_info = true
repeat_torrents = true
brush_free = true
brush_rss = true
hr_discern = false
search_torrents = true
page_index = "index.php"
page_torrents = "torrents.php?incldead=1"
page_sign_in = "attendance.php"
page_control_panel = "usercp.php"
page_detail = "details.php?id={}"
page_download = "download.php?id={}&passkey={}"
page_user = "userdetails.php?id={}"
page_search = "torrents.php?search={}"
page_message = "messages.php"
page_hr = "myhr.php?hrtype=1&userid={}"
page_leeching = "getusertorrentlistajax.php?userid={}&type=leeching"
page_uploaded = "getusertorrentlistajax.php?userid={}&type=uploaded"
page_seeding = "getusertorrentlistajax.php?userid={}&type=seeding"
page_completed = "getusertorrentlistajax.php?userid={}&type=completed"
page_mybonus = "mybonus.php"
page_viewfilelist = "viewfilelist.php?id={}"
sign_info_title = "//div/p[@class='register-info']/text()"
sign_info_content = "//div/p[@class='register-now-info register-info']/text()"
hr = false
hr_rate = 2
hr_time = 10
my_invitation_rule = "//a[contains(@href,'invite.php?id=')]/text()[1]"
my_time_join_rule = "//span[contains(text(),'加入')]/following-sibling::span/span/@title"
my_latest_active_rule = "//span[contains(text(),'最近动向')]/following-sibling::span/span/@title"
my_uploaded_rule = "//img[@alt='上传']/following-sibling::text()[1]"
my_downloaded_rule = "//img[@alt='下载']/following-sibling::text()[1]"
my_ratio_rule = "//img[@alt='分享率'][1]/following-sibling::div/text()[1]"
my_bonus_rule = "//a[@href='mybonus.php']/div/text()[1]"
my_per_hour_bonus_rule = "//h1[contains(text(),'每小时获得的合计憨豆')]/following-sibling::div/div[2]/div[8]/text()"
my_score_rule = "//span[contains(text(),'做种')]/following-sibling::span/text()"
my_level_rule = "//div[@class='!text-base']/div/a[contains(@class,'_Name') and contains(@href,'userdetails.php?id=')]/@class"
my_passkey_rule = "//span[contains(text(),'密钥')]/following-sibling::span//text()"
my_uid_rule = "//div[@class='!text-base']/div/a[contains(@class,'_Name') and contains(@href,'userdetails.php?id=')]/@href"
my_hr_rule = "//a[@href='myhr.php']//text()"
my_leech_rule = "//img[@alt='下载数'][1]/following-sibling::text()[1]"
my_publish_rule = "//p/preceding-sibling::b/text()[1]"
my_seed_rule = "//img[@alt='做种数'][1]/following-sibling::text()[1]"
my_seed_vol_rule = "//div/b/following-sibling::text()[1]"
my_mailbox_rule = "//div[@id='display-message-alert']/following-sibling::div[2]/div/div/div/text()"
my_message_title = "//img[contains(@src,'icon-unread.svg')]/parent::div/following-sibling::div/a[1]//text()"
my_notice_rule = "//a[@href='index.php']/font[contains(text(),'条')]/text()[1]"
my_notice_title = "//div/p[@class='truncate max-w-md']"
my_notice_content = "//div/p[@class='truncate max-w-md']/parent::div/following-sibling::div"
torrents_rule = "//*[@id='mainContent']/div/div[2]/div[3]/div"
torrent_title_rule = ".//div/div[1]/a[contains(@href,'details')]/text()"
torrent_subtitle_rule = ".//div/a[contains(@href,'details')]/following::div[1]/div/text()"
torrent_detail_url_rule = ".//div/div[1]/a[contains(@href,'details')]/@href"
torrent_category_rule = ".//img[@alt='类型']/@src"
torrent_poster_rule = ".//table/tr/td[1]/img/@src"
torrent_magnet_url_rule = ".//a[contains(@href, 'download.php?id=')]/@href"
torrent_size_rule = ".//div[@class='torrent-info']/div[1]/text()"
torrent_progress_rule = ".//div[contains(@title,'ing')]/@title"
torrent_hr_rule = ".//table/tr/td/img[@class='hitandrun']/@title"
torrent_sale_rule = ".//span[contains(@class, 'promotion-tag-')]/text()"
torrent_sale_expire_rule = ".//img[contains(@class,'free')]/following-sibling::font/span/@title[1]"
torrent_release_rule = ".//div[@class='torrent-info']/div[2]/span/@title"
torrent_seeders_rule = ".//div[@class='torrent-info']/div[3]/a/text()"
torrent_leechers_rule = ".//div[@class='torrent-info']/div[4]/a/text()"
torrent_completers_rule = ".//td[8]//text()"
detail_title_rule = "//div/a[contains(@href, 'download.php?id=')]/text()"
detail_subtitle_rule = ".//div[contains(text(),'副标题')]/following-sibling::div[1]/text()"
detail_download_url_rule = "//a[@class='index' and contains(@href,'download.php')]/@href"
detail_size_rule = "//b[contains(text(), '大小')]/parent::span/following-sibling::span/text()"
detail_category_rule = "//span[contains(text(), '类型')]/following-sibling::span/text()"
detail_count_files_rule = "//span[contains(text(), '文件数')]/following-sibling::span/text()"
detail_hash_rule = "//span[contains(text(), 'Hash')]/following-sibling::span/text()"
detail_free_rule = "//div/a[contains(@href, 'download.php?id=')]/following-sibling::div/span[contains(@class, 'promotion-tag-')]/text()"
detail_free_expire_rule = "//div/a[contains(@href, 'download.php?id=')]/following-sibling::div/span[contains(@class, 'promotion-tag-')]/@alt"
detail_douban_rule = "//br/following-sibling::text()[contains(.,'◎豆瓣链接')]"
detail_imdb_rule = "//a[@class='faqlink' and starts-with(@href,'https://www.imdb.com/title/')]/@href"
detail_poster_rule = "//td/a/span[contains(text(),'简介')]/../../following-sibling::td//img[1]/@src"
detail_tags_rule = "//td[contains(text(),'标签')]/following-sibling::td//text()"
torrent_tags_rule = ".//span[@class='tag']/text()"
detail_hr_rule = "//h1/img[@class='hitandrun']/@title"
alive = true
page_pieces_hash_api = "npapi/pieces-hash"
pieces_repeat = false
proxy = true
imdb_search = "torrents.php?search_area=4&search={}"
structure = "HHan"

[level.User]
level_id = 1
level = "User"
days = 0
uploaded = "0"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 0.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "新用户的默认级别。"

[level.PowerUser]
level_id = 2
level = "PowerUser"
days = 4
uploaded = "0"
downloaded = "50GB"
bonus = 0.0
score = 80000
ratio = 1.05
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "得到一个邀请名额；可以直接发布种子；可以查看NFO文档；可以查看用户列表；可以请求续种；可以发送邀请；可以查看排行榜；可以查看其它用户的种子历史(如果用户隐私等级未设置为'强')；可以删除自己上传的字幕。"

[level.EliteUser]
level_id = 3
level = "EliteUser"
days = 8
uploaded = "0"
downloaded = "120GB"
bonus = 0.0
score = 150000
ratio = 1.55
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "EliteUserxa0及以上用户封存账号后不会被删除。"

[level.CrazyUser]
level_id = 4
level = "CrazyUser"
days = 15
uploaded = "0"
downloaded = "300GB"
bonus = 0.0
score = 300000
ratio = 2.05
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "得到两个邀请名额；可以在做种/下载/发布的时候选择匿名模式。"

[level.InsaneUser]
level_id = 5
level = "InsaneUser"
days = 25
uploaded = "0"
downloaded = "500GB"
bonus = 0.0
score = 500000
ratio = 2.55
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "可以查看普通日志。"

[level.VeteranUser]
level_id = 6
level = "VeteranUser"
days = 40
uploaded = "0"
downloaded = "750GB"
bonus = 0.0
score = 900000
ratio = 3.05
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "得到三个邀请名额；可以查看其它用户的评论、帖子历史。VeteranUserxa0及以上用户会永远保留账号。"

[level.ExtremeUser]
level_id = 7
level = "ExtremeUser"
days = 60
uploaded = "0"
downloaded = "1TB"
bonus = 0.0
score = 1100000
ratio = 3.55
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "可以更新过期的外部信息；可以查看ExtremeUser论坛。"

[level.UltimateUser]
level_id = 8
level = "UltimateUser"
days = 80
uploaded = "0"
downloaded = "1636GB"
bonus = 0.0
score = 1300000
ratio = 4.05
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "得到五个邀请名额。"

[level.NexusMaster]
level_id = 9
level = "NexusMaster"
days = 100
uploaded = "0"
downloaded = "3TB"
bonus = 0.0
score = 1500000
ratio = 4.55
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "得到十个邀请名额。"

[level.VIP]
level_id = 0
level = "VIP"
days = 0
uploaded = "0"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 0.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "和NexusMaster拥有相同权限并被认为是精英成员。免除自动降级。"
