url = ["https://www.pttime.org/", "https://www.pttime.top/", ]
name = "时间"
nickname = "pttime"
logo = "favicon.ico"
tracker = "www.pttime.top|www.pttime.org"
sp_full = 150
limit_speed = 95
tags = "影视"
iyuu = 60
sign_in = true
get_info = true
repeat_torrents = true
brush_free = true
brush_rss = true
hr_discern = false
search_torrents = true
page_index = "index.php"
page_torrents = "torrents.php?incldead=1"
page_sign_in = "attendance.php"
page_control_panel = "usercp.php"
page_detail = "details.php?id={}"
page_download = "download.php?id={}&passkey={}"
page_user = "userdetails.php?id={}"
page_search = "torrents.php?search={}"
page_message = "messages.php"
page_hr = "myhr.php?hrtype=1&userid={}"
page_leeching = "getusertorrentlistajax.php?userid={}&type=leeching"
page_uploaded = "getusertorrentlistajax.php?userid={}&type=uploaded"
page_seeding = "getusertorrentlist.php?type=seeding&userid={}"
page_completed = "getusertorrentlistajax.php?userid={}&type=completed"
page_mybonus = "mybonus.php"
page_viewfilelist = "viewfilelist.php?id="
sign_info_title = "//td[1]/b[1]/text()"
sign_info_content = "//td[@class='embedded']/br[1]/following-sibling::span[position()>0 and position() < 5]//text()"
hr = false
hr_rate = 2
hr_time = 10
my_invitation_rule = "//span/a[contains(@href,'invite.php?id=')]/following-sibling::text()[1]"
my_time_join_rule = "//td[contains(text(),'加入')]/following-sibling::td[1]//span/@title"
my_latest_active_rule = "//td[contains(text(),'最近')]/following-sibling::td[1]//span/@title"
my_uploaded_rule = "//font[@class='fcg' and contains(text(),'上传')]/following-sibling::text()"
my_downloaded_rule = "//font[@class='fcr' and contains(text(),'下载')]/following-sibling::text()"
my_ratio_rule = "//font[@class='color_ratio']/following-sibling::text()"
my_bonus_rule = "//a[@href='mybonus.php']/following-sibling::text()[1]"
my_per_hour_bonus_rule = "//div[contains(text(),'每小时')]/text()[1]"
my_score_rule = "//font[@class='color_bonus' and contains(text(),'积分')]/following-sibling::text()[1]"
my_level_rule = "//*[@id='info_block']//tr[1]/td/span/a[1]/@class"
my_passkey_rule = "//td[contains(text(),'秘钥')]/following-sibling::td[1]/span/text()"
my_uid_rule = "//a[contains(@class,'_Name') and contains(@href,'userdetails.php?id=')]/@href"
my_hr_rule = "//a[@href='myhr.php']//text()"
my_leech_rule = "//font[@title='当前下载']/following-sibling::text()[1]"
my_publish_rule = "//p/preceding-sibling::b/text()[1]"
my_seed_rule = "//font[@title='当前做种']/following-sibling::text()[1]"
my_seed_vol_rule = "//b[contains(text(),'资源总大小：')]/following-sibling::text()[1]"
my_mailbox_rule = "//a[@href='messages.php']/font[contains(text(),'条')]/text()[1]"
my_message_title = "//img[@alt='Unread']/parent::div/following-sibling::a[1]/div/text()"
my_notice_rule = "//a[@href='index.php']/font[contains(text(),'条')]/text()[1]"
my_notice_title = "//td[@class='text']/div/a"
my_notice_content = "//td[@class='text']/div/a/following-sibling::div"
torrents_rule = "//table[@class='torrents']/tr/td[not(contains(@class,'colhead'))]/parent::tr"
torrent_title_rule = ".//tr/td[@class='embedded'][1]/a/b/text()"
torrent_subtitle_rule = ".//tr/td[@class='embedded'][1]/font[last()]/text()"
torrent_detail_url_rule = ".//td[@class='embedded']/a[contains(@href,'detail')]/b/parent::a/@href"
torrent_category_rule = ".//td[@class='rowfollow nowrap'][1]/a[1]/img/@alt"
torrent_poster_rule = ".//table/tr/td[1]/img/@src"
torrent_magnet_url_rule = ".//a[contains(@href,'download')]/@href"
torrent_size_rule = ".//td[6]/text()"
torrent_progress_rule = ".//div[contains(@title,'ing')]/@title"
torrent_hr_rule = ".//table/tr/td/img[@class='hitandrun']/@title"
torrent_sale_rule = ".//font[contains(@class,'promotion')][1]/text()"
torrent_sale_expire_rule = ".//font[contains(@class,'free')]/following-sibling::span[1]/@title"
torrent_release_rule = ".//td[@class='rowfollow nowrap']/span/@title"
torrent_seeders_rule = ".//a[contains(@href,'#seeders')]//text()"
torrent_leechers_rule = ".//a[contains(@href,'#leechers')]//text()"
torrent_completers_rule = ".//a[contains(@href,'viewsnatches')]//text()"
detail_title_rule = "//h1/text()[1]"
detail_subtitle_rule = "//td[contains(text(),'副标题')]/following-sibling::td/text()[1]"
detail_download_url_rule = "//a[@class='index' and contains(@href,'download.php')]/@href"
detail_size_rule = "//td//b[contains(text(),'大小')]/following::text()[1]"
detail_category_rule = "//td/b[contains(text(),'类型')]/following-sibling::text()[1]"
detail_count_files_rule = "//td/b[contains(text(),'文件数')]/following-sibling::text()[1]"
detail_hash_rule = "//td/b[contains(text(),'Hash')]/following-sibling::text()[1]"
detail_free_rule = "//h1/b/font/@class"
detail_free_expire_rule = "//h1/b/span/@title"
detail_douban_rule = "//td/a[starts-with(@href,'https://movie.douban.com/subject/')][1]"
detail_imdb_rule = "//a[@class='faqlink' and starts-with(@href,'https://www.imdb.com/title/')]/@href"
detail_poster_rule = "//td/a/span[contains(text(),'简介')]/../../following-sibling::td//img[1]/@src"
detail_tags_rule = "//td[contains(text(),'标签')]/following-sibling::td//text()"
torrent_tags_rule = ".//a[contains(@href,'detail')]/../span[contains(@class,'tags')]/text()"
detail_hr_rule = "//h1/img[@class='hitandrun']/@title"
alive = true
page_pieces_hash_api = "api/pieces-hash"
pieces_repeat = false
proxy = false
imdb_search = "torrents.php?search_area=3&search={}"

[level.User]
level_id = 1
level = "User"
days = 0
uploaded = "0"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 0.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "如果下载量低于100G，不参与账户升级或降级。也就是将一直保持User级，该规则一直存在，只是最近才在代码中发现。"

[level.PowerUser]
level_id = 2
level = "PowerUser"
days = 4
uploaded = "0"
downloaded = "512GB"
bonus = 0.0
score = 0
ratio = 1.05
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "(小学)PowerUser及以上等级。首次升级至此等级的用户将获得2个邀请名额。"

[level.EliteUser]
level_id = 3
level = "EliteUser"
days = 8
uploaded = "0"
downloaded = "1024GB"
bonus = 0.0
score = 0
ratio = 1.55
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "首次升级至此等级的用户将获得2个邀请名额。"

[level.CrazyUser]
level_id = 4
level = "CrazyUser"
days = 15
uploaded = "0"
downloaded = "2048GB"
bonus = 0.0
score = 0
ratio = 2.05
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "(高中)CrazyUser封存后永远保留。首次升级至此等级的用户将获得2个邀请名额。"

[level.InsaneUser]
level_id = 5
level = "InsaneUser"
days = 25
uploaded = "0"
downloaded = "4096GB"
bonus = 0.0
score = 0
ratio = 2.55
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "首次升级至此等级的用户将获得2个邀请名额。"

[level.VeteranUser]
level_id = 6
level = "VeteranUser"
days = 40
uploaded = "0"
downloaded = "8192GB"
bonus = 0.0
score = 0
ratio = 3.05
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "首次升级至此等级的用户将获得2个邀请名额。"

[level.ExtremeUser]
level_id = 7
level = "ExtremeUser"
days = 60
uploaded = "0"
downloaded = "16384GB"
bonus = 0.0
score = 0
ratio = 3.55
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "永远保留(研究生)ExtremeUser账号。首次升级至此等级的用户将获得2个邀请名额。"

[level.UltimateUser]
level_id = 8
level = "UltimateUser"
days = 80
uploaded = "0"
downloaded = "35000GB"
bonus = 0.0
score = 0
ratio = 4.05
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "首次升级至此等级的用户将获得5个邀请名额。"

[level.NexusMaster]
level_id = 9
level = "NexusMaster"
days = 100
uploaded = "0"
downloaded = "70000GB"
bonus = 0.0
score = 0
ratio = 4.55
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "首次升级至此等级的用户将获得10个邀请名额。"

[level.VIP]
level_id = 0
level = "VIP"
days = 0
uploaded = "0"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 0.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "1、永久贵宾无数据要求：分享率、下载量、上传量等。2、直接过新手考核，可直接过其他临时考核。3、力所能及的PT相关技术支持、及其他技术支持。"
