url = ["https://star-space.net/", ]
name = "星空"
nickname = "star-space"
logo = "favicon.ico"
tracker = "https://star-space.net/announce.php"
sp_full = 300
limit_speed = 100
tags = "影视"
iyuu = 91
sign_in = false
get_info = true
repeat_torrents = true
brush_free = true
brush_rss = true
hr_discern = true
search_torrents = true
page_index = "p_index/index.php"
page_torrents = "p_torrent/video_list_g.php"
page_sign_in = "attendance.php"
page_control_panel = "usercp.php"
page_detail = "p_torrent/video_detail.php?tid={}"
page_download = "download.php?id={}&passkey={}"
page_user = "p_user/user_detail.php?uid={}"
page_search = "p_torrent/video_list_g.php?option=&search={}&area=name&column=g_last_upload_date&sort=desc"
imdb_search = "p_torrent/video_list_g.php?seeder=&source=&cat=&search={}&area=imdb&column=tr_create_time&sort=desc&btn_search=搜索&suggest="
page_message = "p_sms/msg_in.php"
page_hr = "myhr.php?hrtype=1&userid={}"
page_leeching = "p_torrent/video_list_t.php?pop=9&userid={}"
page_uploaded = "getusertorrentlistajax.php?userid={}&type=uploaded"
page_seeding = "p_torrent/torrent_user.php?pop=8&userid={}"
page_completed = "getusertorrentlistajax.php?userid={}&type=completed"
page_mybonus = "p_bonus/bonus_hour.php"
page_viewfilelist = "viewfilelist.php?id={}"
sign_info_title = "//td[@id='outer']//td[@class='embedded']/h2/text()"
sign_info_content = "//td[@id='outer']//td[@class='embedded']/table//td//text()"
hr = false
hr_rate = 2
hr_time = 10
my_invitation_rule = "//td[contains(text(),'邀请名额')]/following-sibling::td/text()"
my_time_join_rule = "//td[contains(text(),'加入')]/following-sibling::td/text()"
my_latest_active_rule = "//td[contains(text(),'最近访问')]/following-sibling::td/text()"
my_uploaded_rule = "//span/a[contains(@href,'user_upload')]/text()"
my_downloaded_rule = "//span[@id='user_info_no_hover']/text()"
my_ratio_rule = "//font[@class='color_ratio'][1]/following-sibling::text()[1]"
my_bonus_rule = "//span/a[contains(text(),'魔力')]/text()"
my_per_hour_bonus_rule = "//td[contains(text(),'合计时魔')]/../td[last()]/text()"
my_score_rule = "//span/a[contains(text(),'积分')]/text()"
my_level_rule = "//td[contains(text(),'用户名称')]/following-sibling::td/a/span/@class"
my_passkey_rule = "//td[contains(text(),'当前Passkey')]/following-sibling::td[1]/text()"
my_uid_rule = "//td[contains(text(),'用户名称')]/following-sibling::td/a/@href"
my_hr_rule = "//a[@href='myhr.php']//text()"
my_leech_rule = "//span/a[contains(@href,'p_torrent/torrent_user.php?pop=9')]/text()"
my_publish_rule = "//p/preceding-sibling::b/text()[1]"
my_seed_rule = "//span/a[contains(@href,'p_torrent/torrent_user.php?pop=8')]/text()"
my_seed_vol_rule = "//tr[@id='tr_list']/td[4]"
my_mailbox_rule = "//a[@href='messages.php']/font[contains(text(),'条')]/text()[1]"
my_message_title = "//img[@alt='Unread']/parent::td/following-sibling::td/a[1]//text()"
my_notice_rule = "//a[@href='index.php']/font[contains(text(),'条')]/text()[1]"
my_notice_title = "//td[@class='text']/div/a//text()"
my_notice_content = "//td[@class='text']/div/a/following-sibling::div"
torrents_rule = "//tr[@id='gm_tr_item']"
torrent_title_rule = "./td/div[@id='gm_div_name']/a/text()"
torrent_subtitle_rule = "./td/div[@id='gm_div_desc']/text()"
torrent_detail_url_rule = "./td/div[@id='gm_div_name']/a/@href"
torrent_category_rule = "./td[1]/table[1]//td[@class='corner_bottom']/text()[1]"
torrent_tags_rule = "./td[@id='gm_td_name']/div/span/text()"
torrent_poster_rule = ".//table/tr/td[1]/img/@src"
torrent_magnet_url_rule = "./td/div[@id='tm_div_ico']/a[last()]/@href"
torrent_size_rule = "./td[@id='gm_td_size']/text()"
torrent_progress_rule = ".//div[contains(@title,'ing')]/@title"
torrent_hr_rule = ".//table/tr/td/img[@class='hitandrun']/@title"
torrent_sale_rule = ".//img[contains(@class,'free')]/@alt"
torrent_sale_expire_rule = ".//img[contains(@class,'free')]/following-sibling::font/span/@title"
torrent_release_rule = "./td[@id='gm_td_user']/text()"
torrent_seeders_rule = "./td[@id='gm_td_seeder']/a/text()"
torrent_leechers_rule = "./td[@id='gm_td_downloader']/a/text()"
torrent_completers_rule = "./td[@id='gm_td_finish']/a/text()"
detail_title_rule = "//h1/text()[1]"
detail_subtitle_rule = "//td[contains(text(),'副标题')]/following-sibling::td/text()[1]"
detail_download_url_rule = "//a[@class='index' and contains(@href,'download.php')]/@href"
detail_size_rule = "//td//b[contains(text(),'大小')]/following::text()[1]"
detail_category_rule = "//td/b[contains(text(),'类型')]/following-sibling::text()[1]"
detail_count_files_rule = "//td/b[contains(text(),'文件数')]/following-sibling::text()[1]"
detail_hash_rule = "//td/b[contains(text(),'Hash')]/following-sibling::text()[1]"
detail_free_rule = "//h1/b/font/@class"
detail_free_expire_rule = "//h1/b/span/@title"
detail_douban_rule = "//td/a[starts-with(@href,'https://movie.douban.com/subject/')][1]"
detail_imdb_rule = "//a[@class='faqlink' and starts-with(@href,'https://www.imdb.com/title/')]/@href"
detail_poster_rule = "//td/a/span[contains(text(),'简介')]/../../following-sibling::td//img[1]/@src"
detail_tags_rule = "//td[contains(text(),'标签')]/following-sibling::td//text()"
detail_hr_rule = "//h1/img[@class='hitandrun']/@title"
alive = true
page_pieces_hash_api = "api/pieces-hash"
pieces_repeat = false
proxy = true
structure = "StarSpace"
