url = ["https://star-space.net/", ]
name = "星空"
nickname = "shadow"
logo = "favicon.ico"
tracker = "https://star-space.net/announce.php"
sp_full = 300
limit_speed = 100
tags = "影视"
iyuu = 91
sign_in = true
get_info = true
repeat_torrents = true
brush_free = true
brush_rss = true
hr_discern = true
search_torrents = true
page_index = "index.php"
page_torrents = "p_torrent/video_list_h.php"
page_sign_in = "attendance.php"
page_control_panel = "usercp.php"
page_detail = "details.php?id={}"
page_download = "download.php?id={}&passkey={}"
page_user = "p_user/user_detail.php?uid={}"
page_search = "p_torrent/video_list_g.php?search={}&area=name&column=g_last_upload_date&sort=desc"
page_message = "p_sms/msg_in.php"
page_hr = "myhr.php?hrtype=1&userid={}"
page_leeching = "p_torrent/video_list_t.php?area=leeching&userid={}"
page_uploaded = "getusertorrentlistajax.php?userid={}&type=uploaded"
page_seeding = "p_torrent/video_list_t.php?area=seeding&userid={}"
page_completed = "getusertorrentlistajax.php?userid={}&type=completed"
page_mybonus = "p_bonus/bonus_hour.php"
page_viewfilelist = "viewfilelist.php?id={}"
sign_info_title = "//td[@id='outer']//td[@class='embedded']/h2/text()"
sign_info_content = "//td[@id='outer']//td[@class='embedded']/table//td//text()"
hr = false
hr_rate = 2
hr_time = 10
my_invitation_rule = "//td[contains(text(),'邀请名额')]/following-sibling::td/text()"
my_time_join_rule = "//td[contains(text(),'加入')]/following-sibling::td/text()"
my_latest_active_rule = "//td[contains(text(),'最近访问')]/following-sibling::td/text()"
my_uploaded_rule = "//span/a[contains(@href,'user_upload')]/text()"
my_downloaded_rule = "//span[@id='user_info_no_hover']/text()"
my_ratio_rule = "//font[@class='color_ratio'][1]/following-sibling::text()[1]"
my_bonus_rule = "//span/a[contains(text(),'魔力')]/text()"
my_per_hour_bonus_rule = "//tr[@id='tr_list'][last()]/td[last()]/text()"
my_score_rule = "//span/a[contains(text(),'积分')]/text()"
my_level_rule = "//td[contains(text(),'用户名称')]/following-sibling::td/a/span/@class"
my_passkey_rule = "//td[contains(text(),'密钥')]/following-sibling::td[1]/text()"
my_uid_rule = "//td[contains(text(),'用户名称')]/following-sibling::td/a/@href"
my_hr_rule = "//a[@href='myhr.php']//text()"
my_leech_rule = "//span/a[contains(@href,'area=leeching')]/text()"
my_publish_rule = "//p/preceding-sibling::b/text()[1]"
my_seed_rule = "//span/a[contains(@href,'area=seeding')]/text()"
my_seed_vol_rule = "//td[@id='tm_td_size']"
my_mailbox_rule = "//a[@href='messages.php']/font[contains(text(),'条')]/text()[1]"
my_message_title = "//img[@alt='Unread']/parent::td/following-sibling::td/a[1]//text()"
my_notice_rule = "//a[@href='index.php']/font[contains(text(),'条')]/text()[1]"
my_notice_title = "//td[@class='text']/div/a//text()"
my_notice_content = "//td[@class='text']/div/a/following-sibling::div"
torrents_rule = "//table[@class='torrents']/tr"
torrent_title_rule = ".//td[@class='embedded']/a/b/text()"
torrent_subtitle_rule = ".//a[contains(@href,'detail')]/parent::td/text()[last()]"
torrent_detail_url_rule = ".//td[@class='embedded']/a[contains(@href,'detail')]/@href"
torrent_category_rule = ".//td[@class='rowfollow nowrap'][1]/a[1]/img/@title"
torrent_poster_rule = ".//table/tr/td[1]/img/@src"
torrent_magnet_url_rule = ".//td/a[contains(@href,'download.php?id=')]/@href"
torrent_size_rule = ".//td[5]/text()"
torrent_progress_rule = ".//div[contains(@title,'ing')]/@title"
torrent_hr_rule = ".//table/tr/td/img[@class='hitandrun']/@title"
torrent_sale_rule = ".//img[contains(@class,'free')]/@alt"
torrent_sale_expire_rule = ".//img[contains(@class,'free')]/following-sibling::font/span/@title"
torrent_release_rule = ".//td[4]/span/@title"
torrent_seeders_rule = ".//a[contains(@href,'#seeders')]/text()"
torrent_leechers_rule = ".//a[contains(@href,'#leechers')]/text()"
torrent_completers_rule = ".//a[contains(@href,'viewsnatches')]//text()"
detail_title_rule = "//h1/text()[1]"
detail_subtitle_rule = "//td[contains(text(),'副标题')]/following-sibling::td/text()[1]"
detail_download_url_rule = "//a[@class='index' and contains(@href,'download.php')]/@href"
detail_size_rule = "//td//b[contains(text(),'大小')]/following::text()[1]"
detail_category_rule = "//td/b[contains(text(),'类型')]/following-sibling::text()[1]"
detail_count_files_rule = "//td/b[contains(text(),'文件数')]/following-sibling::text()[1]"
detail_hash_rule = "//td/b[contains(text(),'Hash')]/following-sibling::text()[1]"
detail_free_rule = "//h1/b/font/@class"
detail_free_expire_rule = "//h1/b/span/@title"
detail_douban_rule = "//td/a[starts-with(@href,'https://movie.douban.com/subject/')][1]"
detail_imdb_rule = "//a[@class='faqlink' and starts-with(@href,'https://www.imdb.com/title/')]/@href"
detail_poster_rule = "//td/a/span[contains(text(),'简介')]/../../following-sibling::td//img[1]/@src"
detail_tags_rule = "//td[contains(text(),'标签')]/following-sibling::td//text()"
torrent_tags_rule = ".//a[contains(@href,'detail')]/../span[contains(@class,'tags')]/text()"
detail_hr_rule = "//h1/img[@class='hitandrun']/@title"
alive = true
page_pieces_hash_api = "api/pieces-hash"
pieces_repeat = false
proxy = true
