url = [ "https://dicmusic.com/",]
name = "海豚"
nickname = "dicmusic"
logo = "favicon.ico"
tracker = "tracker.52dic.vip"
sp_full = 100
limit_speed = 100
tags = "音乐"
iyuu = 51
sign_in = false
get_info = true
repeat_torrents = true
brush_free = true
brush_rss = true
hr_discern = false
search_torrents = true
page_index = "index.php"
page_torrents = "torrents.php"
page_sign_in = "attendance.php"
page_control_panel = "usercp.php"
page_detail = "torrents.php?torrentid={}"
page_download = "torrents.php?action=download&id={}&&authkey={}&torrent_pass={}"
page_user = "ajax.php?action=user&id={}"
page_search = "torrents.php?searchstr={}"
page_message = "inbox.php"
page_hr = "myhr.php?hrtype=1&userid={}"
page_leeching = "getusertorrentlistajax.php?userid={}&type=leeching"
page_uploaded = "getusertorrentlistajax.php?userid={}&type=uploaded"
page_seeding = "bonus.php?action=bprates"
page_completed = "getusertorrentlistajax.php?userid={}&type=completed"
page_mybonus = "ajax.php?action=index"
page_viewfilelist = "viewfilelist.php?id={}"
sign_info_title = "//td[@id='outer']//td[@class='embedded']/h2/text()"
sign_info_content = "//td[@id='outer']//td[@class='embedded']/table//td//text()"
hr = false
hr_rate = 2
hr_time = 10
my_invitation_rule = "//span/a[contains(@href,'invite.php?id=')]/following-sibling::text()[1]"
my_time_join_rule = "//td[contains(text(),'加入')]/following-sibling::td/span/@title"
my_latest_active_rule = "//td[contains(text(),'最近动向')]/following-sibling::td/span/@title"
my_uploaded_rule = "//font[@class='color_uploaded']/following-sibling::text()[1]"
my_downloaded_rule = "//font[@class='color_downloaded']/following-sibling::text()[1]"
my_ratio_rule = "//font[@class='color_ratio'][1]/following-sibling::text()[1]"
my_bonus_rule = "//a[@href='mybonus.php']/following-sibling::text()[1]"
my_per_hour_bonus_rule = "//div[contains(text(),'每小时能获取')]/text()[1]"
my_score_rule = "//font[@class='color_bonus' and contains(text(),'积分')]/following-sibling::text()[1]"
my_level_rule = "//table[@id='info_block']//span/a[contains(@class,'_Name') and contains(@href,'userdetails.php?id=')]/@class"
my_passkey_rule = "//td[contains(text(),'密钥')]/following-sibling::td[1]/text()"
my_uid_rule = "//a[contains(@href,'user.php?id=')]/@href"
my_hr_rule = "//a[@href='myhr.php']//text()"
my_leech_rule = "//img[@class='arrowdown']/following-sibling::text()[1]"
my_publish_rule = "//p/preceding-sibling::b/text()[1]"
my_seed_rule = "//img[@class='arrowup']/following-sibling::text()[1]"
my_seed_vol_rule = "//tr/td[3]"
my_mailbox_rule = "//a[@href='messages.php']/font[contains(text(),'条')]/text()[1]"
my_message_title = "//img[@alt='Unread']/parent::td/following-sibling::td/a[1]//text()"
my_notice_rule = "//a[@href='index.php']/font[contains(text(),'条')]/text()[1]"
my_notice_title = "//td[@class='text']/div/a"
my_notice_content = "//td[@class='text']/div/a/following-sibling::div"
torrents_rule = "//tr[@class='torrent']"
torrent_title_rule = "./td/div[contains(@class, 'group_info')]/a/text()"
torrent_subtitle_rule = "./td/div[contains(@class, 'group_info')]/div[@class='torrent_info']/text()"
torrent_detail_url_rule = "./td/div[contains(@class, 'group_info')]/a[2]/@href"
torrent_category_rule = ".//td/div[contains(@class, 'group_info')]/a[2]/following-sibling::text()[1]"
torrent_poster_rule = "./td/div/img/@src"
torrent_magnet_url_rule = "./td/div[contains(@class, 'group_info')]/span/a[1]/@href"
torrent_size_rule = "./td[contains(@class, 'td_size')]/text()"
torrent_progress_rule = ".//div[contains(@title,'ing')]/@title"
torrent_hr_rule = "./table/tr/td/img[@class='hitandrun']/@title"
torrent_sale_rule = "./td/div/div[contains(@class, 'torrent_info')]/strong[contains(@class,'tl_free')]/text()"
torrent_sale_expire_rule = "./td/div/a/span/span[contains(@class,'free ')]/@data-tooltip"
torrent_release_rule = "./td[contains(@class, 'td_time')]/span/text()"
torrent_seeders_rule = "./td[contains(@class, 'td_seeders')]/text()"
torrent_leechers_rule = "./td[contains(@class, 'td_leechers')]/text()"
torrent_completers_rule = "./td[contains(@class, 'td_snatched')]/text()"
detail_title_rule = "//h1/text()[1]"
detail_subtitle_rule = "//td[contains(text(),'副标题')]/following-sibling::td/text()[1]"
detail_download_url_rule = "//a[@class='index' and contains(@href,'download.php')]/@href"
detail_size_rule = "//td//b[contains(text(),'大小')]/following::text()[1]"
detail_category_rule = "//td/b[contains(text(),'类型')]/following-sibling::text()[1]"
detail_count_files_rule = "//td/b[contains(text(),'文件数')]/following-sibling::text()[1]"
detail_hash_rule = "//td/b[contains(text(),'Hash')]/following-sibling::text()[1]"
detail_free_rule = "//h1/b/font/@class"
detail_free_expire_rule = "//h1/b/span/@title"
detail_douban_rule = "//td/a[starts-with(@href,'https://movie.douban.com/subject/')][1]"
detail_imdb_rule = "//a[@class='faqlink' and starts-with(@href,'https://www.imdb.com/title/')]/@href"
detail_poster_rule = "//td/a/span[contains(text(),'简介')]/../../following-sibling::td//img[1]/@src"
detail_tags_rule = "//td[contains(text(),'标签')]/following-sibling::td//text()"
torrent_tags_rule = "//td/div/a/span/span[contains(@class,'TorrentTitle-item ')]/text()"
detail_hr_rule = "//h1/img[@class='hitandrun']/@title"
alive = true
page_pieces_hash_api = "api/pieces-hash"
pieces_repeat = false
proxy = true

[level.User]
level_id = 1
level = "User"
days = 0
uploaded = "0"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 0.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "所有新用户的默认等级\n能够使用RSS订阅系统\n具有论坛「茶话会」版块的阅读权限"

[level.Member]
level_id = 2
level = "Member"
days = 1
uploaded = "0"
downloaded = "80GB"
bonus = 0.0
score = 0
ratio = 0.8
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "享有低级别所有权限\n能够发起求种\n能够查看部分排行榜\n能够完全访问「茶话会」版块"

[level.PowerUser]
level_id = 3
level = "PowerUser"
days = 2
uploaded = "0"
downloaded = "200GB"
bonus = 1.0
score = 0
ratio = 1.2
torrents = 1
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "享有低级别所有权限\n能够发送邀请，首次升级赠送1枚永久邀请\n发邀至少间隔1周\n能够佩戴1枚印记\n能够创建1个私人合集\n能够访问论坛的「求邀区」「发邀区」「PowerUser」版块\n能够完全访问排行榜\n免疫账号不活跃（保号）"

[level.Elite]
level_id = 4
level = "Elite"
days = 4
uploaded = "0"
downloaded = "500GB"
bonus = 25.0
score = 0
ratio = 1.2
torrents = 25
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "享有低级别所有权限\n首次升级赠送1枚永久邀请\n能够佩戴2枚印记\n能够创建2个私人合集\n能够访问论坛的「Elite」版块\n能够检查自己发布的种子\n能够编辑所有种子"

[level.TorrentMaster]
level_id = 5
level = "TorrentMaster"
days = 8
uploaded = "0"
downloaded = "1TB"
bonus = 100.0
score = 0
ratio = 1.2
torrents = 100
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "享有低级别所有权限\n首次升级赠送2枚永久邀请\n每月获赠1枚临时邀请（有效期2周）\n发邀至少间隔72小时\n能够佩戴3枚印记\n能够创建3个私人合集\n能够访问论坛的「TorrentMaster」版块\n能够在商城购买「自定义头衔（不允许BBCode）」"

[level.PowerTorrentMaster]
level_id = 6
level = "PowerTorrentMaster"
days = 12
uploaded = "0"
downloaded = "2TB"
bonus = 250.0
score = 0
ratio = 1.2
torrents = 250
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "享有低级别所有权限\n首次升级赠送2枚永久邀请\n每月获赠2枚临时邀请（有效期2周）\n能够佩戴4枚印记\n能够创建4个私人合集\n能够检查所有种子"

[level.EliteTorrentMaster]
level_id = 7
level = "EliteTorrentMaster"
days = 16
uploaded = "0"
downloaded = "5TB"
bonus = 500.0
score = 0
ratio = 1.2
torrents = 500
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "享有低级别所有权限\n首次升级赠送3枚永久邀请\n每月获赠3枚临时邀请（有效期2周）\n无发邀间隔\n能够佩戴5枚印记\n能够创建5个私人合集\n能够访问论坛的「EliteTorrentMaster」版块\n能够在商城购买「自定义头衔（允许BBCode）」"

[level.Guru]
level_id = 8
level = "Guru"
days = 20
uploaded = "0"
downloaded = "10TB"
bonus = 1000.0
score = 0
ratio = 1.2
torrents = 1000
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "享有低级别所有权限\n拥有无限邀请\n能够佩戴6枚印记\n能够创建6个私人合集\n能够访问论坛的「Guru」版块\n能够查看日志"

[level.VIP]
level_id = 0
level = "VIP"
days = 0
uploaded = "0"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 0.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "对站点做过特殊贡献或特邀会员。由管理人员选出。禁止任何人索要VIP！"
