url = [ "https://hdchina.org/",]
name = "瓷器"
nickname = "hdchina"
logo = "favicon.ico"
tracker = "tracker.hdchina.org"
sp_full = 70
limit_speed = 95
tags = "影视"
iyuu = 28
sign_in = true
get_info = true
repeat_torrents = true
brush_free = true
brush_rss = true
hr_discern = false
search_torrents = true
page_index = "index.php"
page_torrents = "torrents.php?incldead=1"
page_sign_in = "plugin_sign-in.php?cmd=signin"
page_control_panel = "usercp.php"
page_detail = "details.php?id={}&hit=1"
page_download = "download.php?id={}&passkey={}"
page_user = "userdetails.php?id={}"
page_search = "torrents.php?search={}"
page_message = "messages.php"
page_hr = "myhr.php?hrtype=1&userid={}"
page_leeching = "getusertorrentlistajax.php?userid={}&type=leeching"
page_uploaded = "getusertorrentlistajax.php?userid={}&type=uploaded"
page_seeding = "ajax_getusertorrentlist.php"
page_completed = "getusertorrentlistajax.php?userid={}&type=completed"
page_mybonus = "mybonus.php"
page_viewfilelist = "viewfilelist.php?id={}"
sign_info_title = "//td[@id=\"outer\"]//td[@class=\"embedded\"]/h2/text()"
sign_info_content = "//td[@id=\"outer\"]//td[@class=\"embedded\"]/table//td//text()"
hr = false
hr_rate = 2
hr_time = 10
my_invitation_rule = "//p/a[contains(@href,\"invite.php?id=\")]/following-sibling::text()[1]"
my_time_join_rule = "//td[contains(text(),\"加入\")]/following-sibling::td/span/@title"
my_latest_active_rule = "//td[text()=\" 最近动向\"]/following-sibling::td/span/@title[1]"
my_uploaded_rule = "//strong[contains(text(),\"上传量\")]/following-sibling::text()"
my_downloaded_rule = "//strong[contains(text(),\"下载量\")]/following-sibling::text()"
my_ratio_rule = "//strong[contains(text(),\"分享率\")]/following-sibling::font[1]/text()"
my_bonus_rule = "//a[contains(@href,\"mybonus.php\")]/following-sibling::text()[1]"
my_per_hour_bonus_rule = "//div/h3[contains(text(),\"每小时\")]/text()[1]"
my_score_rule = "//font[@class=\"color_bonus\" and contains(text(),\"积分\")]/following-sibling::text()[1]"
my_level_rule = "//p/span/a[contains(@class,\"_Name\") and contains(@href,\"userdetails.php?id=\")]/@class"
my_passkey_rule = "//td[contains(text(),\"密钥\")]/following-sibling::td[1]/text()"
my_uid_rule = "//p/span/a[contains(@class,\"_Name\") and contains(@href,\"userdetails.php?id=\")]/@href"
my_hr_rule = "//a[@href=\"myhr.php\"]//text()"
my_leech_rule = "//i[@title=\"当前下载\"][1]/following-sibling::text()[1]"
my_publish_rule = "//p/preceding-sibling::b/text()[1]"
my_seed_rule = "//i[@title=\"当前做种\"][1]/following-sibling::text()[1]"
my_seed_vol_rule = "//tr/td[3]"
my_mailbox_rule = "//a[@href=\"messages.php\"]/font[contains(text(),\"条\")]/text()[1]"
my_message_title = "//img[@alt=\"Unread\"]/parent::td/following-sibling::td/a[1]//text()"
my_notice_rule = "//a[@href=\"index.php\"]/font[contains(text(),\"条\")]/text()[1]"
my_notice_title = "//div[@class=\"announcebox\"]/div/h4"
my_notice_content = "//div[@class=\"announcebox\"]/div/h4/following-sibling::h3"
torrents_rule = "//table[@class=\"torrent_list\"]/tr[not(contains(@class, \"tab_header\"))]"
torrent_title_rule = ".//h3/a[contains(@href,\"details.php\")]/text()"
torrent_subtitle_rule = ".//h4/text()"
torrent_detail_url_rule = ".//h3/a[contains(@href,\"details.php\")]/@href"
torrent_category_rule = ".//td[1]/a/img/@alt"
torrent_poster_rule = ".//table/tr/td[1]/img/@src"
torrent_magnet_url_rule = ".//td/a[contains(@href,\"download.php?hash\")]/@href"
torrent_size_rule = ".//td[5]/text()"
torrent_hr_rule = ".//table/tr/td/img[@class=\"hitandrun\"]/@title"
torrent_sale_rule = ".//img[contains(@class,\"pro_\")]/@alt"
torrent_sale_expire_rule = ".//img[contains(@class,\"free\")]/../following-sibling::span/@title"
torrent_release_rule = ".//td[4]/span/@title"
torrent_seeders_rule = ".//a[contains(@href,\"#seeders\")]/text()"
torrent_leechers_rule = ".//a[contains(@href,\"#leechers\")]/text()"
torrent_completers_rule = ".//a[contains(@href,\"viewsnatches\")]//text()"
detail_title_rule = "//div[@class=\"m_name\"]/h2/text()[1]"
detail_subtitle_rule = "//div[@class=\"m_name\"]/h3/text()[1]"
detail_download_url_rule = "//a[contains(@href,\"download.php?hash\") and @title=\"下载种子\"]/@href"
detail_size_rule = "//td//b[contains(text(),\"大小\")]/following::text()[1]"
detail_category_rule = "//b[contains(text(),\"类型\")]/following-sibling::text()[1]"
detail_count_files_rule = "//td/b[contains(text(),\"文件数\")]/following-sibling::text()[1]"
detail_hash_rule = "//td/b[contains(text(),\"Hash\")]/following-sibling::text()[1]"
detail_free_rule = ".//img[contains(@class,\"pro_\")]/@alt"
detail_free_expire_rule = ".//img[contains(@class,\"pro_\")]/@onmouseover"
detail_douban_rule = "//td/a[starts-with(@href,\"https://movie.douban.com/subject/\")][1]"
detail_imdb_rule = "//text()[contains(.,\"◎IMDb 链接\")]/following-sibling::a[@class=\"faqlink\" and starts-with(@href,\"https://www.imdb.com/title/\")]/@hr"
detail_poster_rule = "//td/div[@class=\"imgbox\"]/img[1]/@src"
detail_tags_rule = "//td[contains(text(),\"标签\")]/following-sibling::td//text()"
torrent_tags_rule = ".//a[contains(@href,\"detail\")]/../span[contains(@class,\"tags\")]/text()"
detail_hr_rule = "//h1/img[@class=\"hitandrun\"]/@title"
alive = true
page_pieces_hash_api = "api/pieces-hash"
pieces_repeat = false
proxy = true

[level.User]
level_id = 1
level = "User"
days = 0
uploaded = "0"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 0.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "默认的新用户等级。无法提交种子候选，无法对候选投票，无法使用道具，无法打开签名和个性化称号，不能直接发种，不能查看排行榜，处于熟悉规则学习阶段。"

[level.PowerUser]
level_id = 2
level = "PowerUser"
days = 5
uploaded = "0"
downloaded = "200GB"
bonus = 0.0
score = 0
ratio = 1.5
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "享有群众演员(User)的所有权限，可以使用道具，可以打开签名和个性化称号，不能直接发种(暂时下调至PU)，不能查看排行榜。"

[level.EliteUser]
level_id = 3
level = "EliteUser"
days = 10
uploaded = "0"
downloaded = "500GB"
bonus = 0.0
score = 0
ratio = 2.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "享有龙套(PowerUser)的所有权限，可以在候选区投票，可以在论坛建议区发帖，可以上传字幕，可以删除自己上传的字幕。"

[level.CrazyUser]
level_id = 4
level = "CrazyUser"
days = 15
uploaded = "0"
downloaded = "1TB"
bonus = 0.0
score = 0
ratio = 2.5
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "享有主演(EliteUser)的所有权限，可以查看排行榜，可以使用挂起功能，可在种子区观看到当前下载活动进度条，可以查看当前自己在全站中的流量排名，可以进入邀请区。"

[level.InsaneUser]
level_id = 5
level = "InsaneUser"
days = 20
uploaded = "0"
downloaded = "1.5TB"
bonus = 0.0
score = 0
ratio = 3.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "享有大腕(CrazyUser)的所有权限，并可以直接发布种子，无需候选。"

[level.VeteranUser]
level_id = 6
level = "VeteranUser"
days = 25
uploaded = "0"
downloaded = "2TB"
bonus = 0.0
score = 0
ratio = 4.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "享有经纪人(InsaneUser)的所有权限，可以在个人资料内隐藏个人信息，可以匿名做种。"

[level.ExtremeUser]
level_id = 7
level = "ExtremeUser"
days = 30
uploaded = "0"
downloaded = "3TB"
bonus = 0.0
score = 0
ratio = 5.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "享有导演(VeteranUser)的所有权限，可以发送邀请，可以查看其它会员种子历史，可以更新IMDb信息。"

[level.UltimateUser]
level_id = 8
level = "UltimateUser"
days = 40
uploaded = "0"
downloaded = "4TB"
bonus = 0.0
score = 0
ratio = 6.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "享有制片人(ExtremeUser)的所有权限，首次升级该级别可自动获得2枚邀请名额。账号挂起永久保留，未挂起的情况下可以保留50周。取消一个月只能发送一个邀请的限制。"

[level.NexusMaster]
level_id = 9
level = "NexusMaster"
days = 50
uploaded = "0"
downloaded = "5TB"
bonus = 0.0
score = 0
ratio = 8.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "享有国际巨星(UltimateUser)的所有权限，首次升级该级别可自动获得3枚邀请名额，账号永久保存(无需挂起)。"

[level.VIP]
level_id = 0
level = "VIP"
days = 0
uploaded = "0"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 0.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "享有双倍积分特权。和影业帝国(NexusMaster)拥有相同权限并被认为是精英成员。免除自动降级。"
