url = ["https://www.hitpt.com/", ]
name = "百川"
nickname = "hitpt"
logo = "favicon.ico"
tracker = "hitpt.com|hitwh.oncampus.hitpt.com|tracker.hitpt.com"
sp_full = 65
limit_speed = 100
tags = "影视"
iyuu = 59
sign_in = true
get_info = true
repeat_torrents = true
brush_free = true
brush_rss = true
hr_discern = false
search_torrents = true
page_index = "index.php"
page_torrents = "torrents.php?incldead=1"
page_sign_in = "attendance.php"
page_control_panel = "usercp.php"
page_detail = "details.php?id={}"
page_download = "download.php?id={}&passkey={}"
page_user = "userdetails.php?id={}"
page_search = "torrents.php?search={}"
page_message = "messages.php"
page_hr = "myhr.php?hrtype=1&userid={}"
page_leeching = "getusertorrentlistajax.php?userid={}&type=leeching"
page_uploaded = "getusertorrentlistajax.php?userid={}&type=uploaded"
page_seeding = "getusertorrentlistajax.php?userid={}&type=seeding"
page_completed = "getusertorrentlistajax.php?userid={}&type=completed"
page_mybonus = "mybonus.php"
page_viewfilelist = "viewfilelist.php?id={}"
sign_info_title = "//td[@id='outer']//td[@class='embedded']/h2/text()"
sign_info_content = "//td[@id='outer']//td[@class='embedded']/table//td//text()"
hr = false
hr_rate = 2
hr_time = 10
my_invitation_rule = "//a[contains(@href,'invite.php?id=')]/following-sibling::text()[1]"
my_time_join_rule = "//td[contains(text(),'加入')]/following-sibling::td/span/@title"
my_latest_active_rule = "//td[contains(text(),'最近动向')]/following-sibling::td/span/@title"
my_uploaded_rule = "//span[@class='color_uploaded']/following-sibling::text()[1]"
my_downloaded_rule = "//span[@class='color_downloaded']/following-sibling::text()[1]"
my_ratio_rule = "//span[@class='color_ratio'][1]/following-sibling::text()[1]"
my_bonus_rule = "//span/a[@href='mybonus.php']/following-sibling::text()[1]"
my_per_hour_bonus_rule = "//div[contains(text(),'每小时')]/text()[1]"
my_score_rule = "//font[@class='color_bonus' and contains(text(),'积分')]/following-sibling::text()[1]"
my_level_rule = "//table[@id='info_block']//span/a[contains(@class,'_Name') and contains(@href,'userdetails.php?id=')]/@class"
my_passkey_rule = "//td[contains(text(),'密钥')]/following-sibling::td[1]/text()"
my_uid_rule = "//table[@id='info_block']//span/a[contains(@class,'_Name') and contains(@href,'userdetails.php?id=')]/@href"
my_hr_rule = "//a[@href='myhr.php']//text()"
my_leech_rule = "//img[@class='arrowdown'][1]/following-sibling::text()[1]"
my_publish_rule = "//p/preceding-sibling::b/text()[1]"
my_seed_rule = "//img[@class='arrowup'][1]/following-sibling::text()[1]"
my_seed_vol_rule = "//tr/td[3]"
my_mailbox_rule = "//a[@href='messages.php']/font[contains(text(),'条')]/text()[1]"
my_message_title = "//img[@alt='Unread']/parent::td/following-sibling::td/a[1]//text()"
my_notice_rule = "//a[@href='index.php']/font[contains(text(),'条')]/text()[1]"
my_notice_title = "//td[@class='text']/div/a"
my_notice_content = "//td[@class='text']/div/a/following-sibling::div"
torrents_rule = "//table[@class='torrents']/tr"
torrent_title_rule = ".//td/a[contains(@href,'detail')]/b/text()[last()]"
torrent_subtitle_rule = ".//a[contains(@href,'detail')]/parent::td/text()[last()]"
torrent_detail_url_rule = ".//td[@class='embedded']/a[contains(@href,'detail')]/@href"
torrent_category_rule = ".//td[@class='rowfollow nowrap'][1]/a[1]/img/@alt"
torrent_poster_rule = ".//table/tr/td[1]/img/@src"
torrent_magnet_url_rule = ".//a[contains(@href,'download')]/@href"
torrent_size_rule = ".//td[5]/text()"
torrent_progress_rule = ".//div[contains(@title,'ing')]/@title"
torrent_hr_rule = ".//table/tr/td/img[@class='hitandrun']/@title"
torrent_sale_rule = ".//img[contains(@class,'pro_')]/@alt"
torrent_sale_expire_rule = ".//td[@class='embedded']/img[contains(@class,'pro_')]/@onmouseover"
torrent_release_rule = ".//td[4]/span/@title"
torrent_seeders_rule = ".//td[6]/b/a/text()"
torrent_leechers_rule = ".//td[7]/b/a/text()"
torrent_completers_rule = ".//td[8]/a/b/text()"
detail_title_rule = "//h1/text()[1]"
detail_subtitle_rule = "//td[contains(text(),'副标题')]/following-sibling::td/text()[1]"
detail_download_url_rule = "//a[@class='index' and contains(@href,'download.php')]/@href"
detail_size_rule = "//td//b[contains(text(),'大小')]/following::text()[1]"
detail_category_rule = "//td/b[contains(text(),'类型')]/following-sibling::text()[1]"
detail_count_files_rule = "//td/b[contains(text(),'文件数')]/following-sibling::text()[1]"
detail_hash_rule = "//td/b[contains(text(),'Hash')]/following-sibling::text()[1]"
detail_free_rule = "//h1/b/font/@class"
detail_free_expire_rule = "//h1/b/span/@title"
detail_douban_rule = "//td/a[starts-with(@href,'https://movie.douban.com/subject/')][1]"
detail_imdb_rule = "//a[@class='faqlink' and starts-with(@href,'https://www.imdb.com/title/')]/@href"
detail_poster_rule = "//td/a/span[contains(text(),'简介')]/../../following-sibling::td//img[1]/@src"
detail_tags_rule = "//td[contains(text(),'标签')]/following-sibling::td//text()"
torrent_tags_rule = ".//a[contains(@href,'detail')]/../span[contains(@class,'tags')]/text()"
detail_hr_rule = "//h1/img[@class='hitandrun']/@title"
alive = true
page_pieces_hash_api = "api/pieces-hash"
pieces_repeat = false
proxy = true
structure = "NexusPHP"
type = "pt"
nation = "china"

[level.User]
level_id = 1
level = "User"
days = 0
uploaded = "0"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 0.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "新用户的默认级别。"

[level.PowerUser]
level_id = 2
level = "PowerUser"
days = 1
uploaded = "0"
downloaded = "10GB"
bonus = 0.0
score = 0
ratio = 1.5
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "可以直接发布种子；可以查看NFO文档；可以查看用户列表；可以请求续种；可以查看排行榜；可以查看其它用户的种子历史(如果用户隐私等级未设置为'强')；可以删除自己上传的字幕。"

[level.EliteUser]
level_id = 3
level = "EliteUser"
days = 1
uploaded = "0"
downloaded = "120GB"
bonus = 0.0
score = 0
ratio = 1.55
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "EliteUserxa0及以上用户封存账号后不会被删除。"

[level.CrazyUser]
level_id = 4
level = "CrazyUser"
days = 4
uploaded = "0"
downloaded = "300GB"
bonus = 0.0
score = 0
ratio = 2.05
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "得到一个邀请名额；可以在做种/下载/发布的时候选择匿名模式。"

[level.InsaneUser]
level_id = 5
level = "InsaneUser"
days = 6
uploaded = "0"
downloaded = "500GB"
bonus = 0.0
score = 0
ratio = 2.55
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "可以查看普通日志。"

[level.VeteranUser]
level_id = 6
level = "VeteranUser"
days = 8
uploaded = "0"
downloaded = "750GB"
bonus = 0.0
score = 0
ratio = 3.05
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "得到二个邀请名额；可以查看其它用户的评论、帖子历史。VeteranUserxa0及以上用户会永远保留账号。"

[level.ExtremeUser]
level_id = 7
level = "ExtremeUser"
days = 10
uploaded = "0"
downloaded = "1TB"
bonus = 0.0
score = 0
ratio = 3.55
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "可以更新过期的外部信息；可以查看ExtremeUser论坛。"

[level.UltimateUser]
level_id = 8
level = "UltimateUser"
days = 20
uploaded = "0"
downloaded = "1.5TB"
bonus = 0.0
score = 0
ratio = 4.05
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "得到三个邀请名额。"

[level.NexusMaster]
level_id = 9
level = "NexusMaster"
days = 50
uploaded = "0"
downloaded = "2TB"
bonus = 0.0
score = 0
ratio = 4.05
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "得到五个邀请名额。"

[level.VIP]
level_id = 0
level = "VIP"
days = 0
uploaded = "0"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 0.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "和NexusMaster拥有相同权限并被认为是精英成员。免除自动降级。"
