url = [ "https://zeus.hamsters.space/", "https://hudbt.hust.edu.cn/",]
name = "蝴蝶"
nickname = "hudbt"
logo = "favicon.ico"
tracker = "hudbt.hust.edu.cn"
sp_full = 100
limit_speed = 100
tags = "影视"
iyuu = 67
sign_in = false
get_info = true
repeat_torrents = true
brush_free = true
brush_rss = true
hr_discern = false
search_torrents = true
page_index = "index.php"
page_torrents = "torrents.php?incldead=1"
page_sign_in = "attendance.php"
page_control_panel = "usercp.php"
page_detail = "details.php?id={}"
page_download = "download.php?id={}&passkey={}"
page_user = "userdetails.php?id={}"
page_search = "torrents.php?incldead=1&search={}"
page_message = "messages.php"
page_hr = "myhr.php?hrtype=1&userid={}"
page_leeching = "getusertorrentlistajax.php?userid={}&type=leeching"
page_uploaded = "getusertorrentlistajax.php?userid={}&type=uploaded"
page_seeding = "getusertorrentlistajax.php?userid={}&type=seeding"
page_completed = "getusertorrentlistajax.php?userid={}&type=completed"
page_mybonus = "mybonus.php"
page_viewfilelist = "viewfilelist.php?id={}"
sign_info_title = "//td[@id='outer']//td[@class='embedded']/h2/text()"
sign_info_content = "//td[@id='outer']//td[@class='embedded']/table//td//text()"
hr = false
hr_rate = 2
hr_time = 10
my_invitation_rule = "//a[contains(@href,'invite.php')]/span[@id='invites']/text()"
my_time_join_rule = "//td[contains(text(),'加入')]/following-sibling::td/span/@title"
my_latest_active_rule = "//td[contains(text(),'最近动向')]/following-sibling::td/span/@title"
my_uploaded_rule = "//span[@class='color_uploaded']/following-sibling::span/text()[1]"
my_downloaded_rule = "//span[@class='color_downloaded']/following-sibling::text()[1]"
my_ratio_rule = "//span[@class='color_ratio' and contains(text(),'分享率')]/following-sibling::text()[1]"
my_bonus_rule = "//a[contains(@href,'mybonus.php')]/span[@id='bonus']/text()"
my_per_hour_bonus_rule = "//div[contains(text(),'每小时能获取')]/text()[1]"
my_score_rule = "//font[@class='color_bonus' and contains(text(),'积分')]/following-sibling::text()[1]"
my_level_rule = "//div[@id='header-info']//span/a[contains(@class,'_Name') and contains(@href,'userdetails.php?id=')]/@class"
my_passkey_rule = "//dt[contains(text(),'密钥')]/following-sibling::dd[1]/text()"
my_uid_rule = "//div[@id='header-info']//span/a[contains(@class,'_Name') and contains(@href,'userdetails.php?id=')]/@href"
my_hr_rule = "//a[@href='myhr.php']//text()"
my_leech_rule = "//img[@class='arrowdown']/following-sibling::text()[1]"
my_publish_rule = "//p/preceding-sibling::b/text()[1]"
my_seed_rule = "//img[@class='arrowup']/following-sibling::text()[1]"
my_seed_vol_rule = "//tr/td[3]"
my_mailbox_rule = "//a[contains(@href,'messages.php') and contains(text(),'条')]//text()[1]"
my_message_title = "//img[@alt='Unread']/parent::td/following-sibling::td/a[1]//text()"
my_notice_rule = "//a[contains(@href,'index.php') and contains(text(),'条')]//text()[1]"
my_notice_title = "//div[@id='news']/ul/li/a"
my_notice_content = "//div[@id='news']/ul/li/a/following-sibling::div/div/font"
torrents_rule = "//table[@id='torrents']/tbody/tr"
torrent_title_rule = ".//h2/a[contains(@href,'detail')]/parent::td/text()"
torrent_subtitle_rule = ".//h3/text()"
torrent_detail_url_rule = ".//h2/a/@href"
torrent_category_rule = ".//td[1]/a/img/@alt"
torrent_poster_rule = ".//table/tr/td[1]/img/@src"
torrent_magnet_url_rule = ".//td/div/div/div/ul/li/a[contains(@href, 'download')]/@href"
torrent_size_rule = ".//td[5]/text()"
torrent_progress_rule = ".//div[contains(@title,'ing')]/@title"
torrent_hr_rule = ".//table/tr/td/img[@class='hitandrun']/@title"
torrent_sale_rule = ".//td/div/div/div/ul/li/img/@class"
torrent_sale_expire_rule = ".//td/div/div/div/ul/li/img/@title"
torrent_release_rule = ".//td[4]//text()"
torrent_seeders_rule = ".//a[contains(@href,'#seeders')]/text()"
torrent_leechers_rule = ".//a[contains(@href,'#leechers')]/text()"
torrent_completers_rule = ".//a[contains(@href,'viewsnatches')]//text()"
detail_title_rule = "//h1/text()[1]"
detail_subtitle_rule = "//td[contains(text(),'副标题')]/following-sibling::td/text()[1]"
detail_download_url_rule = "//a[@class='index' and contains(@href,'download.php')]/@href"
detail_size_rule = "//td//b[contains(text(),'大小')]/following::text()[1]"
detail_category_rule = "//td/b[contains(text(),'类型')]/following-sibling::text()[1]"
detail_count_files_rule = "//td/b[contains(text(),'文件数')]/following-sibling::text()[1]"
detail_hash_rule = "//td/b[contains(text(),'Hash')]/following-sibling::text()[1]"
detail_free_rule = "//h1/b/font/@class"
detail_free_expire_rule = "//h1/b/span/@title"
detail_douban_rule = "//td/a[starts-with(@href,'https://movie.douban.com/subject/')][1]"
detail_imdb_rule = "//a[@class='faqlink' and starts-with(@href,'https://www.imdb.com/title/')]/@href"
detail_poster_rule = "//td/a/span[contains(text(),'简介')]/../../following-sibling::td//img[1]/@src"
detail_tags_rule = "//td[contains(text(),'标签')]/following-sibling::td//text()"
torrent_tags_rule = ".//a[contains(@href,'detail')]/../span[contains(@class,'tags')]/text()"
detail_hr_rule = "//h1/img[@class='hitandrun']/@title"
alive = true
page_pieces_hash_api = "api/pieces-hash"
pieces_repeat = false
proxy = true
imdb_search = "torrents.php?search_area=4&search={}"

[level.User]
level_id = 1
level = "User"
days = 0
uploaded = "0"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 0.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "新用户的默认级别。"

[level.PowerUser]
level_id = 2
level = "PowerUser"
days = 4
uploaded = "0"
downloaded = "50GB"
bonus = 0.0
score = 0
ratio = 1.05
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "得到一个邀请名额；可以直接发布种子；可以查看NFO文档；可以查看用户列表；可以请求续种；可以查看排行榜；可以查看其它用户的种子历史(如果用户隐私等级未设置为'强')；可以删除自己上传的字幕。"

[level.EliteUser]
level_id = 3
level = "EliteUser"
days = 8
uploaded = "0"
downloaded = "120GB"
bonus = 0.0
score = 0
ratio = 1.55
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "化蛹(EliteUser)xa0及以上用户封存账号后不会被删除。"

[level.CrazyUser]
level_id = 4
level = "CrazyUser"
days = 15
uploaded = "0"
downloaded = "300GB"
bonus = 0.0
score = 0
ratio = 2.05
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "得到一个邀请名额；可以发送邀请（注意：网站会视情况提高或者降低允许发送邀请的最低等级，此处不一定会及时修改）；可以在做种/下载/发布的时候选择匿名模式。"

[level.InsaneUser]
level_id = 5
level = "InsaneUser"
days = 25
uploaded = "0"
downloaded = "500GB"
bonus = 0.0
score = 0
ratio = 2.55
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "可以查看普通日志。"

[level.VeteranUser]
level_id = 6
level = "VeteranUser"
days = 40
uploaded = "0"
downloaded = "750GB"
bonus = 0.0
score = 0
ratio = 3.05
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "得到一个邀请名额；可以查看其它用户的评论、帖子历史。翩跹(VeteranUser)xa0及以上用户会永远保留账号。"

[level.ExtremeUser]
level_id = 7
level = "ExtremeUser"
days = 60
uploaded = "0"
downloaded = "1TB"
bonus = 0.0
score = 0
ratio = 3.55
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "可以更新过期的外部信息；可以查看ExtremeUser论坛。（未启用）"

[level.UltimateUser]
level_id = 8
level = "UltimateUser"
days = 80
uploaded = "0"
downloaded = "1.5TB"
bonus = 0.0
score = 0
ratio = 4.05
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "无"

[level.NexusMaster]
level_id = 9
level = "NexusMaster"
days = 100
uploaded = "0"
downloaded = "3TB"
bonus = 0.0
score = 0
ratio = 4.55
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "无"

[level.VIP]
level_id = 0
level = "VIP"
days = 0
uploaded = "0"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 0.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "和NexusMaster拥有相同权限并被认为是精英成员。免除自动降级自定发等级。"
