url = ["https://audiences.me/", ]
name = "观众"
nickname = "观众"
logo = "favicon.ico"
tracker = "t.audiences.me|tracker.cinefiles.info"
sp_full = 140
limit_speed = 95
tags = "综合,压制,官组,Diy,原盘,特效字幕,X265,Web,最速Web"
iyuu = 68
sign_in = true
sign_type = "NEXUS_SIGN"
get_info = true
repeat_torrents = true
brush_free = true
brush_rss = true
hr_discern = false
search_torrents = true
page_index = "index.php"
page_torrents = "torrents.php?incldead=1"
page_sign_in = "attendance.php"
page_control_panel = "usercp.php"
page_detail = "details.php?id={}"
page_download = "download.php?id={}&passkey={}"
page_user = "userdetails.php?id={}"
page_search = ["torrents.php?search={}", ]
page_message = "messages.php"
page_hr = "myhr.php?hrtype=1&userid={}"
page_leeching = "getusertorrentlistajax.php?userid={}&type=leeching"
page_uploaded = "getusertorrentlistajax.php?userid={}&type=uploaded"
page_seeding = "getusertorrentlistajax.php?userid={}&type=seeding"
page_completed = "getusertorrentlistajax.php?userid={}&type=completed"
page_mybonus = "mybonus.php"
page_viewfilelist = "viewfilelist.php?id={}"
sign_info_title = "//td[@id='outer']//td[@class='embedded']/h2/text()"
sign_info_content = "//td[@id='outer']//td[@class='embedded']/table//td//text()"
hr = false
hr_rate = 2
hr_time = 10
my_invitation_rule = "//td[normalize-space()='邀请']/following-sibling::td[1]//text()"
my_time_join_rule = "//td[contains(text(),'加入')]/following-sibling::td[1]//span/@title"
my_latest_active_rule = "//td[contains(text(),'最近动向')]/following-sibling::td[1]//span/@title"
my_uploaded_rule = "//span[contains(@class,'uploaded')]/span/text()"
my_downloaded_rule = "//span[contains(@class,'downloaded')]/span/text()"
my_ratio_rule = "//span[contains(@class,'ratio')]/span/text()"
my_bonus_rule = "//a[contains(@class,'metric--bonus')]/span/text()"
my_per_hour_bonus_rule = "//div[contains(text(),'每小时')]/../div[2]/text()[1]"
my_score_rule = "//span[contains(@class,'seeding-bonus')]/span/text()"
my_level_rule = "//div/span/b/@class"
my_passkey_rule = "//td[contains(text(),'密钥')]/following-sibling::td[1]/span[@id='passkey']/text()"
my_uid_rule = "//span/span[@class='nowrap']/a[contains(@class,'_Name') and contains(@href,'userdetails.php?id=')]/@href"
my_hr_rule = "//a[contains(@class,'-hr')]/span/text()"
my_leech_rule = "//span[contains(@class,'-active')]/a[contains(@class,'-link--leeching')]/text()"
my_publish_rule = "(/body//b)[1]/text()"
my_seed_rule = "//span[contains(@class,'-active')]/a[contains(@class,'-link--seeding')]/text()"
my_seed_vol_rule = "//b/following-sibling::text()[1]"
my_mailbox_rule = "//a[@href='messages.php']/font[contains(text(),'条')]/text()[1]"
my_message_title = "//img[@alt='Unread']/parent::td/following-sibling::td/a[1]//text()"
my_notice_rule = "//a[@href='index.php']/font[contains(text(),'条')]/text()[1]"
my_notice_title = "//td[@class='text']/div/a"
my_notice_content = "//td[@class='text']/div/a/following-sibling::div"
torrents_rule = "//table[contains(@class,'torrents')]//tr/td[not(@class)]/parent::tr"
torrent_title_rule = ".//a[contains(@href,'detail')]/b/text()[1]"
torrent_subtitle_rule = ".//tr/td[@class='embedded']/span[last()]/text()"
torrent_detail_url_rule = ".//td[@class='embedded']/a[contains(@href,'detail')]/@href"
torrent_category_rule = ".//td[@class='rowfollow nowrap'][1]/a[1]/img/@alt"
torrent_poster_rule = ".//table/tr/td[1]/img/@src"
torrent_magnet_url_rule = ".//a[contains(@href,'download')]/@href"
torrent_size_rule = ".//td[5]/text()"
torrent_progress_rule = ".//div[@class='torrents-progress']/@style"
torrent_hr_rule = ".//img[@class='hitandrun']/@title"
torrent_sale_rule = ".//img[contains(@class,'pro_')]/@alt"
torrent_sale_expire_rule = ".//tr/td[@class='embedded']/b/span[last()]/@title"
torrent_release_rule = ".//td[4]/span/@title"
torrent_seeders_rule = ".//td[6]//text()"
torrent_leechers_rule = ".//td[7]//text()"
torrent_completers_rule = ".//td[8]//text()"
detail_title_rule = "//h1/text()[1]"
detail_subtitle_rule = "//td[contains(text(),'副标题')]/following-sibling::td/text()[1]"
detail_download_url_rule = "//td[contains(text(),'种子链接')]/following-sibling::td/b/a/@href[1]"
detail_size_rule = "//td//b[contains(text(),'大小')]/following::text()[1]"
detail_category_rule = "//td/b[contains(text(),'类型')]/following-sibling::text()[1]"
detail_count_files_rule = "//td/b[contains(text(),'文件数')]/following-sibling::text()[1]"
detail_hash_rule = "//td[contains(text(),'Hash')]/text()"
detail_free_rule = "//h1/b/font/@class"
detail_free_expire_rule = "//h1/b/span/@title"
detail_douban_rule = "//td/div/a[starts-with(@href,'https://movie.douban.com/subject/')][1]"
detail_imdb_rule = "//a[@class='faqlink' and starts-with(@href,'https://www.imdb.com/title/')]/@href"
detail_poster_rule = "//td/a/span[contains(text(),'简介')]/../../following-sibling::td//img[1]/@src"
detail_tags_rule = "//td[contains(text(),'标签')]/following-sibling::td//text()"
torrent_tags_rule = ".//a[contains(@href,'detail')]/../span[contains(@class,'tags')]/text()"
detail_hr_rule = "//h1/img[@class='hitandrun']/@title"
alive = true
page_pieces_hash_api = "api/pieces-hash"
pieces_repeat = false
proxy = true
imdb_search = "torrents.php?search_area=2&search={}"
structure = "NexusPHP"
type = "pt"
nation = "china"
my_email_rule = "//td[contains(text(),'邮箱')]/following-sibling::td[1]//text()"
my_username_rule = "//table[@id='info_block']//span/a[contains(@class,'_Name') and contains(@href,'userdetails.php?id=')]/b/text()"
buy_page = "mybonus.php?action=exchange"

[buy_action]
"100GB上传流量" = "3"
"100GB下载流量" = "5"
"1个邀请名额" = "6"
"1个临时邀请名额" = "7"
"贵宾待遇" = "9"

[level.Peasant]
level_id = -1
level = "Peasant"
name = "悲惨世界"
days = 0
uploaded = "0"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 0.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "当以下情况时将被自动降至本级： 1.如果你已经下载了超过80GB，你的分享率却低于0.8。 2.如果你已经下载了超过200GB，你的分享率却低于0.85。 3.如果你已经下载了超过400GB，你的分享率却低于0.9。 4.如果你已经下载了超过800GB，你的分享率却低于0.95。 5.如果你已经下载了超过1024GB，你的分享率却低于1。 请记住，此等级意味着您的账号处于受限状态（参考用户等级详情），您需要尽快提升分享率！"

[level.PowerUser]
level_id = 2
level = "PowerUser"
name = "年轻气盛"
days = 5
uploaded = "0"
downloaded = "120GB"
bonus = 0.0
score = 100000
ratio = 2.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "必须注册至少5周，并且下载至少120G，分享率大于2.0，做种积分达到100,000。 当条件符合时将被自动提升。注意，无论何时，如果你的分享率低于1.9，你将自动降级。"

[level.EliteUser]
level_id = 3
level = "EliteUser"
name = "江湖儿女"
days = 15
uploaded = "0"
downloaded = "240GB"
bonus = 0.0
score = 180000
ratio = 2.5
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "必须注册至少15周，并且下载至少240G，分享率大于2.5，做种积分达到200,000。 当条件符合时将被自动提升。注意，无论何时，如果你的分享率低于2.4，你将自动降级。"

[level.CrazyUser]
level_id = 4
level = "CrazyUser"
name = "街头霸王"
days = 24
uploaded = "0"
downloaded = "400GB"
bonus = 0.0
score = 320000
ratio = 3.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "必须注册至少24周，并且下载至少400G，分享率大于3.0，做种积分达到400,000。 当条件符合时将被自动提升。注意，无论何时，如果你的分享率低于2.9，你将自动降级。"

[level.InsaneUser]
level_id = 5
level = "InsaneUser"
name = "步履不停"
days = 40
uploaded = "0"
downloaded = "600GB"
bonus = 0.0
score = 480000
ratio = 3.5
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "必须注册至少40周，并且下载至少600G，分享率大于3.5，做种积分达到640,000。 当条件符合时将被自动提升。注意，无论何时，如果你的分享率低于3.4，你将自动降级。"

[level.VeteranUser]
level_id = 6
level = "VeteranUser"
name = "杰出公民"
days = 60
uploaded = "0"
downloaded = "900GB"
bonus = 0.0
score = 660000
ratio = 4.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "必须注册至少60周，并且下载至少1024G，分享率大于4.0，做种积分达880,000。 当条件符合时将被自动提升。注意，无论何时，如果你的分享率低于3.9，你将自动降级。"

[level.ExtremeUser]
level_id = 7
level = "ExtremeUser"
name = "头号玩家"
days = 80
uploaded = "0"
downloaded = "2TB"
bonus = 0.0
score = 880000
ratio = 4.5
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = true
graduation = false
rights = "必须注册至少80周，并且下载至少2048G，分享率大于4.5，做种积分达1,200,000。 当条件符合时将被自动提升。注意，无论何时，如果你的分享率低于4.4，你将自动降级。"

[level.UltimateUser]
level_id = 8
level = "UltimateUser"
name = "一代宗师"
days = 100
uploaded = "0"
downloaded = "4TB"
bonus = 0.0
score = 1080000
ratio = 4.5
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = true
graduation = false
rights = "必须注册至少100周，并且下载至少4096G，分享率大于5.0，做种积分达1,500,000。 当条件符合时将被自动提升。注意，无论何时，如果你的分享率低于4.4，你将自动降级。"

[level.NexusMaster]
level_id = 9
level = "NexusMaster"
name = "教父"
days = 112
uploaded = "0"
downloaded = "8TB"
bonus = 0.0
score = 1280000
ratio = 5.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = true
graduation = true
rights = "必须注册至少112周，并且下载至少8192G，分享率大于6.0，做种积分达1,800,000。 当条件符合时将被自动提升。注意，无论何时，如果你的分享率低于5.9，你将自动降级。"

[level.Rainbow]
level_id = 0
level = "Rainbow"
name = "彩虹照耀"
days = 0
uploaded = "0"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 0.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = true
graduation = true
rights = "必须注册至少128周，并且下载至少10240G，分享率大于8，做种积分达2,400,000。（二周年后将依据用户总体做种积分水平，按比例计算具体要求） 当条件符合时将被自动提升。注意，无论何时， 彩虹照耀(Rainbow) 等级用户如果未达最新要求，你将自动降级。"

[level.VIP]
level_id = 0
level = "VIP"
name = "金玉满堂"
days = 0
uploaded = "0"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 0.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = true
graduation = true
rights = "由管理员仔细斟酌后分配给他们认为对于站点某方面有特殊贡献的用户。 （任何索取贵宾等级的要求将被自动无视）"

[level.Retiree]
level_id = 0
level = "Retiree"
name = "养老族"
days = 0
uploaded = "0"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 0.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = true
graduation = true
rights = "由管理员授予。"

[level.Uploader]
level_id = 0
level = "Uploader"
name = "发布员"
days = 0
uploaded = "0"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 0.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = true
graduation = true
rights = "点此查看Uploader招募相关"

[level.Moderator]
level_id = 0
level = "Moderator"
name = "总版主"
days = 0
uploaded = "0"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 0.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = true
graduation = true
rights = "无需多问，我们会找到你的！"

[level.DirectConnect]
level_id = 0
level = "DirectConnect"
name = "DirectConnect"
days = 0
uploaded = "0"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 0.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = true
graduation = true
rights = "1 - 1024"

[level.BitTorrent]
level_id = 0
level = "BitTorrent"
name = "BitTorrent"
days = 0
uploaded = "0"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 0.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = true
graduation = true
rights = "6881 - 6889"

[level.Kazza]
level_id = 0
level = "Kazza"
name = "Kazza"
days = 0
uploaded = "0"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 0.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = true
graduation = true
rights = "1214"

[level.Gnutella]
level_id = 0
level = "Gnutella"
name = "Gnutella"
days = 0
uploaded = "0"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 0.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = true
graduation = true
rights = "6346 - 6347"

[level.Emule]
level_id = 0
level = "Emule"
name = "Emule"
days = 0
uploaded = "0"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 0.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = true
graduation = true
rights = "4662"

[level.WinMX]
level_id = 0
level = "WinMX"
name = "WinMX"
days = 0
uploaded = "0"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 0.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = true
graduation = true
rights = "6699"

[level.User]
level_id = 1
level = "User"
name = "小鬼当家"
days = 0
uploaded = "0"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 0.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "新用户的默认级别；可以请求续种。"
