url = ["https://cspt.cc/", "https://cspt.date/", "https://cspt.top/", ]
name = "财神"
nickname = "财神"
logo = "favicon.ico"
tracker = "tracker.cspt.top|tracker.cspt.cc|tracker.cspt.date"
sp_full = 150
limit_speed = 100
tags = "影视"
iyuu = 120
sign_in = true
get_info = true
repeat_torrents = true
brush_free = true
brush_rss = true
hr_discern = false
search_torrents = true
page_index = "index.php"
page_torrents = "torrents.php?incldead=1"
page_sign_in = "attendance.php"
page_control_panel = "usercp.php"
page_detail = "details.php?id={}"
page_download = "download.php?id={}&passkey={}"
page_user = "userdetails.php?id={}"
page_search = "search.php?search={}"
page_message = "messages.php"
page_hr = "myhr.php?hrtype=1&userid={}"
page_leeching = "getusertorrentlistajax.php?userid={}&type=leeching"
page_uploaded = "getusertorrentlistajax.php?userid={}&type=uploaded"
page_seeding = "getusertorrentlistajax.php?userid={}&type=seeding"
page_completed = "getusertorrentlistajax.php?userid={}&type=completed"
page_mybonus = "mybonus.php"
page_viewfilelist = "viewfilelist.php?id={}"
sign_info_title = "//div[@id='outer']//td[@class='embedded']/h2/text()"
sign_info_content = "//div[@id='outer']//td[@class='embedded']/table//td//text()"
hr = false
hr_rate = 2
hr_time = 10
my_invitation_rule = "//a[contains(@href,'invite.php?id=')]/following-sibling::text()[1]"
my_time_join_rule = "//td[contains(text(),'加入')]/following-sibling::td/span/@title"
my_latest_active_rule = "//td[contains(text(),'最近动向')]/following-sibling::td/span/@title"
my_uploaded_rule = "//*[@id='arrowUpIconTitle']/../following-sibling::a/text()"
my_downloaded_rule = "//*[@id='arrowDownIconTitle']/../following-sibling::a/text()"
my_ratio_rule = "//*[@id='shareAndroidIconTitle']/../following-sibling::a/text()"
my_bonus_rule = "//*[@id='dolarIconTitle']/../following-sibling::a/text()"
my_per_hour_bonus_rule = "//td[contains(text(),'基本奖励')]/../td[last()]/text()"
my_score_rule = "//td[contains(text(),'做种积分')]/following-sibling::td/text()[1]"
my_level_rule = "//span[@class='user-id']/span/a[contains(@class,'_Name') and contains(@href,'userdetails.php?id=')]/@class"
my_passkey_rule = "//td[contains(text(),'密钥')]/following-sibling::td[1]/span/text()"
my_uid_rule = "//span/a[contains(@class,'_Name') and contains(@href,'userdetails.php?id=')]/@href"
my_hr_rule = "//a[@href='myhr.php']//text()"
my_leech_rule = "//*[contains(text(),'正在下载')]/../following-sibling::a/text()"
my_publish_rule = "//p/preceding-sibling::b/text()[1]"
my_seed_rule = "//*[contains(text(),'当前做种')]/../following-sibling::a/text()"
my_seed_vol_rule = "//p/preceding-sibling::div/div/text()[1]"
my_mailbox_rule = "//a[@href='messages.php']/font[contains(text(),'条')]/text()[1]"
my_message_title = "//img[@alt='Unread']/parent::td/following-sibling::td/a[1]//text()"
my_notice_rule = "//a[@href='index.php']/font[contains(text(),'条')]/text()[1]"
my_notice_title = "//td[@class='text']/div/a"
my_notice_content = "//td[@class='text']/div/a/following-sibling::div"
torrents_rule = "//div[@class='torrents']/div[contains(@class,'torrent-table-for-spider')]/div"
torrent_title_rule = ".//div[contains(@class,'torrent-title')]/div/div[1]/a[contains(@class,'torrent-info-text-name')]/@title"
torrent_subtitle_rule = ".//div[contains(@class,'torrent-title')]/div/div[2]//text()"
torrent_detail_url_rule = ".//div[contains(@class,'torrent-title')]/div/div[1]/a[contains(@class,'torrent-info-text-name')]/@title"
torrent_category_rule = ".//div[contains(@class,'torrent-cat')]//a/img/@title"
torrent_poster_rule = ".//table/tr/td[1]/img/@src"
torrent_magnet_url_rule = ".//div[contains(@class,'torrent-manage')]//a[contains(@href,'download.php?id=')]/@href"
torrent_size_rule = ".//div[contains(@class,'torrent-info-text torrent-info-text-size')]/text()"
torrent_progress_rule = ".//div[contains(@title,'ing')]/@title"
torrent_hr_rule = ".//table/tr/td/img[@class='hitandrun']/@title"
torrent_sale_rule = ".//img[contains(@class,'pro_')]/@alt"
torrent_sale_expire_rule = ".//img[contains(@class,'free')]/following-sibling::font/span/@title"
torrent_release_rule = ".//div[contains(@class,'torrent-info-text torrent-info-text-added')]/span/@title"
torrent_seeders_rule = ".//div[contains(@class,'torrent-info-text torrent-info-text-seeders')]/b/a//text()"
torrent_leechers_rule = ".//div[contains(@class,'torrent-info-text torrent-info-text-leechers')]/b/a//text()"
torrent_completers_rule = ".//div[contains(@class,'torrent-info-text torrent-info-text-finished')]//text()"
detail_title_rule = "//h1/text()[1]"
detail_subtitle_rule = "//td/span[contains(text(),'副标题')]/../following-sibling::td/text()"
detail_download_url_rule = "//td/span[contains(text(),'种子链接')]/../following-sibling::td/a/@href"
detail_size_rule = "//td//b[contains(text(),'大小')]/following::text()[1]"
detail_category_rule = "//td/b[contains(text(),'类型')]/following-sibling::text()[1]"
detail_count_files_rule = "//td/b[contains(text(),'文件数')]/following-sibling::text()[1]"
detail_hash_rule = "//td/b[contains(text(),'Hash')]/following-sibling::text()[1]"
detail_free_rule = "//h1/b/font/@class"
detail_free_expire_rule = "//h1/b/span/@title"
detail_douban_rule = "//td/div/a[starts-with(@href,'https://movie.douban.com/subject/')][1]"
detail_imdb_rule = "//a[@class='faqlink' and starts-with(@href,'https://www.imdb.com/title/')]/@href"
detail_poster_rule = "//td//a/span[contains(text(),'简介')]/../../../following-sibling::td//img[1]/@src"
detail_tags_rule = "//td/span[contains(text(),'标签')]/../following-sibling::td//text()"
torrent_tags_rule = ".//div[contains(@class,'torrent-title')]/div/div[3]/span/text()"
detail_hr_rule = "//h1/img[@class='hitandrun']/@title"
alive = true
page_pieces_hash_api = "api/pieces-hash"
pieces_repeat = true
proxy = true
imdb_search = "torrents.php?search_area=4&search={}"
structure = "NexusPHP"
type = "pt"
nation = "china"

[level.User]
level_id = 1
level = "User"
days = 0
uploaded = "0"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 0.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "新用户的默认级别。只能在每周六中午12点至每周日晚上11点59分发布种子。"

[level.PowerUser]
level_id = 2
level = "PowerUser"
days = 4
uploaded = "0"
downloaded = "50GB"
bonus = 0.0
score = 80000
ratio = 1.05
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "可以直接发布种子；可以查看NFO文档；可以查看用户列表；可以请求续种；可以发送邀请；可以查看排行榜；可以查看其它用户的种子历史(如果用户隐私等级未设置为'强')；可以删除自己上传的字幕。"

[level.EliteUser]
level_id = 3
level = "EliteUser"
days = 8
uploaded = "0"
downloaded = "120GB"
bonus = 0.0
score = 160000
ratio = 1.55
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "EliteUser及以上用户封存账号后不会被删除。"

[level.CrazyUser]
level_id = 4
level = "CrazyUser"
days = 15
uploaded = "0"
downloaded = "512GB"
bonus = 0.0
score = 300000
ratio = 2.05
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "可以在做种/下载/发布的时候选择匿名模式。"

[level.InsaneUser]
level_id = 5
level = "InsaneUser"
days = 25
uploaded = "0"
downloaded = "1TB"
bonus = 0.0
score = 600000
ratio = 2.55
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "可以查看普通日志。"

[level.VeteranUser]
level_id = 6
level = "VeteranUser"
days = 40
uploaded = "0"
downloaded = "2TB"
bonus = 0.0
score = 1000000
ratio = 3.05
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = true
graduation = false
rights = "可以查看其它用户的评论、帖子历史。VeteranUser及以上用户会永远保留账号。"

[level.ExtremeUser]
level_id = 7
level = "ExtremeUser"
days = 60
uploaded = "0"
downloaded = "4TB"
bonus = 0.0
score = 1500000
ratio = 3.55
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = true
graduation = false
rights = "可以更新过期的外部信息；可以查看ExtremeUser论坛。"

[level.UltimateUser]
level_id = 8
level = "UltimateUser"
days = 80
uploaded = "0"
downloaded = "8TB"
bonus = 0.0
score = 2200000
ratio = 4.05
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = true
graduation = false
rights = "无"

[level.NexusMaster]
level_id = 9
level = "NexusMaster"
days = 100
uploaded = "0"
downloaded = "16B"
bonus = 0.0
score = 3000000
ratio = 4.55
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = true
graduation = true
rights = "无"

[level.VIP]
level_id = 0
level = "VIP"
days = 0
uploaded = "0"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 0.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = true
graduation = true
rights = "1.VIP贵宾会员期限内不受系统分享率限制，可以在贵宾期限内无限制下载。可以在贵宾期限内无视H&R规则，畅快下载；2.VIP贵宾会员期限内不会因分享率过低而被系统封禁，免除自动降级，贵宾期限内不计算下行流量；3.VIP贵宾会员期限内开启排行榜查看权限；4.VIP贵宾会员期限内无视每年的年终考核和年中考核；5.拥有捐赠者黄星标识的会员，每小时做种获取魔力值双倍的奖励。"
