url = [ "https://pthome.net/", "https://www.pthome.net/",]
name = "铂金家"
nickname = "pthome"
logo = "favicon.ico"
tracker = "t.pthome.net|t.pthome.net|t.pthome.org"
sp_full = 110
limit_speed = 95
tags = "影视"
iyuu = 2
sign_in = true
get_info = true
repeat_torrents = true
brush_free = true
brush_rss = true
hr_discern = false
search_torrents = true
page_index = "index.php"
page_torrents = "torrents.php?incldead=1"
page_sign_in = "attendance.php"
page_control_panel = "usercp.php"
page_detail = "details.php?id={}"
page_download = "download.php?id={}"
page_user = "userdetails.php?id={}"
page_search = "torrents.php?search={}"
page_message = "messages.php"
page_hr = "myhr.php?hrtype=1&userid={}"
page_leeching = "getusertorrentlistajax.php?userid={}&type=leeching"
page_uploaded = "getusertorrentlistajax.php?userid={}&type=uploaded"
page_seeding = "getusertorrentlistajax.php?userid={}&type=seeding"
page_completed = "getusertorrentlistajax.php?userid={}&type=completed"
page_mybonus = "mybonus.php"
page_viewfilelist = "viewfilelist.php?id={}"
sign_info_title = "//td[@id='outer']//td[@class='embedded']/h2/text()"
sign_info_content = "//td[@id='outer']//td[@class='embedded']/table//td//text()"
hr = false
hr_rate = 2
hr_time = 10
my_invitation_rule = "//td/a[contains(@href,'invite.php?id=')]/following-sibling::text()[1]"
my_time_join_rule = "//td[contains(text(),'加入')]/following-sibling::td[1]//span/@title"
my_latest_active_rule = "//td[contains(text(),'最近')]/following-sibling::td[1]//span/@title"
my_uploaded_rule = "//font[@class='color_uploaded']/following-sibling::text()[1]"
my_downloaded_rule = "//font[@class='color_downloaded']/following-sibling::text()[1]"
my_ratio_rule = "//font[@class='color_ratio'][1]/following-sibling::text()[1]"
my_bonus_rule = "//a[@href='mybonus.php']/following-sibling::text()[1]"
my_per_hour_bonus_rule = "//div[contains(text(),'每小时')]/text()[1]"
my_score_rule = "//font[contains(text(),'做种积分')]/following::text()[1]"
my_level_rule = "//table[@id='info_block']//span/a[contains(@class,'_Name') and contains(@href,'userdetails.php?id=')]/@class"
my_passkey_rule = "//span[@id='passkey']/text()"
my_uid_rule = "//a[contains(@class,'_Name') and contains(@href,'userdetails.php?id=')]/@href"
my_hr_rule = "//a[@href='myhr.php']//text()"
my_leech_rule = "//img[@class='arrowdown'][1]/following-sibling::text()[1]"
my_publish_rule = "//p/preceding-sibling::b/text()[1]"
my_seed_rule = "//img[@class='arrowup'][1]/following-sibling::text()[1]"
my_seed_vol_rule = "//b/following-sibling::text()[1]"
my_mailbox_rule = "//a[@href='messages.php']/font[contains(text(),'条')]/text()[1]"
my_message_title = "//img[@alt='Unread']/parent::td/following-sibling::td/a[1]//text()"
my_notice_rule = "//a[@href='index.php']/font[contains(text(),'条')]/text()[1]"
my_notice_title = "//td[@class='text']/div/a"
my_notice_content = "//td[@class='text']/div/a/following-sibling::div"
torrents_rule = "//table[contains(@class,'torrents')]/tr"
torrent_title_rule = ".//a[contains(@href,'detail')]/b/text()[1]"
torrent_subtitle_rule = ".//a[contains(@href,'detail')]/../span[last()]/text()"
torrent_detail_url_rule = ".//td[@class='embedded']/a[contains(@href,'detail')]/@href"
torrent_category_rule = ".//td[@class='rowfollow nowrap'][1]/a[1]/img/@class"
torrent_poster_rule = ".//table/tr/td[1]/img/@src"
torrent_magnet_url_rule = ".//a[contains(@href,'download.php?id=')]/@href"
torrent_size_rule = ".//td[5]//text()"
torrent_progress_rule = ".//div[contains(@title,'ing')]/@title"
torrent_hr_rule = ".//table/tr/td/img[@class='hitandrun']/@title"
torrent_sale_rule = ".//img[contains(@class,'pro_')]/@alt"
torrent_sale_expire_rule = ".//img[contains(@class,'free')]/following-sibling::b/span/@title"
torrent_release_rule = ".//td[4]/span/@title"
torrent_seeders_rule = ".//td[6]/b/a/text()"
torrent_leechers_rule = ".//a[contains(@href,'#leechers')]//text()"
torrent_completers_rule = ".//a[contains(@href,'viewsnatches')]//text()"
detail_title_rule = "//h1/text()[1]"
detail_subtitle_rule = "//td[contains(text(),'副标题')]/following-sibling::td/text()[1]"
detail_download_url_rule = "//td[contains(text(),'种子链接')]/following-sibling::td/b/a/@href[1]"
detail_size_rule = "//td//b[contains(text(),'大小')]/following::text()[1]"
detail_category_rule = "//td/b[contains(text(),'类型')]/following-sibling::text()[1]"
detail_count_files_rule = "//td/b[contains(text(),'文件数')]/following-sibling::text()[1]"
detail_hash_rule = "//td[contains(text(),'Hash')]/text()[1]"
detail_free_rule = "//h1/b/font/@class"
detail_free_expire_rule = "//h1/b/span/@title"
detail_douban_rule = "//td/a[starts-with(@href,'https://movie.douban.com/subject/')][1]"
detail_imdb_rule = "//a[@class='faqlink' and starts-with(@href,'https://www.imdb.com/title/')]/@href"
detail_poster_rule = "//td/a/span[contains(text(),'简介')]/../../following-sibling::td//img[1]/@src"
detail_tags_rule = "//td[contains(text(),'标签')]/following-sibling::td//text()"
torrent_tags_rule = ".//a[contains(@href,'detail')]/../span[contains(@class,'tags')]/text()"
detail_hr_rule = "//h1/img[@class='hitandrun']/@title"
alive = true
page_pieces_hash_api = "api/pieces-hash"
pieces_repeat = false
proxy = true
imdb_search = "torrents.php?search_area=4&search={}"
structure = "NexusPHP"
type = "pt"
nation = "china"
my_email_rule = "//td[contains(text(),'邮箱')]/following-sibling::td[1]//text()"
my_username_rule = "//table[@id='info_block']//span/a[contains(@class,'_Name') and contains(@href,'userdetails.php?id=')]/b/text()"
buy_page = "mybonus.php?action=exchange"

[buy_action]
"100GB上传流量" = "3"
"100GB下载流量" = "5"
"1个邀请名额" = "6"
"1个临时邀请名额" = "7"
"贵宾待遇" = "9"

[level.User]
level_id = 1
level = "User"
days = 0
uploaded = "0"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 0.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "新用户的默认级别。"

[level.PowerUser]
level_id = 2
level = "PowerUser"
days = 4
uploaded = "0"
downloaded = "200GB"
bonus = 0.0
score = 20000
ratio = 1.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "可以查看NFO文档；可以查看用户列表；可以请求续种；可以查看排行榜；可以查看其它用户的种子历史(如果用户隐私等级未设置为'强')；可以删除自己上传的字幕。可以浏览论坛邀请专版。"

[level.EliteUser]
level_id = 3
level = "EliteUser"
days = 8
uploaded = "0"
downloaded = "350GB"
bonus = 0.0
score = 50000
ratio = 1.1
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "EliteUserxa0及以上用户封存账号后不会被删除"

[level.CrazyUser]
level_id = 4
level = "CrazyUser"
days = 15
uploaded = "0"
downloaded = "500GB"
bonus = 0.0
score = 200000
ratio = 1.2
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "可以在做种/下载/发布的时候选择匿名模式。"

[level.InsaneUser]
level_id = 5
level = "InsaneUser"
days = 25
uploaded = "0"
downloaded = "1TB"
bonus = 0.0
score = 400000
ratio = 1.3
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "可以查看普通日志"

[level.VeteranUser]
level_id = 6
level = "VeteranUser"
days = 40
uploaded = "0"
downloaded = "2TB"
bonus = 0.0
score = 600000
ratio = 1.5
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = true
graduation = false
rights = "可以查看其它用户的评论、帖子历史。VeteranUserxa0及以上用户会永远保留账号。"

[level.ExtremeUser]
level_id = 7
level = "ExtremeUser"
days = 60
uploaded = "0"
downloaded = "3TB"
bonus = 0.0
score = 800000
ratio = 1.5
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = true
graduation = false
rights = "可以更新过期的外部信息；可以查看ExtremeUser论坛。"

[level.UltimateUser]
level_id = 8
level = "UltimateUser"
days = 80
uploaded = "0"
downloaded = "4TB"
bonus = 0.0
score = 1000000
ratio = 1.7
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = true
graduation = false
rights = "同ExtremeUser等级权限"

[level.NexusMaster]
level_id = 9
level = "NexusMaster"
days = 100
uploaded = "0"
downloaded = "6TB"
bonus = 0.0
score = 1200000
ratio = 1.8
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = true
graduation = true
rights = "同ExtremeUser等级权限"

[level.VIP]
level_id = 0
level = "VIP"
days = 0
uploaded = "0"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 0.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = true
graduation = true
rights = "和NexusMaster拥有相同权限并被认为是精英成员。免除自动降级。"
