url = ["https://fsm.name/", ]
name = "飞天拉面"
nickname = "fsm"
logo = "favicon.ico"
tracker = "creditracker"
sp_full = 300
limit_speed = 100
tags = "影视"
iyuu = 0
sign_in = false
get_info = true
repeat_torrents = true
brush_free = true
brush_rss = true
hr_discern = false
search_torrents = false
page_index = "Index"
page_torrents = "torrents.php?incldead=1"
page_sign_in = "Users/me"
page_control_panel = "usercp.php"
page_detail = "Torrents/details?tid={}"
page_download = "Torrents/download?passkey={}&tid={}"
page_user = "Users/profile?uid={}"
page_search = "Torrents?type=0&systematics=2&keyword={}"
page_message = "Mail/list?type=receive"
page_hr = "myhr.php?hrtype=1&userid={}"
page_leeching = "Torrents/myDownload"
page_uploaded = "getusertorrentlistajax.php?userid={}&type=uploaded"
page_seeding = "Torrents/mySeed"
page_completed = "getusertorrentlistajax.php?userid={}&type=completed"
page_mybonus = "Points"
page_viewfilelist = "viewfilelist.php?id={}"
sign_info_title = "//td[@id=\"outer\"]//td[@class=\"embedded\"]/h2/text()"
sign_info_content = "//td[@id=\"outer\"]//td[@class=\"embedded\"]/table//td//text()"
hr = false
hr_rate = 2
hr_time = 10
my_invitation_rule = "invite"
my_time_join_rule = "//th[contains(text(),\"加入\")]/following-sibling::td/text()"
my_latest_active_rule = "//td[contains(text(),\"最近动向\")]/following-sibling::td/span/@title"
my_uploaded_rule = "upload"
my_downloaded_rule = "download"
my_ratio_rule = "//div//text[contains(text(),\"分享率\")]/following-sibling::text()"
my_bonus_rule = "point"
my_per_hour_bonus_rule = "seedGH"
my_score_rule = "//font[@class=\"color_bonus\" and contains(text(),\"积分\")]/following-sibling::text()[1]"
my_level_rule = "//div/a[contains(@href,\"/Users/profile?uid=\")]/@class"
my_passkey_rule = "//div[contains(text(),\"Passkey\")]/following-sibling::input/@value"
my_uid_rule = "uid"
my_hr_rule = "//a[@href=\"myhr.php\"]//text()"
my_leech_rule = "nowActiveDownload"
my_publish_rule = "torrent"
my_seed_rule = "nowActiveUpload"
my_seed_vol_rule = "nowActiveUploadSize"
my_mailbox_rule = "count"
my_message_title = "//button[text()=\"已读\"]/parent::div/preceding-sibling::div[1]/text()"
my_notice_rule = "//a[@href=\"index.php\"]/font[contains(text(),\"条\")]/text()[1]"
my_notice_title = "//td[@class=\"text\"]/div/a"
my_notice_content = "//td[@class=\"text\"]/div/a/following-sibling::div"
torrents_rule = "//table[@class=\"table table-bordered\"]//tr"
torrent_title_rule = ".//td[3]//a[contains(@href,\"/Torrents/details?tid=\")]/text()"
torrent_subtitle_rule = ".//a[contains(@href,\"detail\")]/parent::td/text()[last()]"
torrent_detail_url_rule = ".//td/a[contains(@href,\"/Torrents/details?tid=\")]/@href"
torrent_category_rule = ".//td[1]//a[contains(@href,\"/Torrents?type\")]/text()"
torrent_poster_rule = ".//table/tr/td[1]/img/@src"
torrent_magnet_url_rule = ".//a[contains(@href,\"download\") and contains(@href,\"passkey\")]/@href"
torrent_size_rule = ".//td[7]//text()"
torrent_hr_rule = ".//table/tr/td/img[@class=\"hitandrun\"]/@title"
torrent_sale_rule = ".//span[contains(@class,\"badge bg-primary\")]/text()"
torrent_sale_expire_rule = ".//img[contains(@class,\"free\")]/following-sibling::font/span/@title"
torrent_release_rule = ".//td[6]/span/@title"
torrent_seeders_rule = ".//td[8]//text()"
torrent_leechers_rule = ".//td[9]//text()"
torrent_completers_rule = ".//td[10]//text()"
detail_title_rule = "//h1/text()[1]"
detail_subtitle_rule = "//td[contains(text(),\"副标题\")]/following-sibling::td/text()[1]"
detail_download_url_rule = "//a[@class=\"index\" and contains(@href,\"download.php\")]/@href"
detail_size_rule = "//td//b[contains(text(),\"大小\")]/following::text()[1]"
detail_category_rule = "//td/b[contains(text(),\"类型\")]/following-sibling::text()[1]"
detail_count_files_rule = "//td/b[contains(text(),\"文件数\")]/following-sibling::text()[1]"
detail_hash_rule = "//td/b[contains(text(),\"Hash\")]/following-sibling::text()[1]"
detail_free_rule = "//h1/b/font/@class"
detail_free_expire_rule = "//h1/b/span/@title"
detail_douban_rule = "//td/a[starts-with(@href,\"https://movie.douban.com/subject/\")][1]"
detail_imdb_rule = "//a[@class=\"faqlink\" and starts-with(@href,\"https://www.imdb.com/title/\")]/@href"
detail_poster_rule = "//td/a/span[contains(text(),\"简介\")]/../../following-sibling::td//img[1]/@src"
detail_tags_rule = "//td[contains(text(),\"标签\")]/following-sibling::td//text()"
torrent_tags_rule = ".//a[contains(@href,\"detail\")]/../span[contains(@class,\"tags\")]/text()"
detail_hr_rule = "//h1/img[@class=\"hitandrun\"]/@title"
alive = true
page_pieces_hash_api = "api/pieces-hash"
pieces_repeat = false
proxy = true
