url = [ "https://sharkpt.net/",]
name = "鲨鱼"
nickname = "sharkpt"
logo = "favicon.ico"
tracker = "tracker.sharkpt.net"
sp_full = 100
limit_speed = 100
tags = "影视"
iyuu = 78
sign_in = true
get_info = true
repeat_torrents = true
brush_free = true
brush_rss = true
hr_discern = false
search_torrents = true
page_index = "index.php"
page_torrents = "torrents.php?incldead=1"
page_sign_in = "attendance.php"
page_control_panel = "usercp.php"
page_detail = "details.php?id={}"
page_download = "download.php?id={}&passkey={}"
page_user = "userdetails.php?id={}"
page_search = "torrents.php?search={}"
page_message = "messages.php"
page_hr = "myhr.php?hrtype=1&userid={}"
page_leeching = "getusertorrentlistajax.php?userid={}&type=leeching"
page_uploaded = "getusertorrentlistajax.php?userid={}&type=uploaded"
page_seeding = "getusertorrentlistajax.php?userid={}&type=seeding"
page_completed = "getusertorrentlistajax.php?userid={}&type=completed"
page_mybonus = "mybonus.php"
page_viewfilelist = "viewfilelist.php?id={}"
sign_info_title = "//td[@id=\"nav_block\"]//td[@class=\"embedded\"]/h2/text()"
sign_info_content = "//td[@id=\"nav_block\"]//td[@class=\"embedded\"]/table//td//text()"
hr = false
hr_rate = 2
hr_time = 10
my_invitation_rule = "//div[contains(text(),\"鱼饵数\")]/following-sibling::div//text()[1]"
my_time_join_rule = "//td[contains(text(),\"加入\")]/following-sibling::td/span/@title"
my_latest_active_rule = "//td[contains(text(),\"最近动向\")]/following-sibling::td/span/@title"
my_uploaded_rule = "//div[contains(text(),\"上传量\")]/following-sibling::div//text()[1]"
my_downloaded_rule = "//div[contains(text(),\"下载量\")]/following-sibling::div//text()[1]"
my_ratio_rule = "//font[@class=\"color_ratio\"][1]/following-sibling::text()[1]"
my_bonus_rule = "//div[contains(text(),\"鲨币值\")]/following-sibling::div/@title"
my_per_hour_bonus_rule = "//div[contains(text(),\"每小时能获取\")]/text()[1]"
my_score_rule = "//div[contains(text(),\"做种积分\")]/following-sibling::div//text()[1]"
my_level_rule = "//div[@class=\"nowrap user-name\"]/a[contains(@class,\"_Name\") and contains(@href,\"userdetails.php?id=\")]/@class"
my_passkey_rule = "//td[contains(text(),\"密钥\")]/following-sibling::td[1]/text()"
my_uid_rule = "//div[@class=\"nowrap user-name\"]/a[contains(@class,\"_Name\") and contains(@href,\"userdetails.php?id=\")]/@href"
my_hr_rule = "//div[contains(text(),\"H&R\")]/following-sibling::div//text()[1]"
my_leech_rule = "//div[contains(text(),\"当前下载\")]/following-sibling::div//text()[1]"
my_publish_rule = "//p/preceding-sibling::b/text()[1]"
my_seed_rule = "//div[contains(text(),\"当前上传\")]/following-sibling::div//text()[1]"
my_seed_vol_rule = "//p/preceding-sibling::text()[1]"
my_mailbox_rule = "//*[name()=\"shark-notification\"]/@content"
my_message_title = "//img[@alt=\"Unread\"]/parent::td/following-sibling::td/a[1]//text()"
my_notice_rule = "//*[name()=\"shark-notification\"]/@content1"
my_notice_title = "//td[@class=\"text\"]/div/a"
my_notice_content = "//td[@class=\"text\"]/div/a/following-sibling::div"
torrents_rule = "//div[contains(@class,\"torrent-item\")]"
torrent_title_rule = ".//div[contains(@class,\"torrent-info\")]/div/a/text()"
torrent_subtitle_rule = ".//div[contains(@class,\"torrent-info\")]/div[@class=\"torrent-subtitle\"]/text()"
torrent_detail_url_rule = ".//div[contains(@class,\"torrent-info\")]/div/a/@href"
torrent_category_rule = ".//div[contains(@class,\"torrent-category\")]/img/@src"
torrent_poster_rule = ".//table/tr/td[1]/img/@src"
torrent_magnet_url_rule = ".//div[contains(@class,\"torrent-actions\")]/shark-icon[1]/@onclick"
torrent_size_rule = ".//div[contains(@class,\"torrent-size\")]/text()"
torrent_tags_rule = ".//div[contains(@class,\"torrent-tags\")]/span/a/text()"
torrent_hr_rule = ".//table/tr/td/img[@class=\"hitandrun\"]/@title"
torrent_sale_rule = ".//div[contains(@class,\"torrent-tags\")]/span/text()"
torrent_sale_expire_rule = ".//font[contains(@class,\"free\")]/span/@title"
torrent_release_rule = ".//div[contains(@class,\"torrent-when\")]/span/@title"
torrent_seeders_rule = ".//div[contains(@class,\"torrent-seeders\")]//text()"
torrent_leechers_rule = ".//div[contains(@class,\"torrent-leechers\")]//text()"
torrent_completers_rule = ".//div[contains(@class,\"torrent-snatches\")]//text()"
detail_title_rule = "//h1[@id=\"top\"]/text()[1]"
detail_subtitle_rule = "//td[contains(text(),\"副标题\")]/following-sibling::td/text()[1]"
detail_download_url_rule = "//a[@class=\"index\" and contains(@href,\"download.php\")]/@href"
detail_size_rule = "//td//b[contains(text(),\"大小\")]/following::text()[1]"
detail_category_rule = "//td/b[contains(text(),\"类型\")]/following-sibling::text()[1]"
detail_count_files_rule = "//td/b[contains(text(),\"文件数\")]/following-sibling::text()[1]"
detail_hash_rule = "//td/b[contains(text(),\"Hash\")]/following-sibling::text()[1]"
detail_free_rule = "//h1/b/font/@class"
detail_free_expire_rule = "//h1/b/span/@title"
detail_douban_rule = "//td/a[starts-with(@href,\"https://movie.douban.com/subject/\")][1]"
detail_imdb_rule = "//a[@class=\"faqlink\" and starts-with(@href,\"https://www.imdb.com/title/\")]/@href"
detail_poster_rule = "//td/a/span[contains(text(),\"简介\")]/../../following-sibling::td//img[1]/@src"
detail_tags_rule = "//td[contains(text(),\"标签\")]/following-sibling::td//text()"
detail_hr_rule = "//h1/img[@class=\"hitandrun\"]/@title"
alive = false
page_pieces_hash_api = "api/pieces-hash"
pieces_repeat = false
proxy = true

[level.User]
level_id = 1
level = "User"
days = 0
uploaded = "0"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 0.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "新用户的默认级别。"

[level.PowerUser]
level_id = 2
level = "PowerUser"
days = 5
uploaded = "0"
downloaded = "150GB"
bonus = 0.0
score = 100000
ratio = 2.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "得到一个邀请名额；可以查看用户列表；可以请求续种；可以查看NFO文档；可以查看其它用户的种子历史(如果用户隐私等级未设置为\"强\")；可以直接发布种子；可以删除自己上传的字幕。"

[level.EliteUser]
level_id = 3
level = "EliteUser"
days = 15
uploaded = "0"
downloaded = "300GB"
bonus = 0.0
score = 150000
ratio = 2.5
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "得到两个邀请名额；可以查看排行榜。"

[level.CrazyUser]
level_id = 4
level = "CrazyUser"
days = 25
uploaded = "0"
downloaded = "450GB"
bonus = 0.0
score = 300000
ratio = 3.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "得到三个邀请名额；可以购买、发送邀请；可以在做种、下载、发布的时候选择匿名模式。"

[level.InsaneUser]
level_id = 5
level = "InsaneUser"
days = 40
uploaded = "0"
downloaded = "600GB"
bonus = 0.0
score = 450000
ratio = 3.5
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "得到四个邀请名额；可以查看普通日志。"

[level.VeteranUser]
level_id = 6
level = "VeteranUser"
days = 55
uploaded = "0"
downloaded = "750GB"
bonus = 0.0
score = 650000
ratio = 4.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "得到五个邀请名额；可以查看其它用户的评论、帖子历史。"

[level.ExtremeUser]
level_id = 7
level = "ExtremeUser"
days = 70
uploaded = "0"
downloaded = "1024GB"
bonus = 0.0
score = 800000
ratio = 4.5
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "得到六个邀请名额；可以更新过期的外部信息。ExtremeUserxa0及以上用户会永远保留账号。"

[level.UltimateUser]
level_id = 8
level = "UltimateUser"
days = 90
uploaded = "0"
downloaded = "4TB"
bonus = 0.0
score = 1000000
ratio = 5.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "得到七个邀请名额；可以查看种子结构。"

[level.NexusMaster]
level_id = 9
level = "NexusMaster"
days = 110
uploaded = "0"
downloaded = "8TB"
bonus = 0.0
score = 1250000
ratio = 5.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "得到八个邀请名额。"

[level.VIP]
level_id = 0
level = "VIP"
days = 0
uploaded = "0"
downloaded = "0"
bonus = 0.0
score = 0
ratio = 0.0
torrents = 0
leeches = 0
seeding_delta = 0.0
keep_account = false
graduation = false
rights = "和NexusMaster拥有相同权限并被认为是精英成员。免除自动降级。"
